### ISSUE TITLE
Windows 64 bit machine - installation issue

### ISSUE THREAD

**Issue by svlungade** [ibmdb/node-ibm_db#105]
> ibm_db@0.0.19 install D:\Swapnil\GITRepo\LEAP\node_modules\ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo EAI_AGAIN public.dhe.ibm.com:80
    at Object.exports._errnoException (util.js:874:11)
    at errnoException (dns.js:31:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
 npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ibm_db"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@0.0.19 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@0.0.19 install script 'node installer/driverInstall.js'.
npm ERR! This is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

**Comment by svlungade** [comment]
issue was with the cli driver
