### ISSUE TITLE
Install Fails for latest code on CentOS 7

### ISSUE THREAD

**Issue by mafischer** [ibmdb/node-ibm_db#140]
info install ibm_db@1.0.0
20402 verbose unsafe-perm in lifecycle false
20403 info ibm_db@1.0.0 Failed to exec install script
20404 verbose unlock done using /root/.npm/_locks/ibm-db-7528beb3c9b86e0d.lock for /app/node_modules/@walmart/bnr-api/node_modules/ibm_db
20405 verbose about to build /app/node_modules/@walmart/bnr-api
20406 verbose unlock done using /root/.npm/_locks/walmart-bnr-api-70c96d070f186863.lock for /app/node_modules/@walmart/bnr-api
20407 verbose stack Error: ibm_db@1.0.0 install: `node installer/driverInstall.js`
20407 verbose stack Exit status 1
20407 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
20407 verbose stack     at emitTwo (events.js:87:13)
20407 verbose stack     at EventEmitter.emit (events.js:172:7)
20407 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
20407 verbose stack     at emitTwo (events.js:87:13)
20407 verbose stack     at ChildProcess.emit (events.js:172:7)
20407 verbose stack     at maybeClose (internal/child_process.js:827:16)
20407 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
20408 verbose pkgid ibm_db@1.0.0
20409 verbose cwd /app
20410 error Linux 3.10.0-123.el7.x86_64
20411 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@walmart/bnr-api@0.0.90"
20412 error node v4.4.7
20413 error npm  v2.15.8
20414 error code ELIFECYCLE
20415 error ibm_db@1.0.0 install: `node installer/driverInstall.js`
20415 error Exit status 1
20416 error Failed at the ibm_db@1.0.0 install script 'node installer/driverInstall.js'.
20416 error This is most likely a problem with the ibm_db package,
20416 error not with npm itself.
20416 error Tell the author that this fails on your system:
20416 error     node installer/driverInstall.js
20416 error You can get information on how to open an issue for this project with:
20416 error     npm bugs ibm_db
20416 error Or if that isn't available, you can get their info via:
20416 error
20416 error     npm owner ls ibm_db
20416 error There is likely additional logging output above.

**Comment by mafischer** [comment]
This turned out to be an issue with node-gyp not being able to download header files from nodejs.org from within the intranet.

This can be solved with by using a proxy `npm install --proxy=http://your_proxy` or hosting the header files internally and using `npm install --disturl=http://your_node_dist_location`
