### ISSUE TITLE
npm install failed on RedHat 7.2

### ISSUE THREAD

**Issue by BrianJZhang2** [ibmdb/node-ibm_db#165]
I got this error, my gcc version is 4.8.5
```
# npm install

> ibm_db@1.0.0 install ***/node_modules/ibm_db
> node installer/driverInstall.js

module.js:442
    throw err;
    ^

Error: Cannot find module '***/node_modules/ibm_db/installer/driverInstall.js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (node.js:348:7)
    at startup (node.js:140:9)
    at node.js:463:3
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Linux 3.10.0-327.28.3.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@1.0.0 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@1.0.0 install script 'node installer/driverInstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ibm_db
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     ***/npm-debug.log
```

**Comment by bimalkjha** [comment]
@BrianJZhang2 Could you please try using another node.js version ex 4.4.5? The error says, npm failed to download ibm_db code from npm.js. So, ibm_db/installer/driverInstall.js can not be accessed. Also, if possible check with other system. We need more info as it is working fine for us. Thanks.

**Comment by bimalkjha** [comment]
@BrianJZhang2 I think it might be happening due to tar.gz issue. Please use below command and let us know the result:
```
npm install git+https://git@github.com/ibmdb/node-ibm_db.git
```

Thanks and Regards,
Bimal Jha
