### ISSUE TITLE
test-querySync-select-with-execption.js broken on all platforms

### ISSUE THREAD

**Issue by GeorgeAdams95** [ibmdb/node-ibm_db#172]
I am getting the following error when running the above test:

```
+if( /^win/.test(process.platform) )
 ^^
SyntaxError: Unexpected token if
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by GeorgeAdams95** [comment]
#159 was where this fix was added for windows
