### ISSUE TITLE
test-call-async and test-call-stmt failing

### ISSUE THREAD

**Issue by GeorgeAdams95** [ibmdb/node-ibm_db#174]
I am getting the following errors:

```
# Running test for [[01;29mDB2[01;0m] : test-call-async ... [01;31mfail [01;0m 
# [01;34mStdout: [01;0m 
# newton.proc1 dropped.
# created newton.proc1...
# return value =  0 verygood
# [01;31mStderr: [01;0m 
# assert.js:85
# throw new assert.AssertionError({
# ^
# AssertionError: [ 0, 'verygood' ] deepEqual [ 4, 'verygood' ]
# at /tmp/a6fba419-24ff-46f9-9d96-42985da7b3c8/ibm_db/test/test-call-async.js:34:16
```

```
# Running test for [[01;29mDB2[01;0m] : test-call-stmt ... [01;31mfail [01;0m 
# [01;34mStdout: [01;0m 
# [01;31mStderr: [01;0m 
# assert.js:85
# throw new assert.AssertionError({
# ^
# AssertionError: [ 0, 'verygood' ] deepEqual [ 4, 'verygood' ]
# at /tmp/a6fba419-24ff-46f9-9d96-42985da7b3c8/ibm_db/test/test-call-stmt.js:24:12
# at /tmp/a6fba419-24ff-46f9-9d96-42985da7b3c8/ibm_db/lib/odbc.js:100:5
# at /tmp/a6fba419-24ff-46f9-9d96-42985da7b3c8/ibm_db/lib/odbc.js:207:16
```
Using IBM NODE 6.7.0.0 and these tests are passing on all our other platforms

**Comment by rhtpandeyIN** [comment]
As per our chat conversation updating few key notes here:
1) These test cases are working fine in all other machine except  s390 linux machine. (using node 6.7.0.0)

**Comment by GeorgeAdams95** [comment]
This is also appearing on linux-x64 and x86....

**Comment by GeorgeAdams95** [comment]
after talking with @bimalkjha, we reckon that part of the problem is that proc1 is hard coded to use newton as the schema rather than the schema that is set in common.js

**Comment by GeorgeAdams95** [comment]
These two tests are also failing on windows:
```
# Running test for [[01;29mDB2[01;0m] : test-call-async ... [01;31mfail [01;0m 
# [01;34mStdout: [01;0m 
# created proc1...
# return value =  undefined undefined
# [01;31mStderr: [01;0m 
# assert.js:85
# throw new assert.AssertionError({
# ^
# AssertionError: ODBCResult { fetchMode: 4 } deepEqual [ 4, 'verygood' ]
# at C:\Users\jenkins\AppData\Local\Temp\8f15fbd6-dfe2-4d9e-99e3-2a5fbd6dc2b4\ibm_db\test\test-call-async.js:34:16
# Running test for [[01;29mDB2[01;0m] : test-call-stmt ... [01;31mfail [01;0m 
# [01;34mStdout: [01;0m 
# [01;31mStderr: [01;0m 
# assert.js:85
# throw new assert.AssertionError({
# ^
# AssertionError: true deepEqual [ 4, 'verygood' ]
# at C:\Users\jenkins\AppData\Local\Temp\8f15fbd6-dfe2-4d9e-99e3-2a5fbd6dc2b4\ibm_db\test\test-call-stmt.js:25:12
# at C:\Users\jenkins\AppData\Local\Temp\8f15fbd6-dfe2-4d9e-99e3-2a5fbd6dc2b4\ibm_db\lib\odbc.js:100:5
# at C:\Users\jenkins\AppData\Local\Temp\8f15fbd6-dfe2-4d9e-99e3-2a5fbd6dc2b4\ibm_db\lib\odbc.js:207:16
```
