### ISSUE TITLE
Error: Module Version mismatch. Expected 47, got 48

### ISSUE THREAD

**Issue by ljerka** [ibmdb/node-ibm_db#176]
I am getting this exception:

Error: Module version mismatch. Expected 47, got 48.
at Error (native)
at Object.Module._extensions..node (module.js:440:18)
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at Module.require (module.js:367:17)
at require (internal/module.js:16:19)
at bindings (D:\Projects\node_modules\ibm_db\node_modules\bindings\bindings.js:76:44)
at Object. (D:\Projects\node_modules\ibm_db\lib\odbc.js:27:31)
at Module._compile (module.js:413:34)
at Object.Module._extensions..js (module.js:422:10)

I saw on the similar [closed issue](https://github.com/ibmdb/node-ibm_db/issues/102) that the problem was in node version, but that shouldn't be my case since I have v.5.8.0. I'm on win7, 64bit, npm v.3.10.8.

**Comment by rhtpandeyIN** [comment]
Hi @ljerka ,

Node-ibm_db do not support node V5.X for windows. (as node v5.x is no longer supported by nodeJs itself), we suggest you to use node V6 or earlier versions of node as per your requirement.

**Comment by ljerka** [comment]
I tought node v5.x is supported since in #102 in the post on the end you wrote

> now node.js/ibm_db is also supporting V5.x on Windows. 

But ok, I'll upgrade to node v.6 and will let you know if that fixed the issue.

**Comment by ljerka** [comment]
After upgrading, the error is gone. Thanx!

**Comment by rhtpandeyIN** [comment]
Yes due to unstable behavior of node V5.x we removed that support. Thanks for the acknowledgement. Happy to see that it's working for you now.
