### ISSUE TITLE
ibm_db on Azure

### ISSUE THREAD

**Issue by FKADEV** [ibmdb/node-ibm_db#177]
Application has thrown an uncaught exception and is terminated:
Error: %1 is not a valid Win32 application.

\?\D:\home\site\wwwroot\node_modules\ibm_db\build\Release\odbc_bindings.node
    at Error (native)
    at Object.Module._extensions..node (module.js:434:18)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at bindings (D:\home\site\wwwroot\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\ibm_db\lib\odbc.js:27:31)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

**Comment by rhtpandeyIN** [comment]
Hi @FKADEV ,

By looking the information you have provided I can only guess why this is happening ( as it is not clear here), I think this is because of compatibility issue of native modules on Azure. 
Please refer the below link and try as recommended (well this may or may not be the solution, If you have some other information about this issue please share with us.) 

https://azure.microsoft.com/en-us/documentation/articles/nodejs-use-node-modules-azure-apps/
