### ISSUE TITLE
test-querySync-select-with-execption.js failing on windows

### ISSUE THREAD

**Issue by GeorgeAdams95** [ibmdb/node-ibm_db#181]
seeing the following error:

```
# Running test for [[01;29mDB2[01;0m] : test-querySync-select-with-execption ... [01;31mfail [01;0m 
# [01;34mStdout: [01;0m 
# { Error: [IBM][CLI Driver][DB2/AIX64] SQL0104N  An unexpected token "END-OF-STATEMENT" was found following "select invalid query".  Expected tokens may include:  "<table_expr>".  SQLSTATE=42601
# at Error (native)
# at Database.querySync (C:\Users\jenkins\AppData\Local\Temp\8f15fbd6-dfe2-4d9e-99e3-2a5fbd6dc2b4\ibm_db\lib\odbc.js:532:24)
# at Object.<anonymous> (C:\Users\jenkins\AppData\Local\Temp\8f15fbd6-dfe2-4d9e-99e3-2a5fbd6dc2b4\ibm_db\test\test-querySync-select-with-execption.js:12:17)
# at Module._compile (module.js:570:32)
# at Object.Module._extensions..js (module.js:579:10)
# at Module.load (module.js:487:32)
# at tryModuleLoad (module.js:446:12)
# at Function.Module._load (module.js:438:3)
# at Module.runMain (module.js:604:10)
# at run (bootstrap_node.js:394:7)
# errors: [],
# error: '[node-odbc] Error in ODBCConnection::QuerySync',
# message: '[IBM][CLI Driver][DB2/AIX64] SQL0104N  An unexpected token "END-OF-STATEMENT" was found following "select invalid query".  Expected tokens may include:  "<table_expr>".  SQLSTATE=42601\r\n',
# state: '42601' }
# [01;31mStderr: [01;0m 
# assert.js:85
# throw new assert.AssertionError({
# ^
# AssertionError: '[node-odbc] Error in ODBCConnection::QuerySync' == '[node-odbc] Error in ODBCConnection::QuerySync while executing query.'
# at Object.<anonymous> (C:\Users\jenkins\AppData\Local\Temp\8f15fbd6-dfe2-4d9e-99e3-2a5fbd6dc2b4\ibm_db\test\test-querySync-select-with-execption.js:22:10)
# at Module._compile (module.js:570:32)
# at Object.Module._extensions..js (module.js:579:10)
# at Module.load (module.js:487:32)
# at tryModuleLoad (module.js:446:12)
# at Function.Module._load (module.js:438:3)
# at Module.runMain (module.js:604:10)
# at run (bootstrap_node.js:394:7)
# at startup (bootstrap_node.js:149:9)
# at bootstrap_node.js:509:3
```

**Comment by GeorgeAdams95** [comment]
fix here: https://github.com/ibmdb/node-ibm_db/pull/182

**Comment by Akpotohwo** [comment]
I have just tried it locally with the fix and it works for me

**Comment by bimalkjha** [comment]
merged the pull request. Thanks.
