### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by Danwakeem** [ibmdb/node-ibm_db#200]
I am trying to install this package via npm

``> npm i ibm_db``

But it fails with the following error.
 ```
{ [Error: Command failed: /bin/sh -c node-gyp configure build --IBM_DB_HOME=$IBM_DB_HOME --IS_DOWNLOADED=true
make: *** No rule to make target `Tests/butt/node_modules/ibm_db/installer/clidriver'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IBM_DB_HOME=/Users/danjarvis/Documents/App" "Tests/butt/node_modules/ibm_db/installer/clidriver" "--IS_DOWNLOADED=true"
gyp ERR! cwd /Users/danjarvis/Documents/App Tests/butt/node_modules/ibm_db
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c node-gyp configure build --IBM_DB_HOME=$IBM_DB_HOME --IS_DOWNLOADED=true' }
```

I believe I meet all of the prerequisites. 
I am on MacOS Sirra 10.12.1

**Comment by bimalkjha** [comment]
@Danwakeem Please share the complete output of `npm i ibm_db` command. I have verified on MacOS Sirra 10.12.1 and it is working fine for me. Please see the below output:
```
/Users/bimaljha/nodework/installs> npm i ibm_db
|
> ibm_db@1.0.1 install /Users/bimaljha/nodework/installs/node_modules/ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli//macos64_odbc_cli.tar.gz...
Download and extraction of DB2 ODBC CLI Driver completed successfully ...

****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in /Users/bimaljha/nodework/installs/node_modules/ibm_db/installer   Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
****************************************

  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_connection.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_statement.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_result.o
  CXX(target) Release/obj.target/odbc_bindings/src/dynodbc.o
  SOLINK_MODULE(target) Release/odbc_bindings.node

ibm_db@1.0.1 node_modules/ibm_db
├── bindings@1.2.1
├── q@1.4.1
├── nan@2.3.5
├── targz@1.0.1 (tar-fs@1.14.0)
├── fstream@1.0.10 (inherits@2.0.3, graceful-fs@4.1.11, mkdirp@0.5.1, rimraf@2.5.4)
└── unzip@0.1.11 (setimmediate@1.0.5, pullstream@0.4.1, readable-stream@1.0.34, match-stream@0.0.2, fstream@0.1.31, binary@0.3.0)
/Users/bimaljha/nodework/installs> ls node_modules/
ibm_db
/Users/bimaljha/nodework/installs> 
```
Thanks.

**Comment by Danwakeem** [comment]
Oh okay, I identified the error. 

In my npm install path there was a space in one of the parent directories. When I installed this into a path with no spaces in any directory it worked fine. 

This line here
`make: *** No rule to make target `Tests/Rug/node_modules/ibm_db/installer/clidriver'.  Stop.`

Should have been this path
`/Users/danjarvis/Documents/App\ Tests/Rug/node_modules/ibm_db/installer/clidriver`


Here is the error full error log when there is a space in a directory in your path. 
```
> npm i ibm_db
> ibm_db@1.0.1 install /Users/danjarvis/Documents/App Tests/Rug/node_modules/ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli//macos64_odbc_cli.tar.gz...
Download and extraction of DB2 ODBC CLI Driver completed successfully ...

****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in /Users/danjarvis/Documents/App Tests/Rug/node_modules/ibm_db/installer   Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
****************************************


{ [Error: Command failed: /bin/sh -c node-gyp configure build --IBM_DB_HOME=$IBM_DB_HOME --IS_DOWNLOADED=true
make: *** No rule to make target `Tests/Rug/node_modules/ibm_db/installer/clidriver'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IBM_DB_HOME=/Users/danjarvis/Documents/App" "Tests/Rug/node_modules/ibm_db/installer/clidriver" "--IS_DOWNLOADED=true"
gyp ERR! cwd /Users/danjarvis/Documents/App Tests/Rug/node_modules/ibm_db
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c node-gyp configure build --IBM_DB_HOME=$IBM_DB_HOME --IS_DOWNLOADED=true' }

npm WARN enoent ENOENT: no such file or directory, open '/Users/danjarvis/Documents/App Tests/Rug/package.json'
npm WARN Rug No description
npm WARN Rug No repository field.
npm WARN Rug No README data
npm WARN Rug No license field.
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "ibm_db"
npm ERR! node v4.5.0
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@1.0.1 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@1.0.1 install script 'node installer/driverInstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ibm_db
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/danjarvis/Documents/App Tests/Rug/npm-debug.log
```

**Comment by Danwakeem** [comment]
I added a pull request #201  that I think would fix this issue.
