### ISSUE TITLE
queryStream throw error/crush when select columns contains about 200 columns. 

### ISSUE THREAD

**Issue by kathywang** [ibmdb/node-ibm_db#250]
Got below errors when using queryStream and select statement columns contains about 200 columns, fewer columns like 8 columns same where clause running fine. 
at Readable.push (_stream_readable.js:134:10)Apr 10, 2017 6:15:21 PM
APP/0 at readableAddChunk (_stream_readable.js:164:31)Apr 10, 2017 6:15:21 PM
APP/0 ^Apr 10, 2017 6:15:21 PM
APP/0 at StringDecoder.utf8Text [as text] (string_decoder.js:183:7)Apr 10, 2017 6:15:21 PM
APP/0 at /home/vcap/app/node_modules/ibm_db/lib/odbc.js:709:16Apr 10, 2017 6:15:21 PM
APP/0TypeError: buf.copy is not a functionApr 10, 2017 6:15:21 PM
APP/0 buf.copy(this.lastChar, 0, end);Apr 10, 2017 6:15:21 PM
APP/0 at StringDecoder.write (string_decoder.js:64:46)Apr 10, 2017 6:15:21 PM

**Comment by kathywang** [comment]
After above error occurred, the app crushed, please emit stream on error event whenever error happens during streaming, that can help catch errors instead of app crush.

**Comment by kathywang** [comment]
string_decoder.js:183
  buf.copy(this.lastChar, 0, end);
      ^

TypeError: buf.copy is not a function
    at StringDecoder.utf8Text [as text] (string_decoder.js:183:7)
    at StringDecoder.write (string_decoder.js:64:46)
    at readableAddChunk (_stream_readable.js:164:31)
    at Readable.push (_stream_readable.js:134:10)
    at /Users/kwang/Documents/RESTWork/core0411/node_modules/ibm_db/lib/odbc.js:707:14

**Comment by rhtpandeyIN** [comment]
We are looking into this issue, thanks for reporting.

**Comment by rhtpandeyIN** [comment]
Hi @kathywang , I think it is more of application error rather than ibm_db error,
because I tried to run queries with 306 columns and 1000 rows and I am able to get all the data without any error.
following is my test case, please have a look.

```
var ibmdb = require("ibm_db")
var Pool = require('ibm_db').Pool;
var pool = new Pool();
var assert = require("assert");

var cn = "DATABASE=nodedb;HOSTNAME=localhost;PORT=50000;PROTOCOL=TCPIP;UID=rohit;PWD=D#st1nat1on8";

var tableName = "issue250";

var createQuery = "create table " + tableName + " (name1 char(20), name2 char(20), name3 char(20), name4 char(20), name5 char(20), name6 char(20), name7 char(20), name8 char(20), name9 char(20), name10 char(20), name11 char(20), name12 char(20), name13 char(20), name14 char(20), name15 char(20), name16 char(20), name17 char(20), name18 char(20), name19 char(20), name20 char(20), name21 char(20), name22 char(20), name23 char(20), name24 char(20), name25 char(20), name26 char(20), name27 char(20), name28 char(20), name29 char(20), name30 char(20), name31 char(20), name32 char(20), name33 char(20), name34 char(20), name35 char(20), name36 char(20), name37 char(20), name38 char(20), name39 char(20), name40 char(20), name41 char(20), name42 char(20), name43 char(20), name44 char(20), name45 char(20), name46 char(20), name47 char(20), name48 char(20), name49 char(20), name50 char(20), name51 char(20), name52 char(20), name53 char(20), name54 char(20), name55 char(20), name56 char(20), name57 char(20), name58 char(20), name59 char(20), name60 char(20), name61 char(20), name62 char(20), name63 char(20), name64 char(20), name65 char(20), name66 char(20), name67 char(20), name68 char(20), name69 char(20), name70 char(20), name71 char(20), name72 char(20), name73 char(20), name74 char(20), name75 char(20), name76 char(20), name77 char(20), name78 char(20), name79 char(20), name80 char(20), name81 char(20), name82 char(20), name83 char(20), name84 char(20), name85 char(20), name86 char(20), name87 char(20), name88 char(20), name89 char(20), name90 char(20), name91 char(20), name92 char(20), name93 char(20), name94 char(20), name95 char(20), name96 char(20), name97 char(20), name98 char(20), name99 char(20), name100 char(20), name101 char(20), name102 char(20), name103 char(20), name104 char(20),  name105 char(20), name106 char(20), name107 char(20), name108 char(20), name109 char(20), name110 char(20), name111 char(20), name112 char(20), name113 char(20), name114 char(20), name115 char(20), name116 char(20), name117 char(20), name118 char(20), name119 char(20), name120 char(20), name121 char(20), name122 char(20), name123 char(20), name124 char(20), name125 char(20), name126 char(20), name127 char(20), name128 char(20), name129 char(20), name130 char(20), name131 char(20), name132 char(20), name133 char(20), name134 char(20), name135 char(20), name136 char(20), name137 char(20), name138 char(20), name139 char(20), name140 char(20), name141 char(20), name142 char(20), name143 char(20), name144 char(20), name145 char(20), name146 char(20), name147 char(20), name148 char(20), name149 char(20), name150 char(20), name151 char(20), name152 char(20), name153 char(20), name154 char(20), name155 char(20), name156 char(20), name157 char(20), name158 char(20), name159 char(20), name160 char(20), name161 char(20), name162 char(20), name163 char(20), name164 char(20), name165 char(20), name166 char(20), name167 char(20), name168 char(20), name169 char(20), name170 char(20), name171 char(20), name172 char(20), name173 char(20), name174 char(20), name175 char(20), name176 char(20), name177 char(20), name178 char(20), name179 char(20), name180 char(20), name181 char(20), name182 char(20), name183 char(20), name184 char(20), name185 char(20), name186 char(20), name187 char(20), name188 char(20), name189 char(20), name190 char(20), name191 char(20), name192 char(20), name193 char(20), name194 char(20), name195 char(20), name196 char(20), name197 char(20), name198 char(20), name199 char(20), name200 char(20), name201 char(20), name202 char(20), name203 char(20), name204 char(20),  name205 char(20), name206 char(20), name207 char(20), name208 char(20), name209 char(20), name210 char(20), name211 char(20), name212 char(20), name213 char(20), name214 char(20), name215 char(20), name216 char(20), name217 char(20), name218 char(20), name219 char(20), name220 char(20), name221 char(20), name222 char(20), name223 char(20), name224 char(20), name225 char(20), name226 char(20), name227 char(20), name228 char(20), name229 char(20), name230 char(20), name231 char(20), name232 char(20), name233 char(20), name234 char(20), name235 char(20), name236 char(20), name237 char(20), name238 char(20), name239 char(20), name240 char(20), name241 char(20), name242 char(20), name243 char(20), name244 char(20), name245 char(20), name246 char(20), name247 char(20), name248 char(20), name249 char(20), name250 char(20), name251 char(20), name252 char(20), name253 char(20), name254 char(20), name255 char(20), name256 char(20), name257 char(20), name258 char(20), name259 char(20), name260 char(20), name261 char(20), name262 char(20), name263 char(20), name264 char(20), name265 char(20), name266 char(20), name267 char(20), name268 char(20), name269 char(20), name270 char(20), name271 char(20), name272 char(20), name273 char(20), name274 char(20), name275 char(20), name276 char(20), name277 char(20), name278 char(20), name279 char(20), name280 char(20), name281 char(20), name282 char(20), name283 char(20), name284 char(20), name285 char(20), name286 char(20), name287 char(20), name288 char(20), name289 char(20), name290 char(20), name291 char(20), name292 char(20), name293 char(20), name294 char(20), name295 char(20), name296 char(20), name297 char(20), name298 char(20), name299 char(20), name300 char(20), name301 char(20), name302 char(20), name303 char(20), name304 char(20), name305 char(20), age int)";

var insertQuery = "insert into " + tableName + " values('name1' , 'name2' , 'name3' , 'name4' , 'name5' , 'name6' , 'name7' , 'name8' , 'name9' , 'name10' , 'name11' , 'name12', 'name13', 'name14', 'name15', 'name16', 'name17', 'name18', 'name19', 'name20', 'name21', 'name22', 'name23', 'name24', 'name25', 'name26', 'name27', 'name28', 'name29', 'name30', 'name31', 'name32', 'name33', 'name34', 'name35', 'name36', 'name37', 'name38', 'name39', 'name40', 'name41', 'name42', 'name43', 'name44', 'name45', 'name46', 'name47', 'name48', 'name49', 'name50', 'name51', 'name52', 'name53', 'name54', 'name55', 'name56', 'name57', 'name58', 'name59', 'name60', 'name61', 'name62', 'name63', 'name64', 'name65', 'name66', 'name67', 'name68 ', 'name69', 'name70', 'name71', 'name72', 'name73', 'name74', 'name75', 'name76', 'name77', 'name78', 'name79', 'name80', 'name81', 'name82', 'name83', 'name84', 'name85 ', 'name86 ', 'name87', 'name88', 'name89', 'name90', 'name91', 'name92', 'name93', 'name94', 'name95', 'name96', 'name97', 'name98', 'name99', 'name100', 'name101', 'name102', 'name103', 'name104', ' name105', 'name106', 'name107', 'name108', 'name109', 'name110', 'name111', 'name112', 'name113', 'name114', 'name115', 'name116', 'name117', 'name118 ', 'name119', 'name120', 'name121', 'name122', 'name123', 'name124', 'name125', 'name126', 'name127', 'name128', 'name129', 'name130', 'name131', 'name132', 'name133', 'name134', 'name135 ', 'name136', 'name137', 'name138', 'name139', 'name140', 'name141', 'name142', 'name143', 'name144', 'name145', 'name146', 'name147', 'name148', 'name149', 'name150', 'name151', 'name152', 'name153', 'name154', 'name155', 'name156', 'name157', 'name158', 'name159', 'name160', 'name161', 'name162', 'name163', 'name164', 'name165', 'name166', 'name167', 'name168', 'name169', 'name170', 'name171', 'name172', 'name173', 'name174', 'name175', 'name176', 'name177', 'name178', 'name179', 'name180', 'name181', 'name182', 'name183', 'name184', 'name185', 'name186', 'name187', 'name188', 'name189', 'name190', 'name191', 'name192', 'name193', 'name194', 'name195', 'name196', 'name197', 'name198', 'name199', 'name200', 'name201', 'name202', 'name203', 'name204', ' name205', 'name206', 'name207', 'name208', 'name209', 'name210', 'name211', 'name212', 'name213', 'name214', 'name215', 'name216', 'name217', 'name218', 'name219', 'name220', 'name221', 'name222', 'name223', 'name224', 'name225', 'name226', 'name227', 'name228', 'name229', 'name230', 'name231', 'name232', 'name233', 'name234', 'name235', 'name236', 'name237', 'name238', 'name239', 'name240', 'name241', 'name242', 'name243', 'name244', 'name245', 'name246', 'name247', 'name248', 'name249', 'name250', 'name251', 'name252', 'name253', 'name254', 'name255', 'name256', 'name257', 'name258', 'name259', 'name260', 'name261', 'name262', 'name263', 'name264', 'name265', 'name266', 'name267', 'name268', 'name269', 'name270', 'name271', 'name272', 'name273', 'name274', 'name275', 'name276', 'name277', 'name278', 'name279', 'name280', 'name281', 'name282', 'name283', 'name284', 'name285', 'name286', 'name287', 'name288', 'name289', 'name290', 'name291', 'name292', 'name293', 'name294', 'name295', 'name296', 'name297', 'name298', 'name299', 'name300' , 'name301' , 'name302' , 'name303' , 'name304' , 'name305' , 50)";

var selectQuery = "select * from " + tableName + " where age = 50";

var dropQuery = "drop table " + tableName + "";

try {
    pool.open(cn, function(err, conn) {
        var createTable = conn.querySync(createQuery);

        if(createTable){
            for(var i=0; i<1000; i++) {
                var insert = conn.querySync(insertQuery);
            }

            var stream = conn.queryStream(selectQuery);
            
            var rowcount = 0;
            var count = 0;
            stream.on('data', function (result) {
                rowcount++;
                if(typeof result == "object"){
                    if(Object.keys) {
                        count = Object.keys(result).length;
                    }
                }
            }).on('error', function (err) {
                conn.closeSync();
                console.log('error occured: '+err);
            }).on('end', function () {
                conn.querySync(dropQuery);
                conn.closeSync();
                assert.equal(306, count);
                assert.equal(1000, rowcount);
            });
        } else {
            console.log("table not created");
        }
    });
}
catch(e) {
    console.log("error occurred: "+ e); 
}
```

**Comment by rhtpandeyIN** [comment]
#241 , could you please run the above test sample for your requirements, I tried to run it against 1 million rows and 365 columns and I am getting all data perfectly.

**Comment by rhtpandeyIN** [comment]
Closing the issue now as solution has been given already, please feel free to reopen it again if you are still encountering the same issue.
