### ISSUE TITLE
Potential problem with node 8.1.1

### ISSUE THREAD

**Issue by huineng** [ibmdb/node-ibm_db#282]
I can build successfully on node 8.1.0  but when trying the install using 8.1.1 i get this error

```
93.78% | 17539072 bytes downloaded out of 18703240 bytes.
       gyp ERR! stack Error: 404 response downloading https://nodejs.org/download//v8.1.1/node-v8.1.1-headers.tar.gz
       gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
       gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:453:20)
       
       { Error: Command failed: node-gyp configure build --IBM_DB_HOME="$IBM_DB_HOME" --IS_DOWNLOADED=true
       gyp ERR! configure error
       gyp ERR! stack     at Request.<anonymous> (/tmp/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:210:14)
       gyp ERR! stack     at emitOne (events.js:120:20)
       gyp ERR! stack     at Request.emit (events.js:210:7)
       gyp ERR! stack     at Request.onRequestResponse (/tmp/app/vendor/node/lib/node_modules/npm/node_modules/request/request.js:1074:10)
       gyp ERR! stack     at emitOne (events.js:115:13)
       gyp ERR! stack     at ClientRequest.emit (events.js:210:7)
       gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:564:21)
       gyp ERR! stack     at emitOne (events.js:115:13)
       gyp ERR! System Linux 4.4.0-45-generic
       gyp ERR! command "/tmp/app/vendor/node/bin/node" "/tmp/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IBM_DB_HOME=/tmp/app/node_modules/ibm_db/installer/clidriver" "--IS_DOWNLOADED=true"
       gyp ERR! cwd /tmp/app/node_modules/ibm_db
       gyp ERR! node -v v8.1.1
       gyp ERR! node-gyp -v v3.6.2
       gyp ERR! not ok
```

**Comment by bnoordhuis** [comment]
See https://github.com/nodejs/node/issues/13667, it's an issue with the 8.1.1 release.

Workaround: `npm install --dist-url https://nodejs.org/download/release`
