### ISSUE TITLE
AIX - Could not allocate enough memory for params in ODBC::GetParametersFromArray.

### ISSUE THREAD

**Issue by agov** [ibmdb/node-ibm_db#296]
node -v
v8.1.2

npm -v
5.3.0

oslevel -s
7100-03-09-1717

`Error: Could not allocate enough memory for params in ODBC::GetParametersFromArray.
    at /home/myapp/code/myapp/node_modules/ibm_db/lib/odbc.js:437:21
    at SimpleQueue.next (/home/myapp/code/myapp/node_modules/ibm_db/lib/simple-queue.js:34:5)
    at SimpleQueue.maybeNext (/home/myapp/code/myapp/node_modules/ibm_db/lib/simple-queue.js:22:10)
    at SimpleQueue.push (/home/myapp/code/myapp/node_modules/ibm_db/lib/simple-queue.js:15:8)
    at Database.query (/home/myapp/code/myapp/node_modules/ibm_db/lib/odbc.js:327:14)
    at pool.open (/home/myapp/code/myapp/engine/db2.js:18:14)
    at Pool.open (/home/myapp/code/myapp/node_modules/ibm_db/lib/odbc.js:1478:17)
    at Object.module.exports.poolQuery (/home/myapp/code/myapp/engine/db2.js:10:10)
    at router.get (/home/myapp/code/myapp/routes/api/host.js:26:12)
    at Layer.handle [as handle_request] (/home/myapp/code/myapp/node_modules/express/lib/router/layer.js:95:5)
/home/myapp/code/myapp/node_modules/ibm_db/lib/odbc.js:437
          self.conn.query(query, params, cbQuery);
`

**Comment by agov** [comment]
FYI it works with 1.0.1

ulimit -a
time(seconds)        unlimited
file(blocks)         unlimited
data(kbytes)         unlimited
stack(kbytes)        unlimited
memory(kbytes)       unlimited
coredump(blocks)     unlimited
nofiles(descriptors) unlimited
threads(per process) unlimited
processes(per user)  unlimited

current memory usage is around ~90%

**Comment by rhtpandeyIN** [comment]
Hi, Thanks for the detailed information.
Also, can you please share a sample repro for that? So that I can also test the exact scenario.

**Comment by agov** [comment]
Hello @rhtpandeyIN 
It affects Pool, could not reproduce with regular connections.

```
/home/myapp/code/myapp $ node
> 'use strict'
'use strict'
> let ibmdb = require('ibm_db')
undefined
> let Pool = ibmdb.Pool
undefined
> let pool = new Pool({autoCleanIdle: true, idleTimeout: 10 * 1000})
undefined
> let cn = process.env.CN
undefined
> ibmdb.debug(false)
node-ibm_db logs disabled.
undefined
> pool.open(cn, (err, conn)=> {
...         if (err) {
.....             return console.log(err)
.....         }
...         conn.query('select * from sysibm.sysdummy1', [], (err, res)=> {
.....           console.log(err, res)
.....       })
... })
undefined
> /home/myapp/code/myapp/node_modules/ibm_db/lib/odbc.js:435
          self.conn.query(query, params, cbQuery);
                    ^

Error: Could not allocate enough memory for params in ODBC::GetParametersFromArray.
    at /home/myapp/code/myapp/node_modules/ibm_db/lib/odbc.js:435:21
    at SimpleQueue.next (/home/myapp/code/myapp/node_modules/ibm_db/lib/simple-queue.js:34:5)
    at SimpleQueue.maybeNext (/home/myapp/code/myapp/node_modules/ibm_db/lib/simple-queue.js:22:10)
    at SimpleQueue.push (/home/myapp/code/myapp/node_modules/ibm_db/lib/simple-queue.js:15:8)
    at Database.query (/home/myapp/code/myapp/node_modules/ibm_db/lib/odbc.js:326:14)
    at pool.open (repl:5:14)
    at /home/myapp/code/myapp/node_modules/ibm_db/lib/odbc.js:1521:7
    at /home/myapp/code/myapp/node_modules/ibm_db/lib/odbc.js:208:16

```

**Comment by bimalkjha** [comment]
@agov Please check with ibm_db@2.2.1. Thanks.

**Comment by agov** [comment]
@bimalkjha Same error, the trace changed slightly.

```
Error: Could not allocate enough memory for params in ODBC::GetParametersFromArray.
    at /home/myapp/code/myapp/node_modules/ibm_db/lib/odbc.js:440:21
    at SimpleQueue.next (/home/myapp/code/myapp/node_modules/ibm_db/lib/simple-queue.js:34:5)
    at SimpleQueue.maybeNext (/home/myapp/code/myapp/node_modules/ibm_db/lib/simple-queue.js:22:10)
    at SimpleQueue.push (/home/myapp/code/myapp/node_modules/ibm_db/lib/simple-queue.js:15:8)
    at Database.query (/home/myapp/code/myapp/node_modules/ibm_db/lib/odbc.js:330:14)
    at pool.open (/home/myapp/code/myapp/engine/db2.js:18:14)
    at Pool.open (/home/myapp/code/myapp/node_modules/ibm_db/lib/odbc.js:1483:17)
    at Object.module.exports.poolQuery (/home/myapp/code/myapp/engine/db2.js:10:10)
    at router.get (/home/myapp/code/myapp/routes/api/host.js:26:12)
    at Layer.handle [as handle_request] 
```

**Comment by rhtpandeyIN** [comment]
Hi @agov ,
Issue has been fixed with latest code changes, closing the issue for now. If you have further queries or issues, feel free to comment here or reopen the issue.
