### ISSUE TITLE
fails to work with electron-mocha

### ISSUE THREAD

**Issue by AhmedAKhan** [ibmdb/node-ibm_db#302]
I have created a file called temp.js and it has the following code in it 

```
var ibmdb = require('ibm_db')
```

When I run the file normally it with electron-mocha it gives me this error
```
AzureAD+RICHMONDTruong@DESKTOP-SNLG1UB MINGW64 ~/db2-desktop (testers)
$ ./node_modules/.bin/electron-mocha temp.js

A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\RICHMONDTruong\db2-desktop\node_modules\ibm_db\build\Release\odbc_bindings.node
Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\RICHMONDTruong\db2-desktop\node_modules\ibm_db\build\Release\odbc_bindings.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at bindings (C:\Users\RICHMONDTruong\db2-desktop\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\Users\RICHMONDTruong\db2-desktop\node_modules\ibm_db\lib\odbc.js:27:31)
    at Module._compile (module.js:556:32)
    at Module._extensions..js (module.js:565:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\RICHMONDTruong\db2-desktop\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:/Users/RICHMONDTruong/db2-desktop/temp.js:2:1)
    at Module._compile (module.js:556:32)
    at loader (C:\Users\RICHMONDTruong\db2-desktop\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\RICHMONDTruong\db2-desktop\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at C:\Users\RICHMONDTruong\db2-desktop\node_modules\mocha\lib\mocha.js:230:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Users\RICHMONDTruong\db2-desktop\node_modules\mocha\lib\mocha.js:227:14)
    at Mocha.run (C:\Users\RICHMONDTruong\db2-desktop\node_modules\mocha\lib\mocha.js:495:10)
    at Object.run (C:\Users\RICHMONDTruong\db2-desktop\node_modules\electron-mocha\mocha.js:61:30)
    at App.app.on.error (C:\Users\RICHMONDTruong\db2-desktop\node_modules\electron-mocha\index.js:44:13)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
./node_modules/.bin/electron-mocha: line 14:  4632 Segmentation fault      node "$basedir/../electron-mocha/bin/electron-mocha" "$@"
```

This is on windows 10, 64 bit
node 6.11.0

**Comment by rhtpandeyIN** [comment]
Are you able to run it normally without using electron-mocha ?

**Comment by AhmedAKhan** [comment]
yes it ran properly with normal mocha

**Comment by bimalkjha** [comment]
@AhmedAKhan use ibm_db@2.2.0 and verify. Thanks.

**Comment by bimalkjha** [comment]
Closing the issue as it should work now using ibm_db@2.2.0. If not, please let me know. thanks.
