### ISSUE TITLE
ibm_db@2.2.0 fails after rebuild

### ISSUE THREAD

**Issue by n-riesco** [ibmdb/node-ibm_db#313]
Steps to reproduce using `yarn`:

1. Init a package and add `ibm_db` as a dependency
```sh
user@host:~/tmp$ mkdir test-ibmdb
user@host:~/tmp$ cd test-ibmdb/
user@host:~/tmp/test-ibmdb$ yarn init
yarn init v0.27.5
question name (test-ibmdb): 
question version (1.0.0): 
question description: 
question entry point (index.js): 
question repository url: 
question author: 
question license (MIT): 
success Saved package.json
Done in 11.81s.
user@host:~/tmp/test-ibmdb$ yarn add ibm_db
yarn add v0.27.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 96 new dependencies.
[...]
Done in 55.34s.
```
2. Test `ibm_db` can be required:
```sh
user@host:~/tmp/test-ibmdb$ node -e "require('ibm_db')"
```
3. Force a rebuild
```sh
user@host:~/tmp/test-ibmdb$ yarn install --force
yarn install v0.27.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
success Saved lockfile.
Done in 1.73s.
```

4. `ibm_db` cannot be required after rebuild
```sh
user@host:~/tmp/test-ibmdb$ node -e "require('ibm_db')"
/home/user/tmp/test-ibmdb/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: libdb2.so.1: cannot open shared object file: No such file or directory
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (/home/user/tmp/test-ibmdb/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/user/tmp/test-ibmdb/node_modules/ibm_db/lib/odbc.js:27:31)
    at Module._compile (module.js:570:32)
```

**Comment by n-riesco** [comment]
Here's a workaround that works for me:

https://github.com/n-riesco/node-ibm_db/commit/201ef8967906aade8c191f852ee0c7c804b51d9c

**Comment by n-riesco** [comment]
Perhaps relevant: https://github.com/ibmdb/node-ibm_db/commit/0780914b69845f621cbbfaee70b580afd42a5bea

**Comment by bimalkjha** [comment]
@n-riesco Please let us know the platform on which you are facing this issue.
Please share any simple steps to reproduce it without yarn. Or the issue is only reproducible using yarn?
After force rebuild, do you see file `/home/user/tmp/test-ibmdb/node_modules/ibm_db/installer/clidriver/lib/libdb2.so.1` is present or not?
If file `libdb2.so.1` is present, can you run below commands and verify?
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/user/tmp/test-ibmdb/node_modules/ibm_db/installer/clidriver/lib
export PATH=$PATH:/home/user/tmp/test-ibmdb/node_modules/ibm_db/installer/clidriver/lib:/home/user/tmp/test-ibmdb/node_modules/ibm_db/installer/clidriver/bin
node -e "require('ibm_db')"
```
Thanks.

**Comment by n-riesco** [comment]
The issue is caused by `installer/driverInstall.js`, because on a rebuild it doesn't set the flag `--IS_DOWNLOADED=true`, and this make `binding.gyp` exclude the flag `{ 'ldflags' : [ "-Wl,-R,'<(ORIGIN_LIB_PATH)' " ] }`.

My platform is Ubuntu 16.04 LTS.

**Comment by n-riesco** [comment]
Here are the steps to reproduce the issue using `npm`:

```sh
user@host:~/tmp/test-ibmdb$ npm install
[...]

user@host:~/tmp/test-ibmdb$ node -e "require('ibm_db')"

user@host:~/tmp/test-ibmdb$ npm rebuild
[...]

user@host:~/tmp/test-ibmdb$ node -e "require('ibm_db')"
/home/user/tmp/test-ibmdb/node_modules/bindings/bindings.js:83
        throw e
        ^

Error: libdb2.so.1: cannot open shared object file: No such file or directory
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (/home/user/tmp/test-ibmdb/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/user/tmp/test-ibmdb/node_modules/ibm_db/lib/odbc.js:27:31)
    at Module._compile (module.js:570:32)
```

**Comment by n-riesco** [comment]
And this is the result of running the commands you suggested:
```sh
user@host:~/tmp/test-ibmdb$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/user/tmp/test-ibmdb/node_modules/ibm_db/installer/clidriver/lib

user@host:~/tmp/test-ibmdb$ export PATH=$PATH:/home/user/tmp/test-ibmdb/node_modules/ibm_db/installer/clidriver/lib:/home/user/tmp/test-ibmdb/node_modules/ibm_db/installer/clidriver/bin

user@host:~/tmp/test-ibmdb$ node -e "require('ibm_db')"

user@host:~/tmp/test-ibmdb$
```

**Comment by rhtpandeyIN** [comment]
@n-riesco , now try to rebuild it again. let us know what happened.

**Comment by n-riesco** [comment]
Note that `LD_LIBRARY_PATH` is still set to `` and thus `node -e "require('ibm_db')"` works despite the rebuild:

```sh
user@host:~/tmp/test-ibmdb$ echo $LD_LIBRARY_PATH
:/home/user/tmp/test-ibmdb/node_modules/ibm_db/installer/clidriver/lib

user@host:~/tmp/test-ibmdb$ npm rebuild
[...]

user@host:~/tmp/test-ibmdb$ node -e "require('ibm_db')"

user@host:~/tmp/test-ibmdb$ echo $LD_LIBRARY_PATH
:/home/user/tmp/test-ibmdb/node_modules/ibm_db/installer/clidriver/lib

user@host:~/tmp/test-ibmdb$ 
```

**Comment by bimalkjha** [comment]
@n-riesco I am unable to reproduce the issue on Mac and Linux. Please share the complete output of `npm rebuild` command to look deeper into the issue: 

```
$ npm install git+https://git@github.com/ibmdb/node-ibm_db.git
$ node -e "require('ibm_db')"
$ npm rebuild
$ node -e "require('ibm_db')"
$ node -v
```
Please run above commands in a new directory and share the output starting from rebuild command output as below:
```
hotellnx113: /home/bimaljha/installs> npm rebuild

> ibm_db@2.2.0 install /home/hotellnx113/bimaljha/installs/node_modules/ibm_db
> node installer/driverInstall.js

Rebuild Process: Found clidriver at -> /home/hotellnx113/bimaljha/installs/node_modules/ibm_db/installer/clidriver

Downloading of clidriver skipped - build is in progress...

make: Entering directory `/home/hotellnx113/bimaljha/installs/node_modules/ibm_db/build'
  SOLINK_MODULE(target) Release/obj.target/odbc_bindings.node
  COPY Release/odbc_bindings.node
make: Leaving directory `/home/hotellnx113/bimaljha/installs/node_modules/ibm_db/build'

ibm_db@2.2.0 /home/hotellnx113/bimaljha/installs/node_modules/ibm_db
bindings@1.2.1 /home/hotellnx113/bimaljha/installs/node_modules/ibm_db/node_modules/bindings
.....
hotellnx113: /home/bimaljha/installs> node -e "require('ibm_db')"
hotellnx113: /home/bimaljha/installs> node -v
v0.12.12
hotellnx113: /home/bimaljha/installs> 
```
Thanks.

**Comment by bimalkjha** [comment]
Able to reproduce the issue on linux after removing env variable LD_LIBRARY_PATH. But on Mac it works fine without setting DYLD_LIBRARY_PATH too. Looking further into it. Thanks.

**Comment by n-riesco** [comment]
I reckon it works for you, because in your machine libdb2.so is in your
LD_LIBRARY_PATH.

Tonight (or most likely tomorrow), I'll prepare a Dockerfile to reproduce
the issue.

**Comment by n-riesco** [comment]
@bimalkjha OK, so no need for me to reproduce the issue with a Dockerfile.

BTW, have you had a chance to have a look at the fix [here](https://github.com/n-riesco/node-ibm_db/commit/201ef8967906aade8c191f852ee0c7c804b51d9c)? Would this fix have any undesired side-effects?

**Comment by aslansservant42** [comment]
I ran across this while trying to create a Docker image for a node.js/express service that uses ibm_db. There are several issues that you will encounter. The trick is to set the IBM_DB_HOME and LD_LIBRARY_PATH environment variables correctly to point to places within the cli driver that you need to download. If you are behind a corporate firewall, you will also need to use NODE_TLS_REJECT_UNAUTHORIZED=0 so turn off the ssl certificate checking. This is only for the build so I don't consider it a security flaw. Anyway, here is the complete and working Dockerfile.

```
FROM node:10

# Create app directory
WORKDIR .

# need to download the ibm drivers and set IBM_DB_HOME
ENV NODE_TLS_REJECT_UNAUTHORIZED=0
RUN mkdir /ibmdriver
RUN curl https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz \
  | tar -xzf - -C /ibmdriver/
ENV IBM_DB_HOME /ibmdriver/clidriver
ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:$IBM_DB_HOME/lib



# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available ([email protected]+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm install --only=production

# Bundle app source
COPY . .

ENV BCCB_DECISIONTREE_SERVICE_PORT 3000

EXPOSE 3000
CMD [ "npm", "start" ]

```
