### ISSUE TITLE
test-call-stmt is failing on WIndows

### ISSUE THREAD

**Issue by al-k21** [ibmdb/node-ibm_db#334]
Seeing this on WIndows:
```node
Running test 13 for [DB2] : test-call-stmt ... fail
 Stdout:

 Stderr:

C:\Users\gb120491\tmp\node-ibm_db\lib\odbc.js:614
    result = self.conn.querySync(query);
                       ^
Error: [IBM][CLI Driver][DB2/AIX64] SQL0551N  The statement failed because the authorization ID does not have the required authorization or privilege to perform the operation.  Authorization ID: "CITGMDB2".  Operation: "REPLACE PROCEDURE". Object: "JTCJS11.PROC1".  LINE NUMBER=1.  SQLSTATE=42501

    at Error (native)
    at Database.querySync (C:\Users\gb120491\tmp\node-ibm_db\lib\odbc.js:614:24)
    at C:\Users\gb120491\tmp\node-ibm_db\test\test-call-stmt.js:19:10
    at C:\Users\gb120491\tmp\node-ibm_db\lib\odbc.js:111:11
    at C:\Users\gb120491\tmp\node-ibm_db\lib\odbc.js:208:11
```
Can you comment @rhtpandeyIN ?

**Comment by rhtpandeyIN** [comment]
For more information and discussion check issue:  #333
