### ISSUE TITLE
libpam error 

### ISSUE THREAD

**Issue by al-k21** [ibmdb/node-ibm_db#335]
I am seeing a libpam error:
```js
verbose: ibm_db npm-test:    | /svt/jenkins/workspace/SVT-V6-IBM-CITGM/ARCH/x86/GCC/gcc48/OS/rhel7/TAG/svt/tmp/c983f712-eb7e-48fb-addd-bacd4cd9e767/ibm_db/node_modules/bindings/bindings.js:83                 
verbose:                     | throw e                                                                                                                                                                          
verbose:                     | ^                                                                                                                                                                                
verbose:                     |                                                                                                                                                                                  
verbose:                     | Error: libpam.so.0: cannot open shared object file: No such file or directory                                                                                                    
verbose:                     | at Error (native)                                                                                                                                                                
verbose:                     | at Object.Module._extensions..node (module.js:597:18)                                                                                                                            
verbose:                     | at Module.load (module.js:487:32)                                                                                                                                                
verbose:                     | at tryModuleLoad (module.js:446:12)                                                                                                                                              
verbose:                     | at Function.Module._load (module.js:438:3)                                                                                                                                       
verbose:                     | at Module.require (module.js:497:17)                                                                                                                                             
verbose:                     | at require (internal/module.js:20:19)                                                                                                                                            
verbose:                     | at bindings (/svt/jenkins/workspace/SVT-V6-IBM-CITGM/ARCH/x86/GCC/gcc48/OS/rhel7/TAG/svt/tmp/c983f712-eb7e-48fb-addd-bacd4cd9e767/ibm_db/node_modules/bindings/bindings.js:76:44)
verbose:                     | at Object.<anonymous> (/svt/jenkins/workspace/SVT-V6-IBM-CITGM/ARCH/x86/GCC/gcc48/OS/rhel7/TAG/svt/tmp/c983f712-eb7e-48fb-addd-bacd4cd9e767/ibm_db/lib/odbc.js:31:31)            
verbose:                     | at Module._compile (module.js:570:32)                                                                                                                                            
verbose: ibm_db npm-test:    | npm                 
verbose: ibm_db npm-test:    | ERR! Test failed.  See above for more details.
```
OS: `rhel-x86`

**Comment by bimalkjha** [comment]
@al-k21 Install this libpam.so library. It is missing from your system. This page has more info that can help you: http://www-01.ibm.com/support/docview.wss?uid=swg21671107 Thanks.
