### ISSUE TITLE
Trying to use AIX driver from a Mac OS

### ISSUE THREAD

**Issue by xumes** [ibmdb/node-ibm_db#347]
Hello,

I am trying to connect to a DB2 installed on an AIX OS, from my Mac, but I am getting this error:

```
Error: dlopen(/Users/myuser/dev/Error: dlopen(/Users/myusername/dev/customer-feedback-power/node_modules/ibm_db/build/Release/odbc_bindings.node, 1): Library not loaded: /Users/myusername/devredbook/Use\ cases/Customer\ Feedback\ Code/customer-feedback-power/node_modules/ibm_db/installer/clidriver/lib/libdb2.dylib
  Referenced from: /Users/myusername/dev/customer-feedback-power/node_modules/ibm_db/build/Release/odbc_bindings.node
  Reason: image not found
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/myusername/dev/customer-feedback-power/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/myusername/dev/customer-feedback-power/node_modules/ibm_db/lib/odbc.js:31:31)
    at Module._compile (module.js:570:32)/redbook/Use cases/customer-feedback-power/node_modules/ibm_db/build/Release/odbc_bindings.node, 1): Library not loaded: /Users/myuser/devredbook/Use\ cases/Customer\ Feedback\ Code/customer-feedback-power/node_modules/ibm_db/installer/clidriver/lib/libdb2.dylib
  Referenced from: /Users/myuser/dev/customer-feedback-power/node_modules/ibm_db/build/Release/odbc_bindings.node
  Reason: image not found
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/myuser/dev/customer-feedback-power/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/Users/myuser/dev/customer-feedback-power/node_modules/ibm_db/lib/odbc.js:31:31)
    at Module._compile (module.js:570:32)
```

Any idea?

**Comment by bimalkjha** [comment]
Please share the complete output of "npm install ibm_db" command from your mac. Thanks.

**Comment by xumes** [comment]
hello team,

I could make it work. Basically, I was working on the customer environment and the path to the project countained spaces like` '/Users/username/Customer Feedback/'`

I moved the project to a better path, installed the ibm_db first and then installed all other dependencies:

```
$ npm install ibm_db
$ npm install
```

It works and is working until now.
Thank you very much for your time and patience. Your support is great!!!
