### ISSUE TITLE
linux x64 fails to compile

### ISSUE THREAD

**Issue by brandonros** [ibmdb/node-ibm_db#352]
```
foo@foo.com > npm install ibm_db

> ibm_db@2.2.1 install /foo/node_modules/ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz...

100.00% | 18703240 bytes downloaded out of 18703240 bytes.

****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in undefined   Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
****************************************

Downloading and extraction of DB2 ODBC CLI Driver completed successfully ...

make: Entering directory `/brandon/fs-loyalty-platform/node_modules/ibm_db/build'
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
make: Leaving directory `/brandon/fs-loyalty-platform/node_modules/ibm_db/build'

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"
In file included from ../src/odbc.h:23,
                 from ../src/odbc.cpp:25:
../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/memory:83,
                 from /home/brandon/.node-gyp/8.9.1/include/node/v8.h:21,
                 from ../src/odbc.cpp:19:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_deleter<_Ptr, _Deleter, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:146: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:204: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In constructor ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, _Alloc, _Args&& ...)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:861: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In function ‘_Del* std::get_deleter(const std::__shared_ptr<_Tp2, _Lp>&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:1005: error: cannot use typeid with -fno-rtti
In file included from ../src/odbc.cpp:19:
/home/brandon/.node-gyp/8.9.1/include/node/v8.h: At global scope:
/home/brandon/.node-gyp/8.9.1/include/node/v8.h:333: error: expected unqualified-id before ‘using’
/home/brandon/.node-gyp/8.9.1/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/home/brandon/.node-gyp/8.9.1/include/node/v8.h:350: error: ‘nullptr’ was not declared in this scope
/home/brandon/.node-gyp/8.9.1/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/home/brandon/.node-gyp/8.9.1/include/node/v8.h:357: error: ‘nullptr’ was not declared in this scope
/home/brandon/.node-gyp/8.9.1/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/home/brandon/.node-gyp/8.9.1/include/node/v8.h:365: error: ‘nullptr’ was not declared in this scope
/home/brandon/.node-gyp/8.9.1/include/node/v8.h: In constructor ‘v8::Eternal<T>::Eternal()’:
/home/brandon/.node-gyp/8.9.1/include/node/v8.h:394: error: ‘nullptr’ was not declared in this scope
/home/brandon/.node-gyp/8.9.1/include/node/v8.h: In constructor ‘v8::Eternal<T>::Eternal(v8::Isolate*, v8::Local<S>)’:
/home/brandon/.node-gyp/8.9.1/include/node/v8.h:396: error: ‘nullptr’ was not declared in this scope
/home/brandon/.node-gyp/8.9.1/include/node/v8.h: In member function ‘bool v8::Eternal<T>::IsEmpty() const’:
/home/brandon/.node-gyp/8.9.1/include/node/v8.h:401: error: ‘nullptr’ was not declared in this scope
/home/brandon/.node-gyp/8.9.1/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/home/brandon/.node-gyp/8.9.1/include/node/v8.h:441: error: ‘nullptr’ was not declared in this scope
/home/brandon/.node-gyp/8.9.1/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/home/brandon/.node-gyp/8.9.1/include/node/v8.h:775: error: ‘nullptr’ was not declared in this scope
/home/brandon/.node-gyp/8.9.1/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/home/brandon/.node-gyp/8.9.1/include/node/v8.h:800: error: ‘nullptr’ was not declared in this scope
/home/brandon/.node-gyp/8.9.1/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/home/brandon/.node-gyp/8.9.1/include/node/v8.h:812: error: ‘nullptr’ was not declared in this scope
/home/brandon/.node-gyp/8.9.1/include/node/v8.h: At global scope:
/home/brandon/.node-gyp/8.9.1/include/node/v8.h:838: error: expected unqualified-id before ‘using’
/home/brandon/.node-gyp/8.9.1/include/node/v8.h:1187: error: ‘nullptr’ was not declared in this scope
/home/brandon/.node-gyp/8.9.1/include/node/v8.h:1193: error: ‘nullptr’ was not declared in this scope
/home/brandon/.node-gyp/8.9.1/include/node/v8.h: In constructor ‘v8::RegisterState::RegisterState()’:
/home/brandon/.node-gyp/8.9.1/include/node/v8.h:1733: error: ‘nullptr’ was not declared in this scope
/home/brandon/.node-gyp/8.9.1/include/node/v8.h: At global scope:
/home/brandon/.node-gyp/8.9.1/include/node/v8.h:3198: error: ‘nullptr’ was not declared in this scope
/home/brandon/.node-gyp/8.9.1/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/home/brandon/.node-gyp/8.9.1/include/node/v8.h:3839: error: ‘nullptr’ was not declared in this scope
/home/brandon/.node-gyp/8.9.1/include/node/v8.h: At global scope:
/home/brandon/.node-gyp/8.9.1/include/node/v8.h:4108: error: function definition does not declare parameters
/home/brandon/.node-gyp/8.9.1/include/node/v8.h:4164: error: expected unqualified-id before ‘&’ token
/home/brandon/.node-gyp/8.9.1/include/node/v8.h:4164: error: expected ‘)’ before ‘&’ token
/home/brandon/.node-gyp/8.9.1/include/node/v8.h:4164: error: expected ‘;’ before ‘&’ token
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/ostream_insert.h:36,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/string:46,
                 from ../../nan/nan.h:61,
                 from ../src/odbc.h:23,
                 from ../src/odbc.cpp:25:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘;’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected unqualified-id before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected declaration before end of line
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/brandon/node-v8.9.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 2.6.32-696.13.2.el6.x86_64
gyp ERR! command "/brandon/node-v8.9.1-linux-x64/bin/node" "/brandon/node-v8.9.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=/brandon/fs-loyalty-platform/node_modules/ibm_db/installer/clidriver"
gyp ERR! cwd /brandon/fs-loyalty-platform/node_modules/ibm_db
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.2.1 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@2.2.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by bnoordhuis** [comment]
Your compiler is too old.  Switch to g++ >= 4.8.5 and it should work.  That's not specific to this module, by the way.

**Comment by rhtpandeyIN** [comment]
Thanks @bnoordhuis for the quick response,
@brandonros , please follow Prerequisite guidelines:
`https://github.com/ibmdb/node-ibm_db#prerequisite`

**Comment by brandonros** [comment]
Can you guys do that thing where you get the pre-compiled binary portion into pre-gyp or gyp or whatever other packages use? node-sass automatically downloads a .node file based on your platform, for example

**Comment by brandonros** [comment]
Bump to above question.

**Comment by bimalkjha** [comment]
@brandonros I can see this error in the error output that you pasted: `../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler`. Please check your compiler version and fix this error. Btw, I checked on Ubuntu with node.js v8.9.4 and it works fine! Thanks.

**Comment by bimalkjha** [comment]
@brandonros Precompiled binary is different for different versions of node.js. To support so many versions of node.js on linux, it requires too many binaries. May I know the version of node.js you are trying to use? Thanks.

**Comment by brandonros** [comment]
linux 64 bit, node v8 lts

Regards,

Brandon
________________________________

**Comment by bimalkjha** [comment]
@brandonros Please download this [odbc_bindings.node](https://myshare.rocketsoftware.com/myshare/d/n57GMarR1) file compiled for linux_x64 and node.js v8.9.4. Can you give it a try and see? Need to copy it under `ibm_db\build\Release` directory. Thanks.

**Comment by brandonros** [comment]
```

Error: libdb2.so.1: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:672:18)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at bindings (/foo/scripts/brandon/foo/node_modules/ibm_db/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/foo/scripts/brandon/foo/node_modules/ibm_db/lib/odbc.js:31:31)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
```

**Comment by bimalkjha** [comment]
@brandonros First make sure you the directory `ibm_db/installer/clidriver` exist in your system. If it exists, then set below environment variables:
```
export PATH=..../ibm_db/installer/clidriver/bin:..../ibm_db/installer/clidriver/lib:$PATH
export LD_LIBRARY_PATH=..../ibm_db/installer/clidriver/bin:..../ibm_db/installer/clidriver/lib:$LD_LIBRARY_PATH
```
Thanks.

**Comment by brandonros** [comment]
I will give that a shot. However, I want to hear your opinion on this:

Unfortunately, I do not have root access on a box that is using glibc 2.12 (which is from 2010 I believe)

I believe this compiled driver is going to depend on a higher version of glibc, which you compiled it against. Is there any way to compile this statically, or without a modern glibc dependency?

**Comment by bimalkjha** [comment]
@brandonros We can not compile it statically or without modern glibc dependency. The node.js V4.x must use the newer version of glibc. If you use node.js v0.12.x, then it can get compiled and installed in your system using `npm install ibm_db` only. <BR>
Sharing dependency output for shared `odbc_bindings.node` file and `libdb2.so.1` as below:
```
$ ldd odbc_bindings.node
        linux-vdso.so.1 =>  (0x00007fff3075f000)
        libdb2.so.1 => /home/bjha/nodework/clidriver/lib/libdb2.so.1 (0x00007fe879617000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe879247000)
        libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007fe87900d000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe878e09000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe878bea000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fe8789e2000)
        libpam.so.0 => /lib/x86_64-linux-gnu/libpam.so.0 (0x00007fe8787d4000)
        libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007fe87846d000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe878167000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fe877e63000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fe877c4c000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe87ba34000)
        libaudit.so.1 => /lib/x86_64-linux-gnu/libaudit.so.1 (0x00007fe877a28000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fe87780e000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007fe8775ec000)
$ ldd libdb2.so.1
        linux-vdso.so.1 =>  (0x00007fff4eb4d000)
        libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f462f88c000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f462f688000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f462f46a000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f462f261000)
        libpam.so.0 => /lib/x86_64-linux-gnu/libpam.so.0 (0x00007f462f053000)
        libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f462eced000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f462e9e6000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f462e6e2000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f462e4cc000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f462e102000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4631cc7000)
        libaudit.so.1 => /lib/x86_64-linux-gnu/libaudit.so.1 (0x00007f462dede000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f462dcc5000)
        liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f462daa2000)
```
Thanks.

**Comment by brandonros** [comment]
I am using node v8 with no problems on the box.

Can you please recompile the file? It expired. Also, what steps are you doing to compile? When I compile on a working box and copy it to a non-working box, I get complaints about the driver being linked to a different glibc version. Is the same thing going to happen with the version you are providing?

**Comment by brandonros** [comment]
Error: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/brandon/node_modules/node-ibm_db/build/Release/odbc_bindings.node)

**Comment by brandonros** [comment]
```
g++ -static -fPIC -static-libgcc -static-libstdc++ '-DNODE_GYP_MODULE_NAME=odbc_bindings' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/brandon/.node-gyp/8.11.2/include/node -I/home/brandon/.node-gyp/8.11.2/src -I/home/brandon/.node-gyp/8.11.2/deps/uv/include -I/home/brandon/.node-gyp/8.11.2/deps/v8/include -I../node_modules/nan -I/home/brandon/node-ibm_db/installer/clidriver/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -g -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF ./Release/.deps/Release/obj.target/odbc_bindings/src/odbc.o.d.raw   -c -o Release/obj.target/odbc_bindings/src/odbc.o ../src/odbc.cpp
g++ -static -fPIC -static-libgcc -static-libstdc++ '-DNODE_GYP_MODULE_NAME=odbc_bindings' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/brandon/.node-gyp/8.11.2/include/node -I/home/brandon/.node-gyp/8.11.2/src -I/home/brandon/.node-gyp/8.11.2/deps/uv/include -I/home/brandon/.node-gyp/8.11.2/deps/v8/include -I../node_modules/nan -I/home/brandon/node-ibm_db/installer/clidriver/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -g -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF ./Release/.deps/Release/obj.target/odbc_bindings/src/odbc_connection.o.d.raw   -c -o Release/obj.target/odbc_bindings/src/odbc_connection.o ../src/odbc_connection.cpp
g++ -static -fPIC -static-libgcc -static-libstdc++ '-DNODE_GYP_MODULE_NAME=odbc_bindings' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/brandon/.node-gyp/8.11.2/include/node -I/home/brandon/.node-gyp/8.11.2/src -I/home/brandon/.node-gyp/8.11.2/deps/uv/include -I/home/brandon/.node-gyp/8.11.2/deps/v8/include -I../node_modules/nan -I/home/brandon/node-ibm_db/installer/clidriver/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -g -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF ./Release/.deps/Release/obj.target/odbc_bindings/src/odbc_statement.o.d.raw   -c -o Release/obj.target/odbc_bindings/src/odbc_statement.o ../src/odbc_statement.cpp
g++ -static -fPIC -static-libgcc -static-libstdc++ '-DNODE_GYP_MODULE_NAME=odbc_bindings' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/brandon/.node-gyp/8.11.2/include/node -I/home/brandon/.node-gyp/8.11.2/src -I/home/brandon/.node-gyp/8.11.2/deps/uv/include -I/home/brandon/.node-gyp/8.11.2/deps/v8/include -I../node_modules/nan -I/home/brandon/node-ibm_db/installer/clidriver/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -g -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF ./Release/.deps/Release/obj.target/odbc_bindings/src/odbc_result.o.d.raw   -c -o Release/obj.target/odbc_bindings/src/odbc_result.o ../src/odbc_result.cpp
g++ -shared -pthread -rdynamic -m64 -static -static-libgcc -static-libstdc++ -fPIC -Wl,-R,'$ORIGIN/../../installer/clidriver/lib'   -Wl,-soname=odbc_bindings.node -o Release/obj.target/odbc_bindings.node -Wl,--start-group Release/obj.target/odbc_bindings/src/odbc.o Release/obj.target/odbc_bindings/src/odbc_connection.o Release/obj.target/odbc_bindings/src/odbc_statement.o Release/obj.target/odbc_bindings/src/odbc_result.o -Wl,--end-group -L/home/brandon/node-ibm_db/installer/clidriver/lib -L/home/brandon/node-ibm_db/installer/clidriver/lib64 -ldb2
rm -rf "Release/odbc_bindings.node" && cp -af "Release/obj.target/odbc_bindings.node" "Release/odbc_bindings.node"
```

**Comment by brandonros** [comment]
I tried everything I could to get this library compiled statically, without libc dependency, but I am guessing `/node-ibm_db/installer/clidriver/lib/libdb2.so.1` requires GLIBC_2.14+, which sucks.

**Comment by bimalkjha** [comment]
@brandonros Yes, libdb2.so.1 has dependency on glibc. Please install it.
Regarding steps to compile the binary yourself by cloning the code from github, please check instructions documented [here](https://github.com/ibmdb/node-ibm_db/blob/master/INSTALL.md#222-manual-installation-by-using-git-clone). Thanks.

**Comment by bimalkjha** [comment]
You can check the dependency using `ldd libdb2.so.1` command as I commented [here](https://github.com/ibmdb/node-ibm_db/issues/352#issuecomment-395417902). Thanks.

**Comment by brandonros** [comment]
You 1,000% ignored what I asked.

Can you recompile libdb2.s0.1 to work with GLIBC_2.12 (old corporate versions of RHEL/CentOS)?

**Comment by bimalkjha** [comment]
@brandonros We can not recompile libdb2.so.1. We install it by downloading it from [here](https://www-01.ibm.com/marketing/iwm/iwm/web/download.do?source=swg-idsoc97&pageType=urx&S_PKG=linuxAMD64&lang=en_IN&dlmethod=http). It is compiled, packaged and uploaded by IBM Build team here: https://www-01.ibm.com/support/docview.wss?uid=swg21385217
You can download `IBM Data Server Driver for ODBC and CLI (CLI Driver)` from above link, untar and verify db2level command is working for you or not after adding clidriver\bin and clidriver\lib directory to PATH and LD_LIBRARY_PATH env variables.
If using this driver, db2level works for you, you can `export IBM_DB_HOME=<clidriver_path>` and then `npm install ibm_db`. If IBM_DB_HOME is set, ibm_db do not download clidriver but use the existing one.
If neither `IBM Data Server Driver for ODBC and CLI (CLI Driver)` nor `IBM Data Server Driver Package (DS Driver)` works in your system after [download](https://www-01.ibm.com/support/docview.wss?uid=swg21385217), ibm_db would not work. You may contact IBM Support if these [downloaded](https://www-01.ibm.com/support/docview.wss?uid=swg21385217) drivers do not work in your system. Thanks.
