### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by brayansuarezm** [ibmdb/node-ibm_db#367]
Error: The module '\\?\C:\Users\brian\Desktop\server201802212\node_modules\ibm_db\build\Release\odbc_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 59. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:689:18)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at bindings (C:\Users\brian\Desktop\server201802212\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\Users\brian\Desktop\server201802212\node_modules\ibm_db\lib\odbc.js:31:31)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\brian\Desktop\server201802212\server\models\swagger-v-1.js:1:75)

**Comment by rhtpandeyIN** [comment]
Hi @brayansuarezm , this is because, you are trying to rebuild/compile node-ibm_db with different node.js version than the with which you installed it.

Please follow below steps:
1) If you have proper build environment/setup (Visual studio installed), then you can simply run following command inside "\C:\Users\brian\Desktop\server201802212\node_modules\" directory.
 ---->  `npm rebuild`

2) If you don't have build setup, then please install node-ibm_db using below command:
`npm install ibm_db`  (Please be aware, once you have installed ibm_db with a particular node.js major version, then you can not use it - directly with other node.js major versions : for ex: If node-ibm_db was installed using node 4.X, and later system node.js version got changed then before using node-ibm_db, we need to rebuild it or simply install it again <if building is not possible>).

Thanks.
