### ISSUE TITLE
ibm_db and node 9.7.1

### ISSUE THREAD

**Issue by ichabondcrane** [ibmdb/node-ibm_db#371]
Hi, I'm a Windows 7 64-bit user with Node =9.7.1 installed...
I've tried various fixes such as npm rebuild and install and still get the same error message.
Mac users in our team, with Node 9.7.1 installed can start the app without any issues..
But for us windows users, Node server/app wont work and I get these error message ...... Thanks in advance for your help..
] Error: The module '\\?\C:\workspace\boardz\es-esw-core\node_modules\ibm_db\build\Release\odbc_bindings.node'
[1] was compiled against a different Node.js version using
[1] NODE_MODULE_VERSION 57. This version of Node.js requires
[1] NODE_MODULE_VERSION 59. Please try re-compiling or re-installing
[1] the module (for instance, using `npm rebuild` or `npm install`).
[1]     at Object.Module._extensions..node (module.js:691:18)
[1]     at Module.load (module.js:575:32)
[1]     at tryModuleLoad (module.js:515:12)
[1]     at Function.Module._load (module.js:507:3)
[1]     at Module.require (module.js:606:17)
[1]     at require (internal/module.js:11:18)
[1]     at bindings (C:\workspace\boardz\es-esw-core\node_modules\bindings\bindings.js:76:44)
[1]     at Object.<anonymous> (C:\workspace\boardz\es-esw-core\node_modules\ibm_db\lib\odbc.js:31:31)
[1]     at Module._compile (module.js:662:30)
[1]     at Object.Module._extensions..js (module.js:673:10)
[1]     at Module.load (module.js:575:32)
[1]     at tryModuleLoad (module.js:515:12)
[1]     at Function.Module._load (module.js:507:3)
[1]     at Module.require (module.js:606:17)
[1]     at require (internal/module.js:11:18)
[1]     at Object.<anonymous> (C:\workspace\boardz\es-esw-core\server\server.js:256:106

**Comment by rhtpandeyIN** [comment]
Hi @ichabondcrane , Please share the full error log. And also the details of, how you are installing node-ibm_db?

**Comment by ichabondcrane** [comment]
hi @rhtpandeyIN - I've listed the full error log above. 

I uninstall ibm_db first --> npm uninstall ibm_db 
and do an install again npm install ibm_db

I also did tried the same fix from #283 but this time it didnt work.

**Comment by rhtpandeyIN** [comment]
OK, I got it, it is same this time again, actually we haven't pushed node 9.X binaries yet, but now our module does support compilation and building at run time (if you have proper build setup - Visual studio installed and msbuild, then it should run without any issue).

I would suggest please use node 8.X for instance and we will update our module very soon. And I will update you for the same. thanks.

**Comment by ichabondcrane** [comment]
hi @rhtpandeyIN - do you have the steps on how to setup windows machine so that I could compile myself? I have msbuild installed as well. I tried to do it the other day but I got nowhere. thanks in advance

**Comment by rhtpandeyIN** [comment]
hi @ichabondcrane ,
Sorry for the late reply, but the steps for the "manual build on windows os" are already there in "INSTALL.md" file.
Please follow the below URL: 
`https://github.com/ibmdb/node-ibm_db/blob/master/INSTALL.md#-9-node-ibm_db-how-to-manually-build-on-windows`

**Comment by rhtpandeyIN** [comment]
Hi @ichabondcrane ,

for node v9.x node-ibm_db is working fine, I just installed it using latest node version 9.9.0 and tested the compiled binaries, everything is fine. I am using Windows 10.
Pre-compiled binary option will not work for now, as we have not pushed it yet, but as now run time compilation is there, so it should not create any problem.

For now I am closing the issue, if you have further doubts please feel free to comment.
thanks.

**Comment by bimalkjha** [comment]
@ichabondcrane Using ibm_db@2.3.1 you can compile code on windows with msbuild.exe is added in PATH env variable and visual studio is installed properly. Please verify. thanks.
