### ISSUE TITLE
Security Vulnerability in unzipper

### ISSUE THREAD

**Issue by virkt25** [ibmdb/node-ibm_db#417]
Hi,

This module currently uses `unzipper` version 0.7.x which is known to be vulnerable to the recently disclosed Zip Slip `Arbitrary File Write via Archive Extraction (Zip Slip)` attack. Can you please look into updating to the latest version of `unzipper` which is known to have fixed said vulnerability. 

Snyk Link for issue: 
- https://snyk.io/test/npm/loopback-ibmdb/2.3.0
- https://snyk.io/vuln/npm:unzipper:20180415

**Comment by bimalkjha** [comment]
@virkt25 When we update unzipper version to any version after 0.7.6 in package.json, getting below error:
```
> ibm_db@2.4.0 install C:\bimal\node_modules\ibm_db
> node installer/driverInstall.js

module.js:540
    throw err;
    ^

Error: Cannot find module 'big-integer'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\nodework\master\ibm_db\node_modules\unzipper\lib\D
ecrypt.js:1:76)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\nodework\master\ibm_db\node_modules\unzipper\lib\O
pen\unzip.js:2:15)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
npm WARN enoent ENOENT: no such file or directory, open 'C:\bimal\package.json'
npm WARN bimal No description
npm WARN bimal No repository field.
npm WARN bimal No README data
npm WARN bimal No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.4.0 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@2.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bjha\AppData\Roaming\npm-cache\_logs\2018-06-25T12_41_47_5
86Z-debug.log
```
Seems unzipper has added a new dependency of 'big-integer' package and unable to install it. I checked unzipper/node-modules and do not see this package there. Seems, 0.8.x version of unzipper is not working properly. Thanks.

**Comment by sjtuzl** [comment]
@bimalkjha - we've hit the same security warning on this unzip module. When we will release a new version? The most recent release was more than 1 year ago.

**Comment by sjtuzl** [comment]
I found the 2.4 release which does not include the security patch - https://github.com/ibmdb/node-ibm_db/releases/tag/v2.4.0

**Comment by virkt25** [comment]
@bimaljha Can we get a new version released which includes the updated version please and thanks.
