### ISSUE TITLE
Compilation on Ubuntu 16.04 LTS fails

### ISSUE THREAD

**Issue by gurusrin** [ibmdb/node-ibm_db#425]
I have been trying to compile the ibm_db package on an Ubuntu 16.04 LTS machine running as guest OS on VirtualBox. While building the code, it gives me the following error and fails to install.
```

Downloading and extraction of DB2 ODBC CLI Driver completed successfully ...

make: Entering directory '/home/osboxes/electron-app/node_modules/ibm_db/build'
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
odbc_bindings.target.mk:108: recipe for target 'Release/obj.target/odbc_bindings/src/odbc.o' failed
make: Leaving directory '/home/osboxes/electron-app/node_modules/ibm_db/build'

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"
../src/odbc.cpp: In static member function ‘static void ODBC::UV_AfterCreateConnection(uv_work_t*, int)’:
../src/odbc.cpp:210:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     data->cb->Call(1, info);
                           ^
In file included from ../src/odbc.h:23:0,
                 from ../src/odbc.cpp:28:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/odbc.cpp:217:99: error: no matching function for call to ‘v8::Function::NewInstance(int, v8::Local<v8::Value> [2])’
     Local<Object> js_result = Nan::New<Function>(ODBCConnection::constructor)->NewInstance(2, info);
                                                                                                   ^
In file included from ../src/odbc.cpp:22:0:
/home/osboxes/.node-gyp/10.5.0/include/node/v8.h:3911:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^
/home/osboxes/.node-gyp/10.5.0/include/node/v8.h:3911:44: note:   candidate expects 3 arguments, 2 provided
/home/osboxes/.node-gyp/10.5.0/include/node/v8.h:3914:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^
/home/osboxes/.node-gyp/10.5.0/include/node/v8.h:3914:44: note:   candidate expects 1 argument, 2 provided
../src/odbc.cpp:222:27: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
     data->cb->Call(2, info);
                           ^
In file included from ../src/odbc.h:23:0,
                 from ../src/odbc.cpp:28:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/odbc.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ODBC::CreateConnectionSync(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/odbc.cpp:262:99: error: no matching function for call to ‘v8::Function::NewInstance(int, v8::Local<v8::Value> [2])’
   Local<Object> js_result = Nan::New<Function>(ODBCConnection::constructor)->NewInstance(2, params);
                                                                                                   ^
In file included from ../src/odbc.cpp:22:0:
/home/osboxes/.node-gyp/10.5.0/include/node/v8.h:3911:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>, int, v8::Local<v8::Value>*) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^
/home/osboxes/.node-gyp/10.5.0/include/node/v8.h:3911:44: note:   candidate expects 3 arguments, 2 provided
/home/osboxes/.node-gyp/10.5.0/include/node/v8.h:3914:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                            ^
/home/osboxes/.node-gyp/10.5.0/include/node/v8.h:3914:44: note:   candidate expects 1 argument, 2 provided
../src/odbc.cpp: In static member function ‘static v8::Local<v8::Value> ODBC::CallbackSQLError(SQLSMALLINT, SQLHANDLE, char*, Nan::Callback*)’:
../src/odbc.cpp:1194:19: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   cb->Call(1, info);
                   ^
In file included from ../src/odbc.h:23:0,
                 from ../src/odbc.cpp:28:
../../nan/nan.h:1618:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^
../src/odbc.cpp: In static member function ‘static v8::Local<v8::Value> ODBC::GetSQLError(SQLSMALLINT, SQLHANDLE, char*)’:
../src/odbc.cpp:1258:87: error: no matching function for call to ‘v8::Object::SetPrototype(v8::Local<v8::Value>)’
       objError->SetPrototype(Exception::Error(Nan::New(errorMessage).ToLocalChecked()));
                                                                                       ^
In file included from ../src/odbc.cpp:22:0:
/home/osboxes/.node-gyp/10.5.0/include/node/v8.h:3360:37: note: candidate: v8::Maybe<bool> v8::Object::SetPrototype(v8::Local<v8::Context>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> SetPrototype(Local<Context> context,
                                     ^
/home/osboxes/.node-gyp/10.5.0/include/node/v8.h:3360:37: note:   candidate expects 2 arguments, 1 provided
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.15.0-24-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=/home/osboxes/electron-app/node_modules/ibm_db/installer/clidriver"
gyp ERR! cwd /home/osboxes/electron-app/node_modules/ibm_db
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 

    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"' }

```
It seems that there is an update to the Node's header files and the same needs to be updated in ibm_db package. Any help to resolve this error would be appreciated.

Thank you in advance.

**Comment by bimalkjha** [comment]
@gurusrin Your node.js version is v10.5.0, please use a version < 10.0. That should work. Thanks.

**Comment by gurusrin** [comment]
Thank you Bimal!

I downgraded to the 8.11.3 and it compiles fine.
