### ISSUE TITLE
Npm install issue on linuxamd64

### ISSUE THREAD

**Issue by selden-lin** [ibmdb/node-ibm_db#453]
Hello I am trying to npm install ibm_db but I am running into this issue.
 
 
 
Downloading and extraction of DB2 ODBC CLI Driver completed successfully ...
make: Entering directory `/home/svtdbm/db2_test/node_modules/ibm_db/build'
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
make: Leaving directory `/home/svtdbm/db2_test/node_modules/ibm_db/build'
{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"
cc1plus: error: unrecognized command line option "-std=gnu++1y"
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 3.0.101-63-default
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=/home/svtdbm/db2_test/node_modules/ibm_db/installer/clidriver"
gyp ERR! cwd /home/svtdbm/db2_test/node_modules/ibm_db
gyp ERR! node -v v10.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
    at ChildProcess.exithandler (child_process.js:291:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"' }

**Comment by rhtpandeyIN** [comment]
Please use nodejs version < 10.X, 10.X support yet to be delivered. Thanks.

**Comment by rhtpandeyIN** [comment]
Closing the issue, as not an issue.
