### ISSUE TITLE
Ubuntu install fails

### ISSUE THREAD

**Issue by granteagon** [ibmdb/node-ibm_db#48]
Trying to install on node 0.11.14 and Ubuntu 15.04, I get the following error:

```
> ibm_db@0.0.11 install /srv/v4/node_modules/ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz...
Download and extraction of DB2 ODBC CLI Driver completed successfully ...
make: Entering directory '/srv/v4/node_modules/ibm_db/build'
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
odbc_bindings.target.mk:99: recipe for target 'Release/obj.target/odbc_bindings/src/odbc.o' failed
make: Leaving directory '/srv/v4/node_modules/ibm_db/build'

{ [Error: Command failed: /bin/sh -c node-gyp configure build --IBM_DB_HOME=$IBM_DB_HOME --IBM_DB_HOME_WIN=%IBM_DB_HOME% --IS_DOWNLOADED=true
In file included from ../src/odbc.cpp:25:0:
../src/odbc.h:76:85: error: ‘NanCallback’ has not been declared
     static Handle<Value> CallbackSQLError(SQLSMALLINT handleType, SQLHANDLE handle, NanCallback* cb);
                                                                                     ^
../src/odbc.h:77:101: error: ‘NanCallback’ has not been declared
     static Handle<Value> CallbackSQLError (SQLSMALLINT handleType, SQLHANDLE handle, char* message, NanCallback* cb);
                                                                                                     ^
../src/odbc.h:112:3: error: ‘NanCallback’ does not name a type
   NanCallback* cb;
   ^
In file included from ../src/odbc.cpp:26:0:
../src/odbc_connection.h:95:7: error: ‘NanCallback’ does not name a type
       NanCallback* callback;
       ^
../src/odbc_connection.h:113:3: error: ‘NanCallback’ does not name a type
   NanCallback* cb;
   ^
../src/odbc_connection.h:120:3: error: ‘NanCallback’ does not name a type
   NanCallback* cb;
   ^
../src/odbc_connection.h:143:3: error: ‘NanCallback’ does not name a type
   NanCallback* cb;
   ^
../src/odbc_connection.h:151:3: error: ‘NanCallback’ does not name a type
   NanCallback* cb;
   ^
In file included from ../src/odbc.cpp:27:0:
../src/odbc_result.h:66:7: error: ‘NanCallback’ does not name a type
       NanCallback* cb;
       ^
In file included from ../src/odbc.cpp:28:0:
../src/odbc_statement.h:73:7: error: ‘NanCallback’ does not name a type
       NanCallback* callback;
       ^
../src/odbc_statement.h:95:3: error: ‘NanCallback’ does not name a type
   NanCallback* cb;
   ^
../src/odbc_statement.h:103:3: error: ‘NanCallback’ does not name a type
   NanCallback* cb;
   ^
../src/odbc_statement.h:109:3: error: ‘NanCallback’ does not name a type
   NanCallback* cb;
   ^
../src/odbc_statement.h:117:3: error: ‘NanCallback’ does not name a type
   NanCallback* cb;
   ^
../src/odbc.cpp: In static member function ‘static void ODBC::Init(v8::Handle<v8::Object>)’:
../src/odbc.cpp:48:12: error: ‘NanScope’ was not declared in this scope
   NanScope();
            ^
../src/odbc.cpp:50:50: error: ‘NanNew’ was not declared in this scope
   Local<FunctionTemplate> constructor_template = NanNew<FunctionTemplate>(New);
                                                  ^
../src/odbc.cpp:50:73: error: expected primary-expression before ‘>’ token
   Local<FunctionTemplate> constructor_template = NanNew<FunctionTemplate>(New);
                                                                         ^
../src/odbc.cpp:66:42: error: expected primary-expression before ‘>’ token
   constructor_template->Set(NanNew<String>("SQL_CLOSE"), NanNew<Number>(SQL_CLOSE), constant_attributes);
                                          ^
../src/odbc.cpp:66:71: error: expected primary-expression before ‘>’ token
   constructor_template->Set(NanNew<String>("SQL_CLOSE"), NanNew<Number>(SQL_CLOSE), constant_attributes);
                                                                       ^
../src/odbc.cpp:67:42: error: expected primary-expression before ‘>’ token
   constructor_template->Set(NanNew<String>("SQL_DROP"), NanNew<Number>(SQL_DROP), constant_attributes);
                                          ^
../src/odbc.cpp:67:70: error: expected primary-expression before ‘>’ token
   constructor_template->Set(NanNew<String>("SQL_DROP"), NanNew<Number>(SQL_DROP), constant_attributes);
                                                                      ^
../src/odbc.cpp:68:42: error: expected primary-expression before ‘>’ token
   constructor_template->Set(NanNew<String>("SQL_UNBIND"), NanNew<Number>(SQL_UNBIND), constant_attributes);
                                          ^
../src/odbc.cpp:68:72: error: expected primary-expression before ‘>’ token
   constructor_template->Set(NanNew<String>("SQL_UNBIND"), NanNew<Number>(SQL_UNBIND), constant_attributes);
                                                                        ^
../src/odbc.cpp:69:42: error: expected primary-expression before ‘>’ token
   constructor_template->Set(NanNew<String>("SQL_RESET_PARAMS"), NanNew<Number>(SQL_RESET_PARAMS), constant_attributes);
                                          ^
../src/odbc.cpp:69:78: error: expected primary-expression before ‘>’ token
   constructor_template->Set(NanNew<String>("SQL_RESET_PARAMS"), NanNew<Number>(SQL_RESET_PARAMS), constant_attributes);
                                                                              ^
../src/odbc.cpp:70:42: error: expected primary-expression before ‘>’ token
   constructor_template->Set(NanNew<String>("SQL_DESTROY"), NanNew<Number>(SQL_DESTROY), constant_attributes);
                                          ^
../src/odbc.cpp:70:73: error: expected primary-expression before ‘>’ token
   constructor_template->Set(NanNew<String>("SQL_DESTROY"), NanNew<Number>(SQL_DESTROY), constant_attributes);
                                                                         ^
../src/odbc.cpp:71:42: error: expected primary-expression before ‘>’ token
   constructor_template->Set(NanNew<String>("FETCH_ARRAY"), NanNew<Number>(FETCH_ARRAY), constant_attributes);
                                          ^
../src/odbc.cpp:71:73: error: expected primary-expression before ‘>’ token
   constructor_template->Set(NanNew<String>("FETCH_ARRAY"), NanNew<Number>(FETCH_ARRAY), constant_attributes);
                                                                         ^
In file included from ../src/odbc.cpp:25:0:
../src/odbc.h:235:44: error: expected primary-expression before ‘>’ token
   (constructor_template)->Set(NanNew<String>(#constant),                \
                                            ^
../src/odbc.cpp:72:3: note: in expansion of macro ‘NODE_ODBC_DEFINE_CONSTANT’
   NODE_ODBC_DEFINE_CONSTANT(constructor_template, FETCH_OBJECT);
   ^
../src/odbc.h:236:30: error: expected primary-expression before ‘>’ token
                 NanNew<Number>(constant),                               \
                              ^
../src/odbc.cpp:72:3: note: in expansion of macro ‘NODE_ODBC_DEFINE_CONSTANT’
   NODE_ODBC_DEFINE_CONSTANT(constructor_template, FETCH_OBJECT);
   ^
../src/odbc.cpp:75:87: error: invalid conversion from ‘Nan::NAN_METHOD_RETURN_TYPE (*)(Nan::NAN_METHOD_ARGS_TYPE) {aka void (*)(const Nan::FunctionCallbackInfo<v8::Value>&)}’ to ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’ [-fpermissive]
   NODE_SET_PROTOTYPE_METHOD(constructor_template, "createConnection", CreateConnection);
                                                                                       ^
In file included from ../src/odbc.cpp:20:0:
/root/.node-gyp/0.12.7/src/node.h:244:13: note: initializing argument 3 of ‘void node::NODE_SET_PROTOTYPE_METHOD(v8::Handle<v8::FunctionTemplate>, const char*, v8::FunctionCallback)’
 inline void NODE_SET_PROTOTYPE_METHOD(v8::Handle<v8::FunctionTemplate> recv,
             ^
../src/odbc.cpp:76:95: error: invalid conversion from ‘Nan::NAN_METHOD_RETURN_TYPE (*)(Nan::NAN_METHOD_ARGS_TYPE) {aka void (*)(const Nan::FunctionCallbackInfo<v8::Value>&)}’ to ‘v8::FunctionCallback {aka void (*)(const v8::FunctionCallbackInfo<v8::Value>&)}’ [-fpermissive]
   NODE_SET_PROTOTYPE_METHOD(constructor_template, "createConnectionSync", CreateConnectionSync);
                                                                                               ^
In file included from ../src/odbc.cpp:20:0:
/root/.node-gyp/0.12.7/src/node.h:244:13: note: initializing argument 3 of ‘void node::NODE_SET_PROTOTYPE_METHOD(v8::Handle<v8::FunctionTemplate>, const char*, v8::FunctionCallback)’
 inline void NODE_SET_PROTOTYPE_METHOD(v8::Handle<v8::FunctionTemplate> recv,
             ^
../src/odbc.cpp:79:71: error: ‘NanAssignPersistent’ was not declared in this scope
   NanAssignPersistent(constructor, constructor_template->GetFunction());
                                                                       ^
../src/odbc.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ODBC::New(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/odbc.cpp:124:12: error: ‘NanScope’ was not declared in this scope
   NanScope();
            ^
../src/odbc.cpp:127:13: error: ‘args’ was not declared in this scope
   dbo->Wrap(args.Holder());
             ^
../src/odbc.cpp:143:34: error: ‘NanThrowError’ was not declared in this scope
     return NanThrowError(objError);
                                  ^
../src/odbc.cpp:143:34: error: return-statement with a value, in function returning 'void' [-fpermissive]
../src/odbc.cpp:149:31: error: ‘NanReturnValue’ was not declared in this scope
   NanReturnValue(args.Holder());
                               ^
../src/odbc.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ODBC::CreateConnection(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/odbc.cpp:163:12: error: ‘NanScope’ was not declared in this scope
   NanScope();
            ^
../src/odbc.cpp:165:24: error: ‘args’ was not declared in this scope
   Local<Function> cb = args[0].As<Function>();
                        ^
../src/odbc.cpp:165:43: error: expected primary-expression before ‘>’ token
   Local<Function> cb = args[0].As<Function>();
                                           ^
../src/odbc.cpp:165:45: error: expected primary-expression before ‘)’ token
   Local<Function> cb = args[0].As<Function>();
                                             ^
../src/odbc.cpp:166:3: error: ‘NanCallback’ was not declared in this scope
   NanCallback *callback = new NanCallback(cb);
   ^
../src/odbc.cpp:166:16: error: ‘callback’ was not declared in this scope
   NanCallback *callback = new NanCallback(cb);
                ^
../src/odbc.cpp:166:31: error: expected type-specifier before ‘NanCallback’
   NanCallback *callback = new NanCallback(cb);
                               ^
../src/odbc.cpp:178:9: error: ‘struct create_connection_work_data’ has no member named ‘cb’
   data->cb = callback;
         ^
../src/odbc.cpp:187:31: error: ‘NanUndefined’ was not declared in this scope
   NanReturnValue(NanUndefined());
                               ^
../src/odbc.cpp:187:32: error: ‘NanReturnValue’ was not declared in this scope
   NanReturnValue(NanUndefined());
                                ^
../src/odbc.cpp:165:19: warning: unused variable ‘cb’ [-Wunused-variable]
   Local<Function> cb = args[0].As<Function>();
                   ^
../src/odbc.cpp: In static member function ‘static void ODBC::UV_AfterCreateConnection(uv_work_t*, int)’:
../src/odbc.cpp:206:12: error: ‘NanScope’ was not declared in this scope
   NanScope();
            ^
../src/odbc.cpp:217:11: error: ‘struct create_connection_work_data’ has no member named ‘cb’
     data->cb->Call(1, args);
           ^
../src/odbc.cpp:221:15: error: ‘NanNew’ was not declared in this scope
     args[0] = NanNew<External>(data->dbo->m_hEnv);
               ^
../src/odbc.cpp:221:30: error: expected primary-expression before ‘>’ token
     args[0] = NanNew<External>(data->dbo->m_hEnv);
                              ^
../src/odbc.cpp:222:30: error: expected primary-expression before ‘>’ token
     args[1] = NanNew<External>(data->hDBC);
                              ^
../src/odbc.cpp:224:46: error: expected primary-expression before ‘>’ token
     Local<Object> js_result = NanNew<Function>(ODBCConnection::constructor)->NewInstance(2, args);
                                              ^
../src/odbc.cpp:224:76: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::Function>’
     Local<Object> js_result = NanNew<Function>(ODBCConnection::constructor)->NewInstance(2, args);
                                                                            ^
../src/odbc.cpp:226:27: error: expected primary-expression before ‘>’ token
     args[0] = NanNew<Value>(NanNull());
                           ^
../src/odbc.cpp:226:37: error: ‘NanNull’ was not declared in this scope
     args[0] = NanNew<Value>(NanNull());
                                     ^
../src/odbc.cpp:229:11: error: ‘struct create_connection_work_data’ has no member named ‘cb’
     data->cb->Call(2, args);
           ^
../src/odbc.cpp:238:16: error: ‘struct create_connection_work_data’ has no member named ‘cb’
   delete data->cb;
                ^
../src/odbc.cpp: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE ODBC::CreateConnectionSync(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/odbc.cpp:250:12: error: ‘NanScope’ was not declared in this scope
   NanScope();
            ^
../src/odbc.cpp:252:40: error: ‘args’ was not declared in this scope
   ODBC* dbo = ObjectWrap::Unwrap<ODBC>(args.Holder());
                                        ^
../src/odbc.cpp:268:15: error: ‘NanNew’ was not declared in this scope
   params[0] = NanNew<External>(dbo->m_hEnv);
               ^
../src/odbc.cpp:268:30: error: expected primary-expression before ‘>’ token
   params[0] = NanNew<External>(dbo->m_hEnv);
                              ^
../src/odbc.cpp:269:30: error: expected primary-expression before ‘>’ token
   params[1] = NanNew<External>(hDBC);
                              ^
../src/odbc.cpp:271:44: error: expected primary-expression before ‘>’ token
   Local<Object> js_result = NanNew<Function>(ODBCConnection::constructor)->NewInstance(2, params);
                                            ^
../src/odbc.cpp:271:74: error: base operand of ‘->’ has non-pointer type ‘v8::Persistent<v8::Function>’
   Local<Object> js_result = NanNew<Function>(ODBCConnection::constructor)->NewInstance(2, params);
                                                                          ^
../src/odbc.cpp:273:27: error: ‘NanReturnValue’ was not declared in this scope
   NanReturnValue(js_result);
                           ^
../src/odbc.cpp: In static member function ‘static v8::Handle<v8::Value> ODBC::GetColumnValue(SQLHSTMT, Column, uint16_t*, int)’:
../src/odbc.cpp:369:21: error: ‘NanEscapableScope’ was not declared in this scope
   NanEscapableScope();
                     ^
../src/odbc.cpp:397:41: error: ‘NanNull’ was not declared in this scope
           return NanEscapeScope(NanNull());
                                         ^
../src/odbc.cpp:397:42: error: ‘NanEscapeScope’ was not declared in this scope
           return NanEscapeScope(NanNull());
                                          ^
../src/odbc.cpp:400:33: error: ‘NanNew’ was not declared in this scope
           return NanEscapeScope(NanNew<Number>((int)value));
                                 ^
../src/odbc.cpp:400:46: error: expected primary-expression before ‘>’ token
           return NanEscapeScope(NanNew<Number>((int)value));
                                              ^
../src/odbc.cpp:400:59: error: ‘NanEscapeScope’ was not declared in this scope
           return NanEscapeScope(NanNew<Number>((int)value));
                                                           ^
../src/odbc.cpp:403:33: error: ‘NanNew’ was not declared in this scope
           return NanEscapeScope(NanNew<Number>((short)value));
                                 ^
../src/odbc.cpp:403:46: error: expected primary-expression before ‘>’ token
           return NanEscapeScope(NanNew<Number>((short)value));
                                              ^
../src/odbc.cpp:403:61: error: ‘NanEscapeScope’ was not declared in this scope
           return NanEscapeScope(NanNew<Number>((short)value));
                                                             ^
../src/odbc.cpp:406:33: error: ‘NanNew’ was not declared in this scope
           return NanEscapeScope(NanNew<Number>((long)value));
                                 ^
../src/odbc.cpp:406:46: error: expected primary-expression before ‘>’ token
           return NanEscapeScope(NanNew<Number>((long)value));
                                              ^
../src/odbc.cpp:406:60: error: ‘NanEscapeScope’ was not declared in this scope
           return NanEscapeScope(NanNew<Number>((long)value));
                                                            ^
../src/odbc.cpp:409:33: error: ‘NanNew’ was not declared in this scope
           return NanEscapeScope(NanNew<Number>(value));
                                 ^
../src/odbc.cpp:409:46: error: expected primary-expression before ‘>’ token
           return NanEscapeScope(NanNew<Number>(value));
                                              ^
../src/odbc.cpp:409:54: error: ‘NanEscapeScope’ was not declared in this scope
           return NanEscapeScope(NanNew<Number>(value));
                                                      ^
../src/odbc.cpp:435:41: error: ‘NanNull’ was not declared in this scope
           return NanEscapeScope(NanNull());
                                         ^
../src/odbc.cpp:435:42: error: ‘NanEscapeScope’ was not declared in this scope
           return NanEscapeScope(NanNull());
                                          ^
../src/odbc.cpp:439:33: error: ‘NanNew’ was not declared in this scope
           return NanEscapeScope(NanNew<Number>(value));
                                 ^
../src/odbc.cpp:439:46: error: expected primary-expression before ‘>’ token
           return NanEscapeScope(NanNew<Number>(value));
                                              ^
../src/odbc.cpp:439:54: error: ‘NanEscapeScope’ was not declared in this scope
           return NanEscapeScope(NanNew<Number>(value));
                                                      ^
../src/odbc.cpp:506:39: error: ‘NanNull’ was not declared in this scope
         return NanEscapeScope(NanNull());
                                       ^
../src/odbc.cpp:506:40: error: ‘NanEscapeScope’ was not declared in this scope
         return NanEscapeScope(NanNull());
                                        ^
../src/odbc.cpp:525:31: error: ‘NanNew’ was not declared in this scope
         return NanEscapeScope(NanNew<Date>((double(timelocal(&timeInfo)) * 1000)
                               ^
../src/odbc.cpp:525:42: error: expected primary-expression before ‘>’ token
         return NanEscapeScope(NanNew<Date>((double(timelocal(&timeInfo)) * 1000)
                                          ^
../src/odbc.cpp:526:59: error: ‘NanEscapeScope’ was not declared in this scope
                           + (odbcTime.fraction / 1000000)));
                                                           ^
../src/odbc.cpp:548:39: error: ‘NanNull’ was not declared in this scope
         return NanEscapeScope(NanNull());
                                       ^
../src/odbc.cpp:548:40: error: ‘NanEscapeScope’ was not declared in this scope
         return NanEscapeScope(NanNull());
                                        ^
../src/odbc.cpp:552:69: error: ‘NanNew’ was not declared in this scope
         return NanEscapeScope(NanNew((*buffer == '0') ? false : true));
                                                                     ^
../src/odbc.cpp:552:70: error: ‘NanEscapeScope’ was not declared in this scope
         return NanEscapeScope(NanNew((*buffer == '0') ? false : true));
                                                                      ^
../src/odbc.cpp:577:41: error: ‘NanNull’ was not declared in this scope
           return NanEscapeScope(NanNull());
                                         ^
../src/odbc.cpp:577:42: error: ‘NanEscapeScope’ was not declared in this scope
           return NanEscapeScope(NanNull());
                                          ^
../src/odbc.cpp:591:44: error: ‘NanNew’ was not declared in this scope
             str = NanNew((uint16_t*) buffer);
                                            ^
../src/odbc.cpp:599:64: error: ‘NanNew’ was not declared in this scope
             str = String::Concat(str, NanNew((uint16_t*) buffer));
                                                                ^
../src/odbc.cpp:623:13: error: ‘NanThrowError’ was not declared in this scope
            ));
             ^
../src/odbc.cpp:624:46: error: ‘NanUndefined’ was not declared in this scope
           return NanEscapeScope(NanUndefined());
                                              ^
../src/odbc.cpp:624:47: error: ‘NanEscapeScope’ was not declared in this scope
           return NanEscapeScope(NanUndefined());
                                               ^
../src/odbc.cpp:629:32: error: ‘NanEscapeScope’ was not declared in this scope
       return NanEscapeScope(str);
                                ^
../src/odbc.cpp: In static member function ‘static v8::Local<v8::Object> ODBC::GetRecordTuple(SQLHSTMT, Column*, short int*, uint16_t*, int)’:
../src/odbc.cpp:640:21: error: ‘NanEscapableScope’ was not declared in this scope
   NanEscapableScope();
                     ^
../src/odbc.cpp:642:25: error: ‘NanNew’ was not declared in this scope
   Local<Object> tuple = NanNew<Object>();
                         ^
../src/odbc.cpp:642:38: error: expected primary-expression before ‘>’ token
   Local<Object> tuple = NanNew<Object>();
                                      ^
../src/odbc.cpp:642:40: error: expected primary-expression before ‘)’ token
   Local<Object> tuple = NanNew<Object>();
                                        ^
../src/odbc.cpp:654:30: error: ‘NanEscapeScope’ was not declared in this scope
   return NanEscapeScope(tuple);
                              ^
../src/odbc.cpp: In static member function ‘static v8::Handle<v8::Value> ODBC::GetRecordArray(SQLHSTMT, Column*, short int*, uint16_t*, int)’:
../src/odbc.cpp:664:21: error: ‘NanEscapableScope’ was not declared in this scope
   NanEscapableScope();
                     ^
../src/odbc.cpp:666:24: error: ‘NanNew’ was not declared in this scope
   Local<Array> array = NanNew<Array>();
                        ^
../src/odbc.cpp:666:36: error: expected primary-expression before ‘>’ token
   Local<Array> array = NanNew<Array>();
                                    ^
../src/odbc.cpp:666:38: error: expected primary-expression before ‘)’ token
   Local<Array> array = NanNew<Array>();
                                      ^
../src/odbc.cpp:673:30: error: ‘NanEscapeScope’ was not declared in this scope
   return NanEscapeScope(array);
                              ^
../src/odbc.cpp: At global scope:
../src/odbc.cpp:789:39: error: ‘NanCallback’ has not been declared
                                       NanCallback* cb) {
                                       ^
../src/odbc.cpp: In static member function ‘static v8::Handle<v8::Value> ODBC::CallbackSQLError(SQLSMALLINT, SQLHANDLE, int*)’:
../src/odbc.cpp:790:21: error: ‘NanEscapableScope’ was not declared in this scope
   NanEscapableScope();
                     ^
../src/odbc.cpp:796:8: error: ‘NanEscapeScope’ was not declared in this scope
     cb));
        ^
../src/odbc.cpp: At global scope:
../src/odbc.cpp:802:39: error: ‘NanCallback’ has not been declared
                                       NanCallback* cb) {
                                       ^
../src/odbc.cpp: In static member function ‘static v8::Handle<v8::Value> ODBC::CallbackSQLError(SQLSMALLINT, SQLHANDLE, char*, int*)’:
../src/odbc.cpp:803:21: error: ‘NanEscapableScope’ was not declared in this scope
   NanEscapableScope();
                     ^
../src/odbc.cpp:813:7: error: request for member ‘Call’ in ‘* cb’, which is of non-class type ‘int’
   cb->Call(1, args);
       ^
../src/odbc.cpp:815:38: error: ‘NanUndefined’ was not declared in this scope
   return NanEscapeScope(NanUndefined());
                                      ^
../src/odbc.cpp:815:39: error: ‘NanEscapeScope’ was not declared in this scope
   return NanEscapeScope(NanUndefined());
                                       ^
../src/odbc.cpp: In static member function ‘static v8::Local<v8::Object> ODBC::GetSQLError(SQLSMALLINT, SQLHANDLE)’:
../src/odbc.cpp:823:21: error: ‘NanEscapableScope’ was not declared in this scope
   NanEscapableScope();
                     ^
../src/odbc.cpp:828:38: error: ‘NanEscapeScope’ was not declared in this scope
     (char *) "[node-odbc] SQL_ERROR"));
                                      ^
../src/odbc.cpp: In static member function ‘static v8::Local<v8::Object> ODBC::GetSQLError(SQLSMALLINT, SQLHANDLE, char*)’:
../src/odbc.cpp:832:21: error: ‘NanEscapableScope’ was not declared in this scope
   NanEscapableScope();
                     ^
../src/odbc.cpp:836:28: error: ‘NanNew’ was not declared in this scope
   Local<Object> objError = NanNew<Object>();
                            ^
../src/odbc.cpp:836:41: error: expected primary-expression before ‘>’ token
   Local<Object> objError = NanNew<Object>();
                                         ^
../src/odbc.cpp:836:43: error: expected primary-expression before ‘)’ token
   Local<Object> objError = NanNew<Object>();
                                           ^
../src/odbc.cpp:858:37: error: expected primary-expression before ‘>’ token
   Local<Array> errors = NanNew<Array>();
                                     ^
../src/odbc.cpp:858:39: error: expected primary-expression before ‘)’ token
   Local<Array> errors = NanNew<Array>();
                                       ^
../src/odbc.cpp:894:33: error: ‘NanEscapeScope’ was not declared in this scope
   return NanEscapeScope(objError);
                                 ^
../src/odbc.cpp: In static member function ‘static v8::Local<v8::Array> ODBC::GetAllRecordsSync(HENV, HDBC, HSTMT, uint16_t*, int)’:
../src/odbc.cpp:908:21: error: ‘NanEscapableScope’ was not declared in this scope
   NanEscapableScope();
                     ^
../src/odbc.cpp:910:28: error: ‘NanNew’ was not declared in this scope
   Local<Object> objError = NanNew<Object>();
                            ^
../src/odbc.cpp:910:41: error: expected primary-expression before ‘>’ token
   Local<Object> objError = NanNew<Object>();
                                         ^
../src/odbc.cpp:910:43: error: expected primary-expression before ‘)’ token
   Local<Object> objError = NanNew<Object>();
                                           ^
../src/odbc.cpp:918:35: error: expected primary-expression before ‘>’ token
   Local<Array> rows = NanNew<Array>();
                                   ^
../src/odbc.cpp:918:37: error: expected primary-expression before ‘)’ token
   Local<Array> rows = NanNew<Array>();
                                     ^
../src/odbc.cpp:961:29: error: ‘NanEscapeScope’ was not declared in this scope
   return NanEscapeScope(rows);
                             ^
../src/odbc.cpp: In static member function ‘static v8::Handle<v8::Value> ODBC::GetColumnValue(SQLHSTMT, Column, uint16_t*, int)’:
../src/odbc.cpp:631:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/odbc.cpp: In static member function ‘static v8::Local<v8::Object> ODBC::GetRecordTuple(SQLHSTMT, Column*, short int*, uint16_t*, int)’:
../src/odbc.cpp:655:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/odbc.cpp: In static member function ‘static v8::Handle<v8::Value> ODBC::GetRecordArray(SQLHSTMT, Column*, short int*, uint16_t*, int)’:
../src/odbc.cpp:674:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/odbc.cpp: In static member function ‘static v8::Handle<v8::Value> ODBC::CallbackSQLError(SQLSMALLINT, SQLHANDLE, int*)’:
../src/odbc.cpp:797:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/odbc.cpp: In static member function ‘static v8::Handle<v8::Value> ODBC::CallbackSQLError(SQLSMALLINT, SQLHANDLE, char*, int*)’:
../src/odbc.cpp:816:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/odbc.cpp: In static member function ‘static v8::Local<v8::Object> ODBC::GetSQLError(SQLSMALLINT, SQLHANDLE)’:
../src/odbc.cpp:829:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/odbc.cpp: In static member function ‘static v8::Local<v8::Object> ODBC::GetSQLError(SQLSMALLINT, SQLHANDLE, char*)’:
../src/odbc.cpp:895:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
../src/odbc.cpp: In static member function ‘static v8::Local<v8::Array> ODBC::GetAllRecordsSync(HENV, HDBC, HSTMT, uint16_t*, int)’:
../src/odbc.cpp:962:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 3.19.0-22-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IBM_DB_HOME=/srv/v4/node_modules/ibm_db/installer/clidriver" "--IBM_DB_HOME_WIN=%IBM_DB_HOME%" "--IS_DOWNLOADED=true"
gyp ERR! cwd /srv/v4/node_modules/ibm_db
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c node-gyp configure build --IBM_DB_HOME=$IBM_DB_HOME --IBM_DB_HOME_WIN=%IBM_DB_HOME% --IS_DOWNLOADED=true' }
npm ERR! Linux 3.19.0-22-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@0.0.11 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@0.0.11 install script 'node installer/driverInstall.js'.
npm ERR! This is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /srv/v4/npm-debug.log
```

**Comment by bimalkjha** [comment]
@granteagon ibm_db@0.0.13 is the latest release which has fix for this issue: https://www.npmjs.com/package/ibm_db
Error shows you are installing ibm_db@0.0.11. So, the error is expected. Please install the latest one.
Also, if you still see version as 0.0.11, please remove older installed copies of ibm_db from you system and try. Thanks.

**Comment by granteagon** [comment]
This worked for me.  Thanks so much!
