### ISSUE TITLE
Failed to install the package on Windows 10 and MacOS 10.14

### ISSUE THREAD

**Issue by futura-by** [ibmdb/node-ibm_db#481]
Failed to install the package.
have the following error:

```
$ npm i ibm_db --save

> ibm_db@2.4.1 install C:\work\test\node_modules\ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip...

100.00% | 607 bytes downloaded out of 607 bytes.Unhandled rejection Error: invalid signature: 0x4f44213c
    at C:\work\test\node_modules\unzipper\lib\parse.js:57:26
    at tryCatcher (C:\work\test\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\work\test\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\work\test\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\work\test\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\work\test\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\work\test\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\work\test\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\work\test\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
npm WARN aaa@1.0.0 No description
npm WARN aaa@1.0.0 No repository field.

+ ibm_db@2.4.1
updated 1 package and audited 176 packages in 31.951s
found 0 vulnerabilities

```

The link to driver file (https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip) gives this:
![image](https://user-images.githubusercontent.com/1647673/48126766-18444f80-e293-11e8-8bc8-47d4d4e6248e.png)

**Comment by rhtpandeyIN** [comment]
I think the hosting URL was down because of server maintenance, you can try it again and if this issue is still there then please check your firewall settings or proxy configuration.

Thanks.

**Comment by futura-by** [comment]
Yes it is working now, feel free to close the ticket.

Thanks.
