### ISSUE TITLE
Yarn run test - Error: The specified module could not be found. ibm_db

### ISSUE THREAD

**Issue by mickmdmai** [ibmdb/node-ibm_db#484]
Hi guys! I am running "Yarn test run" for chai mocha framework and using "knex" framework. I am getting following error. Please give me a hint or clue so I can move forward with my testing. Thanks in advanced!

 Knex: run
$ npm install ibm_db --save
Error: The specified module could not be found.

\\?\C:\Users\MXM8UKB\OneDrive - \Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\ibm_db\build\Release\odbc_bindings.node
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at bindings (C:\Users\MXM8UKB\OneDrive - \Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\bindings\bindings.js:81:44)
    at Object.<anonymous> (C:\Users\MXM8UKB\OneDrive - \Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\ibm_db\lib\odbc.js:31:31)
    at Module._compile (module.js:570:32)
    at Module.replacementCompile (C:\Users\MXM8UKB\OneDrive - \Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\nyc\node_modules\append-transform\index.js:58:13)
    at module.exports (C:\Users\MXM8UKB\OneDrive - \Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\nyc\node_modules\default-require-extensions\js.js:8:9)
    at Object.<anonymous> (C:\Users\MXM8UKB\OneDrive - \Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\nyc\node_modules\append-transform\index.js:62:4)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Client_DB2._driver (C:\Users\MXM8UKB\OneDrive - \Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\thd-knex\lib\dialects\db2\index.js:105:12)
    at Client_DB2.initializeDriver (C:\Users\MXM8UKB\OneDrive - \Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\thd-knex\lib\client.js:219:26)
    at Client_DB2.Client (C:\Users\MXM8UKB\OneDrive - \Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\thd-knex\lib\client.js:113:10)
    at new Client_DB2 (C:\Users\MXM8UKB\OneDrive - \Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\thd-knex\lib\dialects\db2\index.js:62:20)
    at Knex (C:\Users\MXM8UKB\OneDrive - \Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\thd-knex\lib\index.js:61:34)
    at Object.<anonymous> (C:\Users\MXM8UKB\OneDrive - \Desktop\Paperless OnBoarding\Knex\document-collection-api\routes\assgHrOnbrdDoc.js:1:14314)
    at Module._compile (module.js:570:32)
    at Module.replacementCompile (C:\Users\MXM8UKB\OneDrive - \Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\nyc\node_modules\append-transform\index.js:58:13)
    at module.exports (C:\Users\MXM8UKB\OneDrive - \Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\nyc\node_modules\default-require-extensions\js.js:8:9)
    at Object.<anonymous> (C:\Users\MXM8UKB\OneDrive - \Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\nyc\node_modules\append-transform\index.js:62:4)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\MXM8UKB\OneDrive - \Desktop\Paperless OnBoarding\Knex\document-collection-api\app.js:1:6022)
    at Module._compile (module.js:570:32)
    at Module.replacementCompile (C:\Users\MXM8UKB\OneDrive - \Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\nyc\node_modules\append-transform\index.js:58:13)
    at module.exports (C:\Users\MXM8UKB\OneDrive - Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\nyc\node_modules\default-require-extensions\js.js:8:9)
    at Object.<anonymous> (C:\Users\MXM8UKB\OneDrive - Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\nyc\node_modules\append-transform\index.js:62:4)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\MXM8UKB\OneDrive - Desktop\Paperless OnBoarding\Knex\document-collection-api\test\assgHrOnbrdDoc_spec.js:5:14)
    at Module._compile (module.js:570:32)
    at Module.replacementCompile (C:\Users\MXM8UKB\OneDrive - Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\nyc\node_modules\append-transform\index.js:58:13)
    at module.exports (C:\Users\MXM8UKB\OneDrive - Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\nyc\node_modules\default-require-extensions\js.js:8:9)
    at Object.<anonymous> (C:\Users\MXM8UKB\OneDrive - Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\nyc\node_modules\append-transform\index.js:62:4)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at C:\Users\MXM8UKB\OneDrive - Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\mocha\lib\mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (C:\Users\MXM8UKB\OneDrive - Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\mocha\lib\mocha.js:217:14)
    at Mocha.run (C:\Users\MXM8UKB\OneDrive - Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\mocha\lib\mocha.js:469:10)
    at Object.<anonymous> (C:\Users\MXM8UKB\OneDrive - Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\mocha\bin\_mocha:404:18)
    at Module._compile (module.js:570:32)
    at Module.replacementCompile (C:\Users\MXM8UKB\OneDrive - Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\nyc\node_modules\append-transform\index.js:58:13)
    at module.exports (C:\Users\MXM8UKB\OneDrive - Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\nyc\node_modules\default-require-extensions\js.js:8:9)
    at Object.<anonymous> (C:\Users\MXM8UKB\OneDrive - Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\nyc\node_modules\append-transform\index.js:62:4)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
    at runMain (C:\Users\MXM8UKB\.node-spawn-wrap-12168-3a80c3ce68be\node:68:10)
    at Function.<anonymous> (C:\Users\MXM8UKB\.node-spawn-wrap-12168-3a80c3ce68be\node:171:5)
    at Object.<anonymous> (C:\Users\MXM8UKB\OneDrive - Desktop\Paperless OnBoarding\Knex\document-collection-api\node_modules\nyc\bin\wrap.js:23:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
    at C:\Users\MXM8UKB\.node-spawn-wrap-12168-3a80c3ce68be\node:178:8
    at Object.<anonymous> (C:\Users\MXM8UKB\.node-spawn-wrap-12168-3a80c3ce68be\node:181:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3

**Comment by bimalkjha** [comment]
@mickmdmai Are you able to install ibm_db independently outside knex framework and run test case? Please share your node version and npm version too. Thanks.

**Comment by mickmdmai** [comment]
Hi Bimal!

  Sorry for the late reply! Yes, I have been able to install ibm_db module,
but I am not able to run yarn test on Jenkins server.

**Comment by bimalkjha** [comment]
Better to post the query in Yarn or knex forum. They should be able to provide more info. Thanks.
