### ISSUE TITLE
Build error on 0.0.13

### ISSUE THREAD

**Issue by joshuarichard** [ibmdb/node-ibm_db#50]
Ran into this error this morning on local attempt to npm install ibm_db:

```
In file included from ../src/odbc.cpp:25:
../src/odbc.h:30:10: fatal error: 'sqlcli1.h' file not found
#include <sqlcli1.h>
         ^
1 error generated.
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IBM_DB_HOME=/Users/joshuarichard/node_modules/ibm_db/installer/clidriver" "--IBM_DB_HOME_WIN=%IBM_DB_HOME%" "--IS_DOWNLOADED=true"
gyp ERR! cwd /Users/joshuarichard/node_modules/ibm_db
gyp ERR! node -v v0.12.5
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c node-gyp configure build --IBM_DB_HOME=$IBM_DB_HOME --IBM_DB_HOME_WIN=%IBM_DB_HOME% --IS_DOWNLOADED=true' }
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "ibm_db"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@0.0.13 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@0.0.13 install script 'node installer/driverInstall.js'.
npm ERR! This is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.
```

**Comment by mtp401** [comment]
Fixed in [PR #51](https://github.com/ibmdb/node-ibm_db/pull/51). The tar.gz npm package was updated ~15 hours ago and breaks install on Mac OS X

**Comment by random6886** [comment]
Do you know when the 0.0.14 will be released with this fix?

**Comment by bimalkjha** [comment]
@joshuarichard and @random6886 : Please verify now and close the ticket. Thanks.

**Comment by nsharmon** [comment]
Same problem happening with 0.0.14 release.  :frowning:

**Comment by bimalkjha** [comment]
@nsharmon You mentioned same problem happening with latest release. Please let us know the platform and full output of "nom install ibm_db" command. Thanks.
