### ISSUE TITLE
Fail to install in ubuntu

### ISSUE THREAD

**Issue by WandyLau** [ibmdb/node-ibm_db#502]
OS: Ubutun 16.04 x86_64
node: 11.4.0
npm: 6.4.1.

error messages:

```info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/root/nodeapp/node-ibm_db/build'
  g++ '-DNODE_GYP_MODULE_NAME=odbc_bindings' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/root/.node-gyp/11.4.0/include/node -I/root/.node-gyp/11.4.0/src -I/root/.node-gyp/11.4.0/deps/openssl/config -I/root/.node-gyp/11.4.0/deps/openssl/openssl/include -I/root/.node-gyp/11.4.0/deps/uv/include -I/root/.node-gyp/11.4.0/deps/zlib -I/root/.node-gyp/11.4.0/deps/v8/include -I../node_modules/nan -I/root/clidriver/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -g -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -MMD -MF ./Release/.deps/Release/obj.target/odbc_bindings/src/odbc.o.d.raw   -c -o Release/obj.target/odbc_bindings/src/odbc.o ../src/odbc.cpp
In file included from ../src/odbc.cpp:28:0:
../src/odbc.h:27:10: fatal error: sqlcli1.h: No such file or directory
 #include <sqlcli1.h>
          ^~~~~~~~~~~
compilation terminated.
odbc_bindings.target.mk:108: recipe for target 'Release/obj.target/odbc_bindings/src/odbc.o' failed
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
make: Leaving directory '/root/nodeapp/node-ibm_db/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.15.0-38-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure" "build" "--IBM_DB_HOME=/root/clidriver" "--IS_DOWNLOADED=false" "--verbose"
gyp ERR! cwd /root/nodeapp/node-ibm_db
gyp ERR! node -v v11.4.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok ```

**Comment by WandyLau** [comment]
Do I miss any dependencies?
