### ISSUE TITLE
doesn't work with Worker Threads

### ISSUE THREAD

**Issue by PavelPolyakov** [ibmdb/node-ibm_db#517]
It is not possible to use nodejs worker threads with this module.

Node.js supports `Worker Threads` as experimental feature:
https://nodejs.org/docs/latest-v10.x/api/worker_threads.html

However, it's not possible to launch them if you're requiring `ibm_db`.

Here is an example:
```js
const {
  Worker,
  MessageChannel,
  MessagePort,
  isMainThread,
  parentPort,
  workerData
} = require("worker_threads");


const ibmdb = require("ibm_db");

if (isMainThread) {

    const worker = new Worker(__filename, {
      workerData: {
        data: 'data'
      }
    });

    worker.on("exit", code => {
      if (code !== 0) throw new Error(`Worker stopped with exit code ${code}`);
      console.log('hello');

    });
} else {
  const { data } = workerData;
  process.exit();
}
```

(if you run `nodejs v10` you'd need to pass a flag `--experimental-worker`)

This results into the error:
```
Error: Module did not self-register.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at bindings (/Users/pp/Projects/db2-hashed-export/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/pp/Projects/db2-hashed-export/node_modules/ibm_db/lib/odbc.js:31:31)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

if you comment out the library requirement - everything is going to run fine.

**Comment by PriyankaManoharan04** [comment]
@PavelPolyakov We have just delivered the fix of this issue. You can clone the code from master branch, install it using `npm install` command and test your example. This fix will be part of next release of ibm_db. Closing the issue as of now. Thanks

**Comment by PavelPolyakov** [comment]
Thanks for the quick fix!
