### ISSUE TITLE
issue installing ibm_db (even upgraded xcode and command line tool)

### ISSUE THREAD

**Issue by chiaki1770** [ibmdb/node-ibm_db#519]
Hi, I've been trying to npm install ibm_db for a lot of attempts. The error I'm getting is:
```IBM_DB_HOME environment variable have already been set to -> /Users/{XXXSorry It's my name the path is correct}/Downloads/clidriver

Downloading of clidriver skipped - build is in progress...

  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME="$IBM_DB_HOME"
../src/odbc.cpp:210:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    data->cb->Call(1, info);
              ^
../../nan/nan.h:1673:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:103:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/odbc.cpp:222:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    data->cb->Call(2, info);
```

My node version is v11.13.0 (I tried 8.12.0 however no luck)
My npm version is 6.7.0
My Mac OS version is 10.14.4
My gcc version is: 
```configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.3)
Target: x86_64-apple-darwin18.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

my node-gyp version is 3.8.0

NOTE: if I don't set $IBM_DB_HOME and npm install download the clidriver, it still failed.

Need some help. Thanks a lot!!!

**Comment by PriyankaManoharan04** [comment]
@chiaki1770 Can you provide the complete output/Error of npm install ibm_db.Thanks

**Comment by chiaki1770** [comment]
@PriyankaManoharan04 Hello, pls see below:
```
> ibm_db@2.5.0 install /Users/Me/Documents/OCR/SmartPages-Cloud-Backend/x-ray/node_modules/ibm_db
> node installer/driverInstall.js

IBM_DB_HOME environment variable have already been set to -> /Users/Me/Downloads/clidriver

Downloading of clidriver skipped - build is in progress...

  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME="$IBM_DB_HOME"
../src/odbc.cpp:210:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    data->cb->Call(1, info);
              ^
../../nan/nan.h:1673:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:103:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/odbc.cpp:222:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    data->cb->Call(2, info);
              ^
../../nan/nan.h:1673:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:103:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/odbc.cpp:495:21: error: variable has incomplete type 'struct tm'
          struct tm timeInfo = {0,0,0,0,0,0,0,0,0,0,0};
                    ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/wchar.h:131:19: note: forward declaration of 'tm'
            const struct tm * __restrict) __DARWIN_ALIAS(wcsftime);
                         ^
../src/odbc.cpp:670:59: warning: format specifies type 'int' but the argument has type 'long' [-Wformat]
                  ", columnType = %i, index = %i\n", ret, (long)(hStmt) >> 16 & 0x0000ffff, 
                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/odbc.cpp:671:19: warning: format specifies type 'int' but the argument has type 'long' [-Wformat]
                  (long)(hStmt) & 0x0000ffff, (int) column.type, column.index);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/odbc.cpp:912:38: warning: 'IntegerValue' is deprecated: Use maybe version [-Wdeprecated-declarations]
          params[i].paramtype = val->IntegerValue();
                                     ^
/Users/Me/.node-gyp/11.13.0/include/node/v8.h:2570:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/Me/.node-gyp/11.13.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/odbc.cpp:916:35: warning: 'IntegerValue' is deprecated: Use maybe version [-Wdeprecated-declarations]
          params[i].c_type = val->IntegerValue();
                                  ^
/Users/Me/.node-gyp/11.13.0/include/node/v8.h:2570:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/Me/.node-gyp/11.13.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/odbc.cpp:922:33: warning: 'IntegerValue' is deprecated: Use maybe version [-Wdeprecated-declarations]
          params[i].type = val->IntegerValue();
                                ^
/Users/Me/.node-gyp/11.13.0/include/node/v8.h:2570:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/Me/.node-gyp/11.13.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/odbc.cpp:930:46: warning: 'IntegerValue' is deprecated: Use maybe version [-Wdeprecated-declarations]
              params[i].buffer_length = val->IntegerValue();
                                             ^
/Users/Me/.node-gyp/11.13.0/include/node/v8.h:2570:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/Me/.node-gyp/11.13.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/odbc.cpp:972:35: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
    Local<String> string = value->ToString();
                                  ^
/Users/Me/.node-gyp/11.13.0/include/node/v8.h:2548:10: note: 'ToString' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<String> ToString() const);
         ^
/Users/Me/.node-gyp/11.13.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/odbc.cpp:988:27: warning: 'Utf8Length' is deprecated: Use Isolate version instead [-Wdeprecated-declarations]
        bufflen = string->Utf8Length() + 1;
                          ^
/Users/Me/.node-gyp/11.13.0/include/node/v8.h:2682:3: note: 'Utf8Length' has been explicitly marked deprecated here
  V8_DEPRECATED("Use Isolate version instead", int Utf8Length() const);
  ^
/Users/Me/.node-gyp/11.13.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/odbc.cpp:1008:17: warning: 'WriteUtf8' is deprecated: Use Isolate* version [-Wdeprecated-declarations]
        string->WriteUtf8((char *) param->buffer);
                ^
/Users/Me/.node-gyp/11.13.0/include/node/v8.h:2753:3: note: 'WriteUtf8' has been explicitly marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/Me/.node-gyp/11.13.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/odbc.cpp:1015:17: warning: 'WriteOneByte' is deprecated: Use Isolate* version [-Wdeprecated-declarations]
        string->WriteOneByte((uint8_t *)param->buffer);
                ^
/Users/Me/.node-gyp/11.13.0/include/node/v8.h:2746:3: note: 'WriteOneByte' has been explicitly marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/Me/.node-gyp/11.13.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/odbc.cpp:1023:17: warning: 'WriteUtf8' is deprecated: Use Isolate* version [-Wdeprecated-declarations]
        string->WriteUtf8((char *) param->buffer);
                ^
/Users/Me/.node-gyp/11.13.0/include/node/v8.h:2753:3: note: 'WriteUtf8' has been explicitly marked deprecated here
  V8_DEPRECATED("Use Isolate* version",
  ^
/Users/Me/.node-gyp/11.13.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/odbc.cpp:1066:43: warning: 'IntegerValue' is deprecated: Use maybe version [-Wdeprecated-declarations]
    int64_t  *number = new int64_t(value->IntegerValue());
                                          ^
/Users/Me/.node-gyp/11.13.0/include/node/v8.h:2570:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/Me/.node-gyp/11.13.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/odbc.cpp:1082:42: warning: 'NumberValue' is deprecated: Use maybe version [-Wdeprecated-declarations]
    double *number   = new double(value->NumberValue());
                                         ^
/Users/Me/.node-gyp/11.13.0/include/node/v8.h:2569:3: note: 'NumberValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", double NumberValue() const);
  ^
/Users/Me/.node-gyp/11.13.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/odbc.cpp:1103:40: warning: 'BooleanValue' is deprecated: Use maybe version [-Wdeprecated-declarations]
    bool *boolean    = new bool(value->BooleanValue());
                                       ^
/Users/Me/.node-gyp/11.13.0/include/node/v8.h:2568:3: note: 'BooleanValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", bool BooleanValue() const);
  ^
/Users/Me/.node-gyp/11.13.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/odbc.cpp:1194:7: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  cb->Call(1, info);
      ^
../../nan/nan.h:1673:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:103:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
17 warnings and 1 error generated.
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=false" "--IBM_DB_HOME=/Users/Me/Downloads/clidriver"
gyp ERR! cwd /Users/Me/Documents/OCR/SmartPages-Cloud-Backend/x-ray/node_modules/ibm_db
gyp ERR! node -v v11.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

    at ChildProcess.exithandler (child_process.js:297:12)
    at ChildProcess.emit (events.js:193:13)
    at maybeClose (internal/child_process.js:1001:16)
    at Socket.stream.socket.on (internal/child_process.js:405:11)
    at Socket.emit (events.js:193:13)
    at Pipe._handle.close (net.js:614:12)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node-gyp configure build  --IS_DOWNLOADED=false --IBM_DB_HOME="$IBM_DB_HOME"' }
npm WARN BACA@1.0.0 No repository field.
npm WARN BACA@1.0.0 No license field.
npm WARN The package proxyquire is included as both a dev and production dependency.
npm WARN The package sinon is included as both a dev and production dependency.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.5.0 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@2.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Me/.npm/_logs/2019-04-01T12_31_30_906Z-debug.log
```

**Comment by PriyankaManoharan04** [comment]
@chiaki1770 can you share your xcode-select version.Thanks

**Comment by chiaki1770** [comment]
@PriyankaManoharan04 Hi, my xcode-select version is 2354.

**Comment by PriyankaManoharan04** [comment]
@chiaki1770 can you switch to version 2349 and check can you able to install ibm_db.Thanks

**Comment by chiaki1770** [comment]
<img width="417" alt="Screen Shot 2019-04-02 at 2 41 49 PM" src="https://user-images.githubusercontent.com/39866552/55424355-76314680-5556-11e9-8a86-7c99c99b8c1b.png">
Hi @PriyankaManoharan04, I downloaded xcode10.1, xcode10 and xcode9.4.1. However under these versions, I still got xcode-select version 2349. Any thoughts on how to switch to version 2349? Thanks.

**Comment by chiaki1770** [comment]
@PriyankaManoharan04 My coworker used 2354 and can install.. any thoughts?

**Comment by PriyankaManoharan04** [comment]
@chiaki1770 Your installation is failing due to below compilation error:
```
../src/odbc.cpp:495:21: error: variable has incomplete type 'struct tm'
          struct tm timeInfo = {0,0,0,0,0,0,0,0,0,0,0};
```
It says the `struct tm` do not have 11 members in your system. Normally it should have. Please check your `time.h` file. It should be under /usr/include dir. If not found, look at other place. The no of members in `struct tm` in your time.h file should be 11. If it is not, please use correct time.h.
Thanks.

**Comment by chiaki1770** [comment]
@PriyankaManoharan04 Hi..my struct tm seemed correct..
```
#ifndef _TIME_H_
#define	_TIME_H_

#include <_types.h>
#include <Availability.h>
#include <sys/_types/_clock_t.h>
#include <sys/_types/_null.h>
#include <sys/_types/_size_t.h>
#include <sys/_types/_time_t.h>
#include <sys/_types/_timespec.h>

struct tm {
	int	tm_sec;		/* seconds after the minute [0-60] */
	int	tm_min;		/* minutes after the hour [0-59] */
	int	tm_hour;	/* hours since midnight [0-23] */
	int	tm_mday;	/* day of the month [1-31] */
	int	tm_mon;		/* months since January [0-11] */
	int	tm_year;	/* years since 1900 */
	int	tm_wday;	/* days since Sunday [0-6] */
	int	tm_yday;	/* days since January 1 [0-365] */
	int	tm_isdst;	/* Daylight Savings Time flag */
	long	tm_gmtoff;	/* offset from UTC in seconds */
	char	*tm_zone;	/* timezone abbreviation */
};

#if __DARWIN_UNIX03
#define CLOCKS_PER_SEC  1000000	/* [XSI] */
#else /* !__DARWIN_UNIX03 */
#include <machine/_limits.h>	/* Include file containing CLK_TCK. */

#define CLOCKS_PER_SEC  (__DARWIN_CLK_TCK)
#endif /* __DARWIN_UNIX03 */

#ifndef _ANSI_SOURCE
extern char *tzname[];
#endif

extern int getdate_err;
#if __DARWIN_UNIX03
extern long timezone __DARWIN_ALIAS(timezone);
#endif /* __DARWIN_UNIX03 */
extern int daylight;

__BEGIN_DECLS
char *asctime(const struct tm *);
clock_t clock(void) __DARWIN_ALIAS(clock);
char *ctime(const time_t *);
double difftime(time_t, time_t);
struct tm *getdate(const char *);
struct tm *gmtime(const time_t *);
struct tm *localtime(const time_t *);
time_t mktime(struct tm *) __DARWIN_ALIAS(mktime);
size_t strftime(char * __restrict, size_t, const char * __restrict, const struct tm * __restrict) __DARWIN_ALIAS(strftime);
char *strptime(const char * __restrict, const char * __restrict, struct tm * __restrict) __DARWIN_ALIAS(strptime);
time_t time(time_t *);

#ifndef _ANSI_SOURCE
void tzset(void);
#endif /* not ANSI */

/* [TSF] Thread safe functions */
char *asctime_r(const struct tm * __restrict, char * __restrict);
char *ctime_r(const time_t *, char *);
struct tm *gmtime_r(const time_t * __restrict, struct tm * __restrict);
struct tm *localtime_r(const time_t * __restrict, struct tm * __restrict);

#if !defined(_ANSI_SOURCE) && (!defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE))
time_t posix2time(time_t);
#if !__DARWIN_UNIX03
char *timezone(int, int);
#endif /* !__DARWIN_UNIX03 */
void tzsetwall(void);
time_t time2posix(time_t);
time_t timelocal(struct tm * const);
time_t timegm(struct tm * const);
#endif /* neither ANSI nor POSIX */

#if !defined(_ANSI_SOURCE)
int nanosleep(const struct timespec *__rqtp, struct timespec *__rmtp) __DARWIN_ALIAS_C(nanosleep);
#endif

#if !defined(_DARWIN_FEATURE_CLOCK_GETTIME) || _DARWIN_FEATURE_CLOCK_GETTIME != 0
#if __DARWIN_C_LEVEL >= 199309L
#if __has_feature(enumerator_attributes)
#define __CLOCK_AVAILABILITY __OSX_AVAILABLE(10.12) __IOS_AVAILABLE(10.0) __TVOS_AVAILABLE(10.0) __WATCHOS_AVAILABLE(3.0)
#else
#define __CLOCK_AVAILABILITY
#endif

typedef enum {
_CLOCK_REALTIME __CLOCK_AVAILABILITY = 0,
#define CLOCK_REALTIME _CLOCK_REALTIME
_CLOCK_MONOTONIC __CLOCK_AVAILABILITY = 6,
#define CLOCK_MONOTONIC _CLOCK_MONOTONIC
#if !defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE)
_CLOCK_MONOTONIC_RAW __CLOCK_AVAILABILITY = 4,
#define CLOCK_MONOTONIC_RAW _CLOCK_MONOTONIC_RAW
_CLOCK_MONOTONIC_RAW_APPROX __CLOCK_AVAILABILITY = 5,
#define CLOCK_MONOTONIC_RAW_APPROX _CLOCK_MONOTONIC_RAW_APPROX
_CLOCK_UPTIME_RAW __CLOCK_AVAILABILITY = 8,
#define CLOCK_UPTIME_RAW _CLOCK_UPTIME_RAW
_CLOCK_UPTIME_RAW_APPROX __CLOCK_AVAILABILITY = 9,
#define CLOCK_UPTIME_RAW_APPROX _CLOCK_UPTIME_RAW_APPROX
#endif
_CLOCK_PROCESS_CPUTIME_ID __CLOCK_AVAILABILITY = 12,
#define CLOCK_PROCESS_CPUTIME_ID _CLOCK_PROCESS_CPUTIME_ID
_CLOCK_THREAD_CPUTIME_ID __CLOCK_AVAILABILITY = 16
#define CLOCK_THREAD_CPUTIME_ID _CLOCK_THREAD_CPUTIME_ID
} clockid_t;

__CLOCK_AVAILABILITY
int clock_getres(clockid_t __clock_id, struct timespec *__res);

__CLOCK_AVAILABILITY
int clock_gettime(clockid_t __clock_id, struct timespec *__tp);

#if !defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE)
__CLOCK_AVAILABILITY
__uint64_t clock_gettime_nsec_np(clockid_t __clock_id);
#endif

__OSX_AVAILABLE(10.12) __IOS_PROHIBITED
__TVOS_PROHIBITED __WATCHOS_PROHIBITED
int clock_settime(clockid_t __clock_id, const struct timespec *__tp);

#undef __CLOCK_AVAILABILITY
#endif /* __DARWIN_C_LEVEL */
#endif /* _DARWIN_FEATURE_CLOCK_GETTIME */

__END_DECLS

#ifdef _USE_EXTENDED_LOCALES_
#include <xlocale/_time.h>
#endif /* _USE_EXTENDED_LOCALES_ */

#endif /* !_TIME_H_ */
```

**Comment by PriyankaManoharan04** [comment]
@chiaki1770 can you share time.h under this path /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include

**Comment by PriyankaManoharan04** [comment]
@chiaki1770 You are getting this error because you system is picking up some other `time.h` file which does not have 11 members in it.So please check for `time.h` in some other folder and if it exists remove it.For example you can check if `/usr/local/include/time.h` exists on your system, remove it if it exists.Thanks

**Comment by chiaki1770** [comment]
it worked!!!! @PriyankaManoharan04 Thank you so much!!!!
