### ISSUE TITLE
0.0.13 build error on bluemix

### ISSUE THREAD

**Issue by jzjsuper** [ibmdb/node-ibm_db#52]
I build a bluemix web app using `Internet of Things Foundation Starter` boilerplate and the following build error occurs.
```
-----> Downloaded app package (108K)

-----> IBM SDK for Node.js Buildpack v2.3-20150720-1448
       Based on Cloud Foundry Node.js Buildpack v64
-----> Reading application state
       package.json...
       build directory...
       cache directory...
       environment variables...
       Node engine range:   0.10.x
       Npm engine:          unspecified
       Start mechanism:     none
       node_modules source: package.json
       node_modules cached: false
       NPM_CONFIG_PRODUCTION=true
       NODE_MODULES_CACHE=true
-----> Installing binaries
       Resolving node version 0.10.x via 'node-version-resolver'
       Installing IBM SDK for Node.js (0.10.40) from cache
       Using default npm version: 1.4.28
-----> Checking and configuring service extensions before installing dependencies
jq: error: Cannot iterate over null
jq: error: Cannot iterate over null
jq: error: Cannot iterate over null
jq: error: Cannot iterate over null
jq: error: Cannot iterate over null
jq: error: Cannot iterate over null
jq: error: Cannot iterate over null
jq: error: Cannot iterate over null
jq: error: Cannot iterate over null
jq: error: Cannot iterate over null
jq: error: Cannot iterate over null
jq: error: Cannot iterate over null
jq: error: Cannot iterate over null
jq: error: Cannot iterate over null
jq: error: Cannot iterate over null
jq: error: Cannot iterate over null
-----> Building dependencies
       Installing node modules
       npm WARN package.json iot-bluemix@0.4.19 No repository field.
       > typechecker@2.0.8 preinstall /tmp/staged/app/node_modules/getmac/node_modules/extract-opts/node_modules/typechecker
       > node ./cyclic.js
       > kerberos@0.0.11 install /tmp/staged/app/node_modules/mongodb/node_modules/kerberos
       > (node-gyp rebuild 2> builderror.log) || (exit 0)
       make: Entering directory `/tmp/staged/app/node_modules/mongodb/node_modules/kerberos/build'
         CXX(target) Release/obj.target/kerberos/lib/kerberos.o
         CXX(target) Release/obj.target/kerberos/lib/worker.o
         CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
         CC(target) Release/obj.target/kerberos/lib/base64.o
         CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
         SOLINK_MODULE(target) Release/obj.target/kerberos.node
         SOLINK_MODULE(target) Release/obj.target/kerberos.node: Finished
         COPY Release/kerberos.node
       make: Leaving directory `/tmp/staged/app/node_modules/mongodb/node_modules/kerberos/build'
       > bson@0.2.22 install /tmp/staged/app/node_modules/mongodb/node_modules/bson
       > (node-gyp rebuild 2> builderror.log) || (exit 0)
       make: Entering directory `/tmp/staged/app/node_modules/mongodb/node_modules/bson/build'
         CXX(target) Release/obj.target/bson/ext/bson.o
         SOLINK_MODULE(target) Release/obj.target/bson.node
         SOLINK_MODULE(target) Release/obj.target/bson.node: Finished
         COPY Release/bson.node
       make: Leaving directory `/tmp/staged/app/node_modules/mongodb/node_modules/bson/build'
       > ibm_db@0.0.13 install /tmp/staged/app/node_modules/node-red-nodes-cf-sqldb-dashdb/node_modules/ibm_db
       > node installer/driverInstall.js
       Downloading DB2 ODBC CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz...
       Download and extraction of DB2 ODBC CLI Driver completed successfully ...
       make: Entering directory `/tmp/staged/app/node_modules/node-red-nodes-cf-sqldb-dashdb/node_modules/ibm_db/build'
         CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
         CXX(target) Release/obj.target/odbc_bindings/src/odbc_connection.o
         CXX(target) Release/obj.target/odbc_bindings/src/odbc_statement.o
         CXX(target) Release/obj.target/odbc_bindings/src/odbc_result.o
         CXX(target) Release/obj.target/odbc_bindings/src/dynodbc.o
         SOLINK_MODULE(target) Release/obj.target/odbc_bindings.node
       make: Leaving directory `/tmp/staged/app/node_modules/node-red-nodes-cf-sqldb-dashdb/node_modules/ibm_db/build'
       { [Error: Command failed: /usr/bin/ld: cannot find -ldb2
       collect2: ld returned 1 exit status
       make: *** [Release/obj.target/odbc_bindings.node] Error 1
       gyp ERR! build error 
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:268:23)
       gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
       gyp ERR! System Linux 3.13.0-39-generic
       gyp ERR! command "node" "/tmp/staged/app/vendor/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IBM_DB_HOME=/tmp/staged/app/node_modules/node-red-nodes-cf-sqldb-dashdb/node_modules/ibm_db/installer/clidriver" "--IBM_DB_HOME_WIN=%IBM_DB_HOME%" "--IS_DOWNLOADED=true"
       gyp ERR! cwd /tmp/staged/app/node_modules/node-red-nodes-cf-sqldb-dashdb/node_modules/ibm_db
       gyp ERR! node -v v0.10.40
       gyp ERR! node-gyp -v v1.0.1
       gyp ERR! not ok 
       ] killed: false, code: 1, signal: null }
       > bcrypt@0.8.3 install /tmp/staged/app/node_modules/node-red/node_modules/bcrypt
       > node-gyp rebuild
       make: Entering directory `/tmp/staged/app/node_modules/node-red/node_modules/bcrypt/build'
         CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
         CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
         CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
         SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node
         SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node: Finished
         COPY Release/bcrypt_lib.node
       make: Leaving directory `/tmp/staged/app/node_modules/node-red/node_modules/bcrypt/build'
       > bufferutil@1.1.0 install /tmp/staged/app/node_modules/node-red/node_modules/ws/node_modules/bufferutil
       > node-gyp rebuild
       make: Entering directory `/tmp/staged/app/node_modules/node-red/node_modules/ws/node_modules/bufferutil/build'
         CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
         SOLINK_MODULE(target) Release/obj.target/bufferutil.node
         SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
         COPY Release/bufferutil.node
       make: Leaving directory `/tmp/staged/app/node_modules/node-red/node_modules/ws/node_modules/bufferutil/build'
       > utf-8-validate@1.1.0 install /tmp/staged/app/node_modules/node-red/node_modules/ws/node_modules/utf-8-validate
       > node-gyp rebuild
       make: Entering directory `/tmp/staged/app/node_modules/node-red/node_modules/ws/node_modules/utf-8-validate/build'
         CXX(target) Release/obj.target/validation/src/validation.o
         SOLINK_MODULE(target) Release/obj.target/validation.node
         SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
         COPY Release/validation.node
       make: Leaving directory `/tmp/staged/app/node_modules/node-red/node_modules/ws/node_modules/utf-8-validate/build'
       > serialport@1.7.4 install /tmp/staged/app/node_modules/node-red/node_modules/node-red-node-serialport/node_modules/serialport
       > node-pre-gyp install --fallback-to-build
       [serialport] Success: "/tmp/staged/app/node_modules/node-red/node_modules/node-red-node-serialport/node_modules/serialport/build/serialport/v1.7.4/Release/node-v11-linux-x64/serialport.node" is installed via remote
       npm ERR! ibm_db@0.0.13 install: `node installer/driverInstall.js`
       npm ERR! Exit status 1
       npm ERR! 
       npm ERR! Failed at the ibm_db@0.0.13 install script.
       npm ERR! This is most likely a problem with the ibm_db package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     node installer/driverInstall.js
       npm ERR! You can get their info via:
       npm ERR!     npm owner ls ibm_db
       npm ERR! There is likely additional logging output above.
       npm ERR! System Linux 3.13.0-39-generic
       npm ERR! command "/tmp/staged/app/vendor/node/bin/node" "/tmp/staged/app/vendor/node/bin/npm" "install" "--unsafe-perm" "--quiet" "--userconfig" "/tmp/staged/app/.npmrc"
       npm ERR! cwd /tmp/staged/app
       npm ERR! node -v v0.10.40
       npm ERR! npm -v 1.4.28
       npm ERR! code ELIFECYCLE

FAILED
Server error, status code: 400, error code: 170004, message: App staging failed in the buildpack compile phase

```

**Comment by slaupster** [comment]
also affects me.

**Comment by Quattrone** [comment]
Also me. Do you have any clue on that ?

**Comment by jzjsuper** [comment]
It's fixed in 0.0.14

**Comment by bimalkjha** [comment]
@jzjsuper could you please share the link for this Internet of Things Foundation Starter boilerplate. Also, would like to know how ibm_db get used here. Thanks.

**Comment by bimalkjha** [comment]
@jzjsuper you can mail me at bimaljha@in.ibm.com

**Comment by jzjsuper** [comment]
@bimalkjha You can find it by:
1. Register / Log in IBM Bluemix
2. Go to dashboard
3. Click  `CREATE APP`
4. Click `WEB`
5. Click `Browse Boilerplates`
6. Choose `Internet of Things Foundation Starter`
