### ISSUE TITLE
Error in installing ibm_db

### ISSUE THREAD

**Issue by apalek94** [ibmdb/node-ibm_db#520]
Hello all,
         Currently i am working on nodejs. My O.S. & nodejs details are--->
O.S.--> Windows 10, X64
Nodejs --> 11.11.0
node-gyp--> 3.3.1
I have to run one piece of code from github., but getting error.Here i will mention 2 errors-->
1) By running "npm start" 
2) By running "npm install ibm_db"

1st error by running"npm start"----------------------------------------->
Error: The specified procedure could not be found.
\\?\C:\RTC_Code\rtc\node_modules\ibm_db\build\Release\odbc_bindings.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:840:18)
    at Module.load (C:\RTC_Code\rtc\node_modules\coffee-script\lib\coffee-scrip\register.js:45:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at bindings (C:\RTC_Code\rtc\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\RTC_Code\rtc\node_modules\ibm_db\lib\odbc.js:31:31)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (C:\RTC_Code\rtc\node_modules\coffee-script\lib\coffee-scrip\register.js:45:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (C:\RTC_Code\rtc\routes\bl\scope.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (C:\RTC_Code\rtc\node_modules\coffee-script\lib\coffee-scrip\register.js:45:36)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (C:\RTC_Code\rtc\routes\ui\rtc.js:18:10)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (C:\RTC_Code\rtc\app.js:11:23)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (C:\RTC_Code\rtc\bin\www:7:11)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scheduler@0.8.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scheduler@0.8.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\AnkitaPalekar\AppData\Roaming\npm-cache\_logs\2019-04-01T17_54_47_807Z-debug.log
 
2nd error when i run "npm install ibm_db"---------------------------------------------------->
{ Error: Command failed: msbuild /clp:Verbosity=minimal /nologo /p:Configuration=Release;Platform=x64 "C:\RTC_Code\rtc\node_modules\ibm_db\build\binding.sln"
'msbuild' is not recognized as an internal or external command,
operable program or batch file.

    at ChildProcess.exithandler (child_process.js:297:12)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:984:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'msbuild /clp:Verbosity=minimal /nologo /p:Configuration=Release;Platform=x64 "C:\\RTC_Code\\rtc\\node_modules\\ibm_db\\build\\binding.sln"' }

msbuild build process failed!

Proceeding with Pre-compiled Binary Installation.

===================================
node-ibm_db installed successfully!

At last it is showing that "node-ibm_db installed successfully!" but I am not getting then why it was showing error when i start the server by giving command "npm start".

Can anyone please help me to resolve this issue..?

**Comment by PriyankaManoharan04** [comment]
@apalek94 Can you please check for the file in this path 'node_modules\ibm_db\build\Release\odbc_bindings.node' under ibm_db.

node-ibm_db installed successfully! message implies that ibm_db has been installed successfully.
under the test folder update your connection string in config.testConnectionStrings.json file and run 'node test-basic-test.js' and if you can able to get the output then there is no problem with ibm_db installation process. Thanks

**Comment by apalek94** [comment]
@PriyankaManoharan04 ..Yes odbc_binding.node is present there in the path which you have mentioned..

**Comment by apalek94** [comment]
@PriyankaManoharan04 ..I have updated config.testConnectionStrings.json file and run 'node test-basic-test.js' but still got the same error--------->

Error: The specified procedure could not be found.
\\?\C:\Users\AnkitaPalekar\eclipse-workspace\NodeJS+DB2\FirstApp\node_modules\ibm_db\build\Release\odbc_bindings.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:840:18)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at bindings (C:\Users\AnkitaPalekar\eclipse-workspace\NodeJS+DB2\FirstApp\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Users\AnkitaPalekar\eclipse-workspace\NodeJS+DB2\FirstApp\node_modules\ibm_db\lib\odbc.js:31:31)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)

**Comment by PriyankaManoharan04** [comment]
@apalek94 Can you try exactly below steps on new command prompt window and share the result:
```
cd \
mkdir nodeapp
cd nodeapp
npm install ibm_db
cd node_modules\ibm_db\test
node test-basic-test.js
```
Also, you can update the connection string in `ibm_db\installer\testODBCConnection.bat` file and execute it to test the basic connectivity. If that work, then set the env var PATH and LIB as in `testODBCConnection.bat` and then try `node test-basic-test.js`. You can also comment the `db2cli` command in `testODBCConnection.bat` and write `node test-basic-test.js` there and execute to fix any env related issue. Thanks.

**Comment by PriyankaManoharan04** [comment]
Other option is you can degrade your node.js version to v10.x and try. It is working for me with node v11.11.0.
Also, to avoid use of precompiled binary, you can search for 'msbuild.exe' in your system as the error in first post is `msbuild build process failed!`. Add the bin folder of msbuild.exe to PATH env var and install ibm-db using new command prompt. Thanks.

**Comment by apalek94** [comment]
@PriyankaManoharan04  i have updated db credentials in testODBCConnection.bat  & set PATH & LIB variables is as follows,(after running this .bat file in cmd i am getting error which i have pasted below)-->
@ECHO OFF
if "%IBM_DB_HOME%" == "" (SET IBM_DB_HOME=%cd%\clidriver)
SET PATH=%IBM_DB_HOME%\bin;%IBM_DB_HOME%\adm;%IBM_DB_HOME%\lib;%PATH%
SET LIB=%IBM_DB_HOME%\lib;%LIB%
DEL /F 1.trc 1.flw 1.fmt 1.fmtc 1.cli
db2trc on -t -f 1.trc
db2cli validate -database "scopedb:10.***.**.***:" -connect -user ***** -passwd *****
:: You can use either above db2cli command or below node command to run .js file.
:: Keep only one and comment other. Better to use above validate command first.
 

Error------------------------------------------------------------------------------------------------------------>
Trace is turned on
===============================================================================
Error: db2cli sees an invalid option.
Run "db2cli -help" for a valid syntax.
===============================================================================
The filename, directory name, or volume label syntax is incorrect.
Trace is turned off
Total number of trace records     : 5860
Trace truncated                   : NO
Trace wrapped                     : NO
Number of trace records formatted : 12 (pid: 888 tid 16112 node: -1)
Number of trace records formatted : 5485 (pid: 15516 tid 14760 node: -1)
Number of trace records formatted : 131 (pid: 1376 tid 6196 node: -1)
Trace truncated                   : NO
Trace wrapped                     : NO
Total number of trace records     : 5860
Number of trace records formatted : 5628
Trace truncated                   : NO
Trace wrapped                     : NO
Total number of trace records     : 5860
Number of trace records formatted : 0
Trace truncated                   : NO
Trace wrapped                     : NO
Total number of trace records     : 5860
Number of trace records formatted : 232

**Comment by apalek94** [comment]
Tried last option also by using nodejs lower verion 10.15.3 & in path env variable added path upto bin folder of msbuild.exe, but got this error & tried npm install ibm_db in new direcorty but getting following error--->

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME=$IBM_DB_HOME
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\AnkitaPalekar\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\AnkitaPalekar\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=$IBM_DB_HOME"
gyp ERR! cwd C:\Users\AnkitaPalekar\nodeapp\node_modules\ibm_db
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME=$IBM_DB_HOME' }

node-gyp build process failed!

Proceeding with Pre-compiled Binary Installation.


===================================
node-ibm_db installed successfully!

**Comment by PriyankaManoharan04** [comment]
@apalek94 Now Can you update your connection string and run 'node test-basic-test.js' and check can you able to run that file.Thanks

**Comment by apalek94** [comment]
@PriyankaManoharan04 ..I have updated connection string in config.testConnectionStrings.json & run 'node test-basic-test.js' but still got the same error also updated in testODBCConnection.bat & run both files 'node test-basic-test.js & 'node run tests.js' again got the same error.

Error: The specified procedure could not be found.
\\?\C:\Users\AnkitaPalekar\eclipse-workspace\NodeJS+DB2\FirstApp\node_modules\ibm_db\build\Release\odbc_bindings.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at bindings (C:\Users\AnkitaPalekar\eclipse-workspace\NodeJS+DB2\FirstApp\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Users\AnkitaPalekar\eclipse-workspace\NodeJS+DB2\FirstApp\node_modules\ibm_db\lib\odbc.js:31:31)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)

**Comment by PriyankaManoharan04** [comment]
@apalek94 Can you delete the folder `npm` under (C:\Users\AnkitaPalekar\AppData\Roaming\npm) and please follow exactly the below steps on new command prompt and share your output.

cd \
mkdir nodeapp
cd nodeapp
npm install ibm_db
cd node_modules\ibm_db\test
node test-basic-test.js

Under your nodeapp folder please make sure you have node_modules folder and package-lock.json file.

Thanks.

**Comment by apalek94** [comment]
Hi @PriyankaManoharan04 
I have installed nodejs version 10.15.3 & followed exactly above steps. Got following error---------------------------------------------------------------------------------------------------->

C:\Users\AnkitaPalekar\nodeapp\node_modules\ibm_db\test>node test-basic-test.js
C:\Users\AnkitaPalekar\nodeapp\node_modules\bindings\bindings.js:121
        throw e;
        ^

Error: The specified procedure could not be found.
\\?\C:\Users\AnkitaPalekar\nodeapp\node_modules\ibm_db\build\Release\odbc_bindings.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at bindings (C:\Users\AnkitaPalekar\nodeapp\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Users\AnkitaPalekar\nodeapp\node_modules\ibm_db\lib\odbc.js:31:31)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)

**Comment by PriyankaManoharan04** [comment]
"Error: db2cli sees an invalid option." says you have deleted some space while modifying the command. Please check proper spacing and try to rerun it. That will tell us any odbc driver related issue.

**Comment by PriyankaManoharan04** [comment]
Using dependency walker (download from net if you don't have), verify that C:\Users\AnkitaPalekar\nodeapp\node_modules\ibm_db\build\Release\odbc_bindings.node is able to find all its dependent libraries or not. If not, then need to set the path. 
Also, you can compare with your colleague system env and see what is difference. it is working fine for us. thanks.

**Comment by apalek94** [comment]
@PriyankaManoharan04 
I have installed dependency walker & it is showing that it is not able to find all the dependencies. Now, which path i need to set can you please tell me & thanks Priyanka for all your support..

**Comment by apalek94** [comment]
sharing the o/p of dependency walker------------>
[odbc_bindings.txt](https://github.com/ibmdb/node-ibm_db/files/3037560/odbc_bindings.txt)

**Comment by PriyankaManoharan04** [comment]
@apalek94 The issue is because you have an old version of Db2 installed at C:\PROGRA~1\IBM\SQLLIB. The ibm_db driver is picking up the dlls of this location which is very old and hence failing.
From your system env var PATH, please remove below env vars:
```
C:\PROGRA~1\IBM\SQLLIB\BIN\
C:\PROGRA~1\IBM\SQLLIB\FUNCTION\
C:\PROGRA~1\IBM\SQLLIB\SAMPLES\REPL\
C:\Users\AnkitaPalekar\nodeapp\node_modules\ibm_db\build\Release\odbc_bindings.node\
C:\PROGRA~1\IBM\SQLLIB\BIN\
C:\PROGRA~1\IBM\SQLLIB\FUNCTION\
C:\PROGRA~1\IBM\SQLLIB\SAMPLES\REPL\
```
and add below paths to PATH env var:
```
C:\Users\AnkitaPalekar\nodeapp\node_modules\ibm_db\installer\clidriver\bin\
C:\Users\AnkitaPalekar\nodeapp\node_modules\ibm_db\installer\clidriver\lib\
```
Also remove any reference of `C:\PROGRA~1\IBM\SQLLIB` from `LIB` system env var and add above directories to `LIB` system environment variable.
After correcting the system environment variables `PATH` and `LIB`, open a new command windows and then run below commands:
```
cd .....\ibm_db
npm install
node test\test-basic-test.js
```
Thanks.

**Comment by apalek94** [comment]
Hi @PriyankaManoharan04 
I have followed above steps again got error------------------------------------------------------------>
C:\Users\AnkitaPalekar\nodeapp\node_modules\ibm_db\test>node test-basic-test.js
Trying to open a connection ...
{ [Error: [IBM][CLI Driver] SQL1336N  The remote host "hotel.torolab.ibm.com" was not found.  SQLSTATE=08001
]
  errors: [],
  error: '[node-odbc] SQL_ERROR',
  message:
   '[IBM][CLI Driver] SQL1336N  The remote host "hotel.torolab.ibm.com" was not found.  SQLSTATE=08001\r\n',
  state: '08001',
  sqlcode: -1336 }
assert.js:85
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: { [Error: [IBM][CLI Driver] SQL1336N  The remote host "hotel.torolab.ibm.com" was not found.  SQLSTATE=08001
]
  errors: [],... == null
    at C:\Users\AnkitaPalekar\nodeapp\node_modules\ibm_db\test\test-basic-test.js:9:10
    at C:\Users\AnkitaPalekar\nodeapp\node_modules\ibm_db\lib\odbc.js:111:11
    at C:\Users\AnkitaPalekar\nodeapp\node_modules\ibm_db\lib\odbc.js:332:18

**Comment by PriyankaManoharan04** [comment]
@apalek94 Now its an connection error.Please update your connection string in config.testConnectionStrings.json file and run 'node test-basic-test.js'.Thanks

**Comment by apalek94** [comment]
@PriyankaManoharan0
Finally done!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  :-)
Thanks alot Priyanka for your continuous support. Appreciated!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
