### ISSUE TITLE
Ubuntu issue with install

### ISSUE THREAD

**Issue by AlaaShamandy** [ibmdb/node-ibm_db#522]
Downloading ibm_db is successful but installation faces an error:

Downloading and extraction of DB2 ODBC CLI Driver completed successfully ...

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/root/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/root/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/root/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/which/which.js:80:29)
gyp ERR! stack     at /root/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/which/which.js:89:16
gyp ERR! stack     at /root/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /root/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.15.0-44-generic
gyp ERR! command "/root/.nvm/versions/node/v8.9.4/bin/node" "/root/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=/var/www/proxyproject/SVLHelpDesk/vueauthclient-backend/node_modules/ibm_db/installer/clidriver"
gyp ERR! cwd /var/www/proxyproject/SVLHelpDesk/vueauthclient-backend/node_modules/ibm_db
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"' }

**Comment by AlaaShamandy** [comment]
Can be closed, had to install Make on the server!
