### ISSUE TITLE
npm install failing in Travis CI Linux

### ISSUE THREAD

**Issue by brandonwarech** [ibmdb/node-ibm_db#527]
```
> ibm_db@2.5.0 install /home/travis/build/Watson-Implementations-Practice/WBS-Bot-Framework/orchestration-nodeapp/node_modules/ibm_db
> node installer/driverInstall.js
Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli//linuxx64_odbc_cli.tar.gz...
100.00% | 21032500 bytes downloaded out of 21032500 bytes.
****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in undefined   Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
****************************************
Downloading and extraction of DB2 ODBC CLI Driver completed successfully ...
make: Entering directory `/home/travis/build/Watson-Implementations-Practice/WBS-Bot-Framework/orchestration-nodeapp/node_modules/ibm_db/build'
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
make: Leaving directory `/home/travis/build/Watson-Implementations-Practice/WBS-Bot-Framework/orchestration-nodeapp/node_modules/ibm_db/build'
{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
cc1plus: error: unrecognized command line option ‘-std=gnu++1y’
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 3.13.0-115-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v10.15.3/bin/node" "/home/travis/.nvm/versions/node/v10.15.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=/home/travis/build/Watson-Implementations-Practice/WBS-Bot-Framework/orchestration-nodeapp/node_modules/ibm_db/installer/clidriver"
gyp ERR! cwd /home/travis/build/Watson-Implementations-Practice/WBS-Bot-Framework/orchestration-nodeapp/node_modules/ibm_db
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: [secure],
  code: 1,
  signal: null,
  cmd:
   'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"' }
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.5.0 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@2.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by bimalkjha** [comment]
@brandonwarech In the posted error message, we can see below error:
```
cc1plus: error: unrecognized command line option ‘-std=gnu++1y’
```
After searching it on google, we can find many posts. I think [this](https://stackoverflow.com/questions/14674597/cc1plus-error-unrecognized-command-line-option-std-c11-with-g) post has mentioned correct root cause and solution.
Your system has older version of g++ compiler which do not support C++11 syntax. Newer node versions uses C++11 syntax and require g++ version > 4.8. Please upgrade your compiler to latest version. Thanks.

**Comment by jinin2007** [comment]
@brandonwarech  I got the same error.  I have not figured out how to upgrade C++ complier in travis.  Have you found a solution yet?  Thanks.

**Comment by brandonwarech** [comment]
@jinin2007 thanks for reaching out, here's my  `.travis.yml` that works to upgrade the c++ compiler

language: node_js
node_js:
  - 10
  - 9
  - 8
sudo: required
os: linux
dist: trusty
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_install:
  - sudo apt-get install build-essential

**Comment by jinin2007** [comment]
It works like a charm !!!  Thank you soooooooo much for your help, @brandonwarech : )
