### ISSUE TITLE
executeNonQuerySync   Wrong number of parameters. SQLSTATE=07001

### ISSUE THREAD

**Issue by debrajo** [ibmdb/node-ibm_db#595]
I've been trying to find correct coding syntax to perform a beginTransaction, prepareSync  insert SQL with 2  executeNonQuerySync  with a error / row checking for a commit/rollback.  I've tried both beginTransaction  and beginTransactionSync and I continued to receive the error from title.   

I've reproduced the error to this small code.  Any help/direction would be appreciated. 
node.js : v10.16.0 
npm : 6.9.0
ibm_db : ibm_db@2.6.1
copy db2consv_zs.lic  node_modules\ibm_db\installer\clidriver\license

executeNonQuery.js
```
/**
 * Db2 for z/OS,  
 * DSN11015 : Db2 11 in new-function mode   
CREATE TABLE U246149.TESTS01 (                                    
  RPT_YEAR CHAR(4) NOT NULL,                                       
  RPT_MONTH CHAR(2) NOT NULL                                      
) IN U246149.QMFSAVEU                                             
 AUDIT NONE DATA CAPTURE NONE CCSID UNICODE NOT VOLATILE APPEND NO ;
 * 
 */

var ibmdb = require('ibm_db');
var connString = "DRIVER={DB2};DATABASE=DSND;UID=xxxxx;PWD=V3stGood;HOSTNAME=iccmvs1.pok.ibm.com;port=6000"
try {
    ibmdb.debug(true);  // **==> ENABLE CONSOLE LOGS. <==**
    ibmdb.open(connString, function (err, conn) {
        if (err) return console.log(err);
        console.log("prepareSync starting")
        var stmt = conn.prepareSync("INSERT INTO U246149.TESTS01 (RPT_YEAR , RPT_MONTH)  VALUES (?, ?)") //testTable
        var affectedRowCount = stmt.executeNonQuerySync(['2019', '10'])
        console.log("insertStaging insert newRow success: Affected rows = " + affectedRowCount);
        conn.closeSync(function (err) { console.log("commitTransactionSync Connection Closed after success."); });
    });
} catch (error) {
    console.log(' Fatal error')
    console.log(error.message);
}
```

Console Log: 
node executeNonQuery
```
`node-ibm_db logs enabled.
prepareSync starting
C:\Users\DebraJohnson\projects\git\src\github.ibm.com\debrajo\db2_client\executeNonQuery.js:21
        var affectedRowCount = stmt.executeNonQuerySync(['2019', '10'])
                                    ^
Error: [IBM][CLI Driver] CLI0100E  Wrong number of parameters. SQLSTATE=07001
    at C:\Users\DebraJohnson\projects\git\src\github.ibm.com\debrajo\db2_client\executeNonQuery.js:21:37
    at C:\Users\DebraJohnson\projects\git\src\github.ibm.com\debrajo\db2_client\node_modules\ibm_db\lib\odbc.js:111:11
    at C:\Users\DebraJohnson\projects\git\src\github.ibm.com\debrajo\db2_client\node_modules\ibm_db\lib\odbc.js:335:11
```
`

**Comment by bimalkjha** [comment]
@debrajo Currently executeNonQuerySync() ignores any parameters passed to it. So, no parameter is binded and  hence error by executeNonQuerySync().
To avoid it, you can call stmt.bindSync([params]) first and then call stmt.executeNonQuerySync(). That should work. So, below code from your test program should work.
```
          var stmt = conn.prepareSync("INSERT INTO U246149.TESTS01 (RPT_YEAR , RPT_MONTH)  VALUES (?, ?)") //testTable
         stmt.bindSync(['2019', '10']);
        var affectedRowCount = stmt.executeNonQuerySync();
```
Above is a work around. You can hitting this issue due to some missing code. Code for executeNonQuerySync() is missing in `ibm_db/lib/odbc.js` file. I'll deliver the fix soon. Thanks.
