### ISSUE TITLE
API fails on wrong number of parameters

### ISSUE THREAD

**Issue by daniel-ferenczi** [ibmdb/node-ibm_db#63]
The API fails and causes the application to end when calling the query method on a connection with a wrong number of parameters. Would it be possible to implement a check for this?
```
{ [Error: [IBM][CLI Driver] CLI0100E  Wrong number of parameters. SQLSTATE=07001]
  errors: [],
  error: '[node-odbc] SQL_ERROR',
  message: '[IBM][CLI Driver] CLI0100E  Wrong number of parameters. SQLSTATE=07001',
  state: '07001' }
...\node_modules\ibm_db\lib\odbc.js:324
      self.conn.query(sql, params, cbQuery);
               ^
TypeError: Cannot read property 'query' of undefined
    at ...\node_modules\ibm_db\lib\odbc.js:324:16
    at SimpleQueue.next (...\node_modules\ibm_db\lib\simple-queue.js:34:5)
    at SimpleQueue.maybeNext (...\node_modules\ibm_db\lib\simple-queue.js:22:10)
    at ...\node_modules\ibm_db\lib\simple-queue.js:37:12
    at ...\node_modules\ibm_db\lib\odbc.js:285:20

Process finished with exit code 1
```

**Comment by bimalkjha** [comment]
@daniel-ferenczi Please share your test program. Also, let us know why are you calling query with wrong number of parameters? With wrong number of parameters, error is expected. What kind of you are looking for. Please share repro. Thanks.
