### ISSUE TITLE
error in installation of node-red-contrib-db2

### ISSUE THREAD

**Issue by sara88m** [ibmdb/node-ibm_db#646]
Hi everyone. I installed node-red on win64. Now I want to install node-red-contrib-db2 but I get error. anyone could help me? this is the log:
----------------------------------------------------------
2020-05-01T14:16:09.062Z Install : node-red-contrib-db2 0.0.2

2020-05-01T14:16:09.742Z npm.cmd install --no-audit --no-update-notifier --save --save-prefix="~" --production node-red-contrib-db2@0.0.2
2020-05-01T14:16:12.476Z [err] npm
2020-05-01T14:16:12.476Z [err]  WARN deprecated tar.gz@0.1.1: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar
2020-05-01T14:16:13.536Z [err] npm
2020-05-01T14:16:13.537Z [err]  WARN deprecated natives@1.1.6: This module relies on Node.js's internals and will break at some point. Do not use it, and update to graceful-fs@4.x.
2020-05-01T14:16:17.051Z [out] 
2020-05-01T14:16:17.051Z [out] > ibm_db@0.0.19 install C:\Users\amir\.node-red\node_modules\ibm_db
2020-05-01T14:16:17.051Z [out] > node installer/driverInstall.js
2020-05-01T14:16:17.051Z [out] 
2020-05-01T14:16:17.229Z [err] fs.js:35
2020-05-01T14:16:17.229Z [err] } = primordials;
2020-05-01T14:16:17.229Z [err]     ^
2020-05-01T14:16:17.229Z [err] 
2020-05-01T14:16:17.229Z [err] ReferenceError: primordials is not defined
2020-05-01T14:16:17.229Z [err]     at fs.js:35:5
2020-05-01T14:16:17.229Z [err]     at req_ (C:\Users\amir\.node-red\node_modules\natives\index.js:143:24)
2020-05-01T14:16:17.229Z [err]     at Object.req [as require] (C:\Users\amir\.node-red\node_modules\natives\index.js:55:10)
2020-05-01T14:16:17.229Z [err]     at Object.<anonymous> (C:\Users\amir\.node-red\node_modules\unzip\node_modules\graceful-fs\fs.js:1:37)
2020-05-01T14:16:17.229Z [err]     at Module._compile (internal/modules/cjs/loader.js:1133:30)
2020-05-01T14:16:17.229Z [err]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
2020-05-01T14:16:17.229Z [err]     at Module.load (internal/modules/cjs/loader.js:977:32)
2020-05-01T14:16:17.229Z [err]     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
2020-05-01T14:16:17.229Z [err]     at Module.require (internal/modules/cjs/loader.js:1019:19)
2020-05-01T14:16:17.229Z [err]     at require (internal/modules/cjs/helpers.js:77:18)
2020-05-01T14:16:17.986Z [err] npm 
2020-05-01T14:16:17.986Z [err] ERR! code ELIFECYCLE
2020-05-01T14:16:17.986Z [err] npm ERR! errno 1
2020-05-01T14:16:17.988Z [err] npm 
2020-05-01T14:16:17.988Z [err] ERR! ibm_db@0.0.19 install: `node installer/driverInstall.js`
2020-05-01T14:16:17.988Z [err] npm ERR! Exit status 1
2020-05-01T14:16:17.989Z [err] npm ERR! 
2020-05-01T14:16:17.989Z [err] npm ERR! Failed at the ibm_db@0.0.19 install script.
2020-05-01T14:16:17.989Z [err] npm
2020-05-01T14:16:17.989Z [err]  ERR! This is probably not a problem with npm. There is likely additional logging output above.
2020-05-01T14:16:18.074Z [err] 
2020-05-01T14:16:18.074Z [err] npm ERR! A complete log of this run can be found in:
2020-05-01T14:16:18.074Z [err] npm ERR!     C:\Users\amir\AppData\Roaming\npm-cache\_logs\2020-05-01T14_16_17_996Z-debug.log
2020-05-01T14:16:18.105Z rc=1

**Comment by bimalkjha** [comment]
@sara88m It looks issue with `node-red-contrib-db2@0.0.2` which is not updated since last 4 years. Its due to use of old version of ibm_db in package.json file. I would suggest to clone the node-red-contrib-db2 from https://github.com/mfou/node-red-contrib-db2.git, update version of ibm_db at line no 6 in package.json to 2.6.4 and then run `npm install` to install it. Alternatively, you may open an issue against node-red-contrib-db2 to update the version of ibm_db used by this package. This issue is not related with ibm_db. Thanks.
