### ISSUE TITLE
AIX Error: Could not locate the bindings file

### ISSUE THREAD

**Issue by jh6779** [ibmdb/node-ibm_db#736]
Installed ibm_db no error but make says nothing to be done

```
> ibm_db@2.7.2 install /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db
> node installer/driverInstall.js

platform =  aix , arch =  ppc64 , node.js version =  v14.15.0
make version = GNU Make version 3.79, by Richard Stallman and Roland McGrath.
IBM_DB_HOME environment variable have already been set to -> /whouse/sqllib

Downloading of clidriver skipped - build is in progress...

gmake: Entering directory `/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build'
gmake: Nothing to be done for `all'.
gmake: Leaving directory `/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build'

+ ibm_db@2.7.2
added 59 packages from 45 contributors and audited 59 packages in 7.151s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

When I try to run my application using ibm_db I get the following error

```
 /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build/Debug/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build/Release/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/out/Debug/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/Debug/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/out/Release/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/Release/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build/default/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/compiled/14.15.0/aix/ppc64/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/addon-build/release/install-root/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/addon-build/debug/install-root/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/addon-build/default/install-root/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/lib/binding/node-v83-aix-ppc64/odbc_bindings.node
    at bindings (/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/lib/odbc.js:57:31)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/whouse/dev/jhernand/db2-cloudant/app.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  tries: [
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build/Debug/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build/Release/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/out/Debug/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/Debug/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/out/Release/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/Release/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build/default/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/compiled/14.15.0/aix/ppc64/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/addon-build/release/install-root/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/addon-build/debug/install-root/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/addon-build/default/install-root/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/lib/binding/node-v83-aix-ppc64/odbc_bindings.node'
  ]
}
```

**Comment by bimalkjha** [comment]
@jh6779 The `Nothing to be done for all` from `gmake` is causing the problem. As a result, the cpp files under `ibm_db/src` directory did not get compiled and bindings file `/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build/Release/odbc_bindings.node` didn't generate. Try below commands and share the result:
```
cd /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db
npm install
node test/test-basic-test.js
```
Thanks.

**Comment by jh6779** [comment]
Received a similar error:
```
>cd /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db
[whouse@devreports] /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db
>npm install

> ibm_db@2.7.2 install /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db
> node installer/driverInstall.js

platform =  aix , arch =  ppc64 , node.js version =  v14.15.0
make version = GNU Make version 3.79, by Richard Stallman and Roland McGrath.
IBM_DB_HOME environment variable have already been set to -> /whouse/sqllib

Downloading of clidriver skipped - build is in progress...

gmake: Entering directory `/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build'
gmake: Nothing to be done for `all'.
gmake: Leaving directory `/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build'

npm notice created a lockfile as package-lock.json. You should commit this file.
added 62 packages from 52 contributors and audited 62 packages in 9.389s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

[whouse@devreports] /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db
>node test/test-basic-test.js
/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/node_modules/bindings/bindings.js:135
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build/Debug/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build/Release/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/out/Debug/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/Debug/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/out/Release/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/Release/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build/default/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/compiled/14.15.0/aix/ppc64/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/addon-build/release/install-root/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/addon-build/debug/install-root/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/addon-build/default/install-root/odbc_bindings.node
 → /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/lib/binding/node-v83-aix-ppc64/odbc_bindings.node
    at bindings (/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/lib/odbc.js:57:31)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/test/common.js:1:12)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  tries: [
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build/Debug/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build/Release/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/out/Debug/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/Debug/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/out/Release/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/Release/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build/default/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/compiled/14.15.0/aix/ppc64/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/addon-build/release/install-root/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/addon-build/debug/install-root/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/addon-build/default/install-root/odbc_bindings.node',
    '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/lib/binding/node-v83-aix-ppc64/odbc_bindings.node'
  ]
}
```

**Comment by bimalkjha** [comment]
@jh6779 Looks strange behavior of gmake. Please share output of `db2level` command and run below commands:
```
cd /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db
rm -rf build
npm install
```
If still fails, then share output of below commands:
```
npm install -g node-gyp
echo $IBM_DB_HOME
ls -l /whouse/sqllib/include/sqlcli1.h
node-gyp configure build --IBM_DB_HOME=$IBM_DB_HOME  --IS_DOWNLOADED=false --verbose 
```
Thanks.

**Comment by jh6779** [comment]
```
[whouse@devreports] /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db
>echo $IBM_DB_HOME
/whouse/sqllib
[whouse@devreports] /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db
>ls -l /whouse/sqllib/include/sqlcli1.h
-r--r--r--    1 bin      bin           77380 May 30 2019  /whouse/sqllib/include/sqlcli1.h
[whouse@devreports] /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db
>node-gyp configure build --IBM_DB_HOME=$IBM_DB_HOME  --IS_DOWNLOADED=false --verbose
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   '/opt/node-v14.15.0-aix-ppc64/bin/node',
gyp verb cli   '/opt/node-v14.15.0-aix-ppc64/bin/node-gyp',
gyp verb cli   'configure',
gyp verb cli   'build',
gyp verb cli   '--IBM_DB_HOME=/whouse/sqllib',
gyp verb cli   '--IS_DOWNLOADED=false',
gyp verb cli   '--verbose'
gyp verb cli ]
gyp info using node-gyp@7.1.2
gyp info using node@14.15.0 | aix | ppc64
gyp verb command configure []
gyp verb find Python Python is not set from command line or npm configuration
gyp verb find Python Python is not set from environment variable PYTHON
gyp verb find Python checking if "python3" can be used
gyp verb find Python - executing "python3" to get executable path
gyp verb find Python - executable path is "/opt/bin/python3"
gyp verb find Python - executing "/opt/bin/python3" to get version
gyp verb find Python - version is "3.5.2"
gyp info find Python using Python version 3.5.2 found at "/opt/bin/python3"
gyp verb get node dir no --target version specified, falling back to host node version: 14.15.0
gyp verb command install [ '14.15.0' ]
gyp verb install input version string "14.15.0"
gyp verb install installing version: 14.15.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 14.15.0
gyp verb build dir attempting to create "build" dir: /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build
gyp verb build dir "build" dir needed to be created? undefined
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build/config.gypi
gyp verb config.gypi checking for gypi file: /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/config.gypi
gyp verb common.gypi checking for gypi file: /whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp verb node-gyp root npm_parent_directory is node-v14.15.0-aix-ppc64
gyp verb node-gyp root Finding node root directory
gyp verb find exports file Found exports file: /opt/node-v14.15.0-aix-ppc64/include/node/node.exp
gyp info spawn /opt/bin/python3
gyp info spawn args [
gyp info spawn args   '/opt/node-v14.15.0-aix-ppc64/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/node-v14.15.0-aix-ppc64/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/whouse/.cache/node-gyp/14.15.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/whouse/.cache/node-gyp/14.15.0',
gyp info spawn args   '-Dnode_exp_file=/opt/node-v14.15.0-aix-ppc64/include/node/node.exp',
gyp info spawn args   '-Dnode_gyp_dir=/opt/node-v14.15.0-aix-ppc64/lib/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/whouse/.cache/node-gyp/14.15.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture ppc64
gyp verb node dev dir /whouse/.cache/node-gyp/14.15.0
gyp verb `which` succeeded for `gmake` /usr/local/bin/gmake
gyp info spawn gmake
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
gmake: Entering directory `/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build'
gmake: Nothing to be done for `all'.
gmake: Leaving directory `/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build'
gyp info ok
```

**Comment by bimalkjha** [comment]
@jh6779 Still `gmake` fails to compile the code. First delete `/whouse/dev/jhernand/db2-cloudant/node_modules/ibm_db/build` directory and then run the node-gyp command. It still it fails, update the gmake package to latest version and then try. Thanks.

**Comment by bimalkjha** [comment]
@jh6779 Any update?

**Comment by jh6779** [comment]
@bimalkjha I was able to update make and that allowed the install to proceed but I'm now stuck on g++ error. I updated g++ but there is a LIBPATH dependency that is conflicting with node. I will have to resolve this before I can complete the ibm_db install.

**Comment by jh6779** [comment]
I was able to install ibm_db however I am getting a coredump when the application ends
```
>node app.js
Cloudant Database 'stg_iw' already exists skipping create
DB2 export complete
Inserted 253 documents
Completed Insert to stg_iw
Illegal instruction(coredump)
```

**Comment by bimalkjha** [comment]
@jh6779 The core dump at last is a known issue on AIX. If you can ignore it and proceed, would be good.
Its a bug with node.js installer on AIX. Check [this comment](https://github.com/ibmdb/node-ibm_db/issues/439#issuecomment-413954096) of issue #439 more info. Thanks.
