### ISSUE TITLE
ibm_db Installation issue using node v10.23.1

### ISSUE THREAD

**Issue by davidmrg** [ibmdb/node-ibm_db#737]
Hi,

When installing a node project that uses the ibm_db@2.4.0 (by using the npm install command), the following error appears in console:

```
> ibm_db@2.4.0 install /Users/davidmramirez/Desktop/Onboarding/onboardingMan22012021/onboarding-management/node_modules/ibm_db
> node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz...

100.00% | 28394652 bytes downloaded out of 28394652 bytes.

****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in undefined   Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
****************************************

Downloading and extraction of DB2 ODBC CLI Driver completed successfully ...

  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o

{ Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"
../src/odbc.cpp:210:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    data->cb->Call(1, info);
              ^
../../nan/nan.h:1654:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/odbc.cpp:217:80: error: no matching member function for call to 'NewInstance'
    Local<Object> js_result = Nan::New<Function>(ODBCConnection::constructor)->NewInstance(2, info);
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/Users/davidmramirez/Library/Caches/node-gyp/10.23.1/include/node/v8.h:3996:44: note: candidate function not viable: requires single argument 'context', but 2 arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/davidmramirez/Library/Caches/node-gyp/10.23.1/include/node/v8.h:3993:44: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
../src/odbc.cpp:222:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    data->cb->Call(2, info);
              ^
../../nan/nan.h:1654:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/odbc.cpp:262:78: error: no matching member function for call to 'NewInstance'
  Local<Object> js_result = Nan::New<Function>(ODBCConnection::constructor)->NewInstance(2, params);
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
/Users/davidmramirez/Library/Caches/node-gyp/10.23.1/include/node/v8.h:3996:44: note: candidate function not viable: requires single argument 'context', but 2 arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
/Users/davidmramirez/Library/Caches/node-gyp/10.23.1/include/node/v8.h:3993:44: note: candidate function not viable: requires 3 arguments, but 2 were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> NewInstance(
                                           ^
../src/odbc.cpp:912:38: warning: 'IntegerValue' is deprecated [-Wdeprecated-declarations]
          params[i].paramtype = val->IntegerValue();
                                     ^
/Users/davidmramirez/Library/Caches/node-gyp/10.23.1/include/node/v8.h:2476:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/davidmramirez/Library/Caches/node-gyp/10.23.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/odbc.cpp:916:35: warning: 'IntegerValue' is deprecated [-Wdeprecated-declarations]
          params[i].c_type = val->IntegerValue();
                                  ^
/Users/davidmramirez/Library/Caches/node-gyp/10.23.1/include/node/v8.h:2476:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/davidmramirez/Library/Caches/node-gyp/10.23.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/odbc.cpp:922:33: warning: 'IntegerValue' is deprecated [-Wdeprecated-declarations]
          params[i].type = val->IntegerValue();
                                ^
/Users/davidmramirez/Library/Caches/node-gyp/10.23.1/include/node/v8.h:2476:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/davidmramirez/Library/Caches/node-gyp/10.23.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/odbc.cpp:930:46: warning: 'IntegerValue' is deprecated [-Wdeprecated-declarations]
              params[i].buffer_length = val->IntegerValue();
                                             ^
/Users/davidmramirez/Library/Caches/node-gyp/10.23.1/include/node/v8.h:2476:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/davidmramirez/Library/Caches/node-gyp/10.23.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/odbc.cpp:1066:43: warning: 'IntegerValue' is deprecated [-Wdeprecated-declarations]
    int64_t  *number = new int64_t(value->IntegerValue());
                                          ^
/Users/davidmramirez/Library/Caches/node-gyp/10.23.1/include/node/v8.h:2476:3: note: 'IntegerValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
  ^
/Users/davidmramirez/Library/Caches/node-gyp/10.23.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/odbc.cpp:1082:42: warning: 'NumberValue' is deprecated [-Wdeprecated-declarations]
    double *number   = new double(value->NumberValue());
                                         ^
/Users/davidmramirez/Library/Caches/node-gyp/10.23.1/include/node/v8.h:2475:3: note: 'NumberValue' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", double NumberValue() const);
  ^
/Users/davidmramirez/Library/Caches/node-gyp/10.23.1/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/odbc.cpp:1194:7: warning: 'Call' is deprecated [-Wdeprecated-declarations]
  cb->Call(1, info);
      ^
../../nan/nan.h:1654:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../nan/nan.h:102:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/odbc.cpp:1258:87: error: too few arguments to function call, expected 2, have 1
      objError->SetPrototype(Exception::Error(Nan::New(errorMessage).ToLocalChecked()));
      ~~~~~~~~~~~~~~~~~~~~~~                                                          ^
/Users/davidmramirez/Library/Caches/node-gyp/10.23.1/include/node/v8.h:3442:3: note: 'SetPrototype' declared here
  V8_WARN_UNUSED_RESULT Maybe<bool> SetPrototype(Local<Context> context,
  ^
/Users/davidmramirez/Library/Caches/node-gyp/10.23.1/include/node/v8config.h:416:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
9 warnings and 3 errors generated.
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/davidmramirez/.nvm/versions/node/v10.23.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:191:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/davidmramirez/.nvm/versions/node/v10.23.1/bin/node" "/Users/davidmramirez/.nvm/versions/node/v10.23.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=/Users/davidmramirez/Desktop/Onboarding/onboardingMan22012021/onboarding-management/node_modules/ibm_db/installer/clidriver"
gyp ERR! cwd /Users/davidmramirez/Desktop/Onboarding/onboardingMan22012021/onboarding-management/node_modules/ibm_db
gyp ERR! node -v v10.23.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"' }
npm WARN onboarding-management@0.0.1 No repository field.
npm WARN onboarding-management@0.0.1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.4.0 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@2.4.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/davidmramirez/.npm/_logs/2021-01-22T18_23_56_483Z-debug.log
MacBook-Air-de-David:onboarding-management davidmramirez$ 
```

Thanks and regards,

**Comment by bimalkjha** [comment]
@davidmrg ibm_db v2.4.0 is very old and it do not support node v10.23.1. So, please install latest version of ibm_db using `npm install ibm_db@2.7.2` which works with node v10.23.1. Thanks.

**Comment by bimalkjha** [comment]
@davidmrg Closing the issue now. Let us know if you still face any issue using ibm_db@2.7.2. Thanks.
