### ISSUE TITLE
Not Building on OSX

### ISSUE THREAD

**Issue by caltangelo** [ibmdb/node-ibm_db#74]
When running `npm install ibm_db` on my machine with  OSX 10.10.5 and node 5.0.0, I get the following error:
```
Downloading DB2 ODBC CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz...
Download and extraction of DB2 ODBC CLI Driver completed successfully ...
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o

{ [Error: Command failed: /bin/sh -c node-gyp configure build --IBM_DB_HOME=$IBM_DB_HOME --IS_DOWNLOADED=true
In file included from ../src/odbc.cpp:25:
In file included from ../src/odbc.h:23:
../../nan/nan.h:261:25: error: redefinition of '_NanEnsureLocal'
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                        ^
../../nan/nan.h:256:25: note: previous definition is here
NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                        ^
../../nan/nan.h:661:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../../nan/nan.h:672:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/a573029/.node-gyp/5.0.0/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/a573029/.node-gyp/5.0.0/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/a573029/.node-gyp/5.0.0/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/a573029/.node-gyp/5.0.0/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5 arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../src/odbc.cpp:25:
In file included from ../src/odbc.h:23:
../../nan/nan.h:676:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/a573029/.node-gyp/5.0.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/a573029/.node-gyp/5.0.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/a573029/.node-gyp/5.0.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against 'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/a573029/.node-gyp/5.0.0/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against 'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../src/odbc.cpp:25:
In file included from ../src/odbc.h:23:
../../nan/nan.h:683:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
../src/odbc.cpp:115:16: warning: implicit conversion of NULL constant to 'SQLHENV' (aka 'int') [-Wnull-conversion]
      m_hEnv = NULL;      
             ~ ^~~~
               0
../src/odbc.cpp:129:17: warning: implicit conversion of NULL constant to 'SQLHENV' (aka 'int') [-Wnull-conversion]
  dbo->m_hEnv = NULL;
              ~ ^~~~
                0
../src/odbc.cpp:221:32: warning: cast to 'void *' from smaller integer type 'SQLHENV' (aka 'int') [-Wint-to-void-pointer-cast]
    args[0] = NanNew<External>((void*)data->dbo->m_hEnv);
                               ^
../src/odbc.cpp:222:32: warning: cast to 'void *' from smaller integer type 'SQLHDBC' (aka 'int') [-Wint-to-void-pointer-cast]
    args[1] = NanNew<External>((void*)data->hDBC);
                               ^
../src/odbc.cpp:233:5: warning: 'FatalException' is deprecated: Use FatalException(isolate, ...) [-Wdeprecated-declarations]
    FatalException(try_catch);
    ^
/Users/a573029/.node-gyp/5.0.0/include/node/node.h:283:29: note: 'FatalException' has been explicitly marked deprecated here
                inline void FatalException(const v8::TryCatch& try_catch) {
                            ^
/Users/a573029/.node-gyp/5.0.0/include/node/node.h:66:42: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                                         ^
../src/odbc.cpp:268:32: warning: cast to 'void *' from smaller integer type 'SQLHENV' (aka 'int') [-Wint-to-void-pointer-cast]
  params[0] = NanNew<External>((void*)dbo->m_hEnv);
                               ^
../src/odbc.cpp:269:32: warning: cast to 'void *' from smaller integer type 'SQLHDBC' (aka 'int') [-Wint-to-void-pointer-cast]
  params[1] = NanNew<External>((void*)hDBC);
                               ^
../src/odbc.cpp:479:9: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        tm_sec : 0
        ^~~~~~~~
        .tm_sec = 
../src/odbc.cpp:480:11: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        , tm_min : 0
          ^~~~~~~~
          .tm_min = 
../src/odbc.cpp:481:11: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        , tm_hour : 0
          ^~~~~~~~~
          .tm_hour = 
../src/odbc.cpp:482:11: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        , tm_mday : 0
          ^~~~~~~~~
          .tm_mday = 
../src/odbc.cpp:483:11: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        , tm_mon : 0
          ^~~~~~~~
          .tm_mon = 
../src/odbc.cpp:484:11: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        , tm_year : 0
          ^~~~~~~~~
          .tm_year = 
../src/odbc.cpp:485:11: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        , tm_wday : 0
          ^~~~~~~~~
          .tm_wday = 
../src/odbc.cpp:486:11: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        , tm_yday : 0
          ^~~~~~~~~
          .tm_yday = 
../src/odbc.cpp:487:11: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        , tm_isdst : 0
          ^~~~~~~~~~
          .tm_isdst = 
../src/odbc.cpp:488:11: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        , tm_gmtoff : 0
          ^~~~~~~~~~~
          .tm_gmtoff = 
../src/odbc.cpp:489:11: warning: use of GNU old-style field designator extension [-Wgnu-designator]
        , tm_zone : 0
          ^~~~~~~~~
          .tm_zone = 
In file included from ../src/odbc.cpp:19:
/Users/a573029/.node-gyp/5.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/a573029/.node-gyp/5.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:414:12: note: in instantiation of function template specialization 'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/odbc.cpp:19:
/Users/a573029/.node-gyp/5.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/a573029/.node-gyp/5.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:424:12: note: in instantiation of function template specialization 'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/odbc.cpp:19:
/Users/a573029/.node-gyp/5.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/a573029/.node-gyp/5.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:1514:12: note: in instantiation of function template specialization 'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/odbc.cpp:19:
/Users/a573029/.node-gyp/5.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/a573029/.node-gyp/5.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../../nan/nan.h:1632:12: note: in instantiation of function template specialization 'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(handle->Get(NanNew(key)).As<v8::Object>());
           ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
In file included from ../src/odbc.cpp:19:
/Users/a573029/.node-gyp/5.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Array *volatile' from incompatible type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/a573029/.node-gyp/5.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../src/odbc.cpp:961:10: note: in instantiation of function template specialization 'v8::Local<v8::Array>::Local<v8::Value>' requested here
  return NanEscapeScope(rows);
         ^
../../nan/nan.h:398:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(_NanEnsureLocal(val))
                             ^
18 warnings and 10 errors generated.
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IBM_DB_HOME=/Users/a573029/git/mainframeHelper/node_modules/ibm_db/installer/clidriver" "--IS_DOWNLOADED=true"
gyp ERR! cwd /Users/a573029/git/mainframeHelper/node_modules/ibm_db
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c node-gyp configure build --IBM_DB_HOME=$IBM_DB_HOME --IS_DOWNLOADED=true' }
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/5.0.0/bin/node" "/usr/local/bin/npm" "install" "ibm_db"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@0.0.15 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@0.0.15 install script 'node installer/driverInstall.js'.
npm ERR! This is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/a573029/git/mainframeHelper/npm-debug.log```

**Comment by smartmouse** [comment]
I do not think ibm_db supports node 5.0.0, yet

**Comment by smartmouse** [comment]
If you just do npm install ibm_db, they will only work with Node 0.12.x . They have a branch that supports Node 4.x .

**Comment by bimalkjha** [comment]
@caltangelo Have you used below command to install? It should work for you:
`npm install git+https://git@github.com/ibmdb/node-ibm_db.git#v4_support`

Thanks.

**Comment by bimalkjha** [comment]
@smartmouse This comment says, it works for node.js 5.1.0 too: https://github.com/ibmdb/node-ibm_db/issues/64#issuecomment-158203371
Can you try? Thanks.

**Comment by caltangelo** [comment]
@bimalkjha Your suggestion worked, thank you very much.
