### ISSUE TITLE
/node_modules/ibm_db/build/Release/odbc_bindings.node: invalid ELF header  - ERROR WHILE RUNNING DOCKER WITH IBM_DB FOR MY APPLICATION

### ISSUE THREAD

**Issue by songires** [ibmdb/node-ibm_db#758]
> ibm-cert-manager@1.0.0 CERT-docker-debug /usr/src/app
> export NODE_ENV=development && backend/node_modules/.bin/concurrently "npm:CERT-docker-back" "npm:CERT-front"

[CERT-front] 
[CERT-front] > ibm-cert-manager@1.0.0 CERT-front /usr/src/app
[CERT-front] >  cd frontend && ./node_modules/.bin/webpack -w --mode=development --config-name "CERT-debug"
[CERT-front] 
[CERT-docker-back] 
[CERT-docker-back] > ibm-cert-manager@1.0.0 CERT-docker-back /usr/src/app
[CERT-docker-back] > cd backend && node src/index.js
[CERT-docker-back] 
[CERT-docker-back] ENVIRONMENT======> development
[CERT-front] APP DIRECTORY/usr/src/app/frontend
[CERT-front] BUILD DIRECTORY/usr/src/app/frontend/build
[CERT-docker-back] /usr/src/app/backend/node_modules/bindings/bindings.js:121
[CERT-docker-back]         throw e;
[CERT-docker-back]         ^
[CERT-docker-back] 
[CERT-docker-back] Error: /usr/src/app/backend/node_modules/ibm_db/build/Release/odbc_bindings.node: invalid ELF header
[CERT-docker-back]     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1122:18)
[CERT-docker-back]     at Module.load (internal/modules/cjs/loader.js:928:32)
[CERT-docker-back]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[CERT-docker-back]     at Module.require (internal/modules/cjs/loader.js:952:19)
[CERT-docker-back]     at require (internal/modules/cjs/helpers.js:88:18)
[CERT-docker-back]     at bindings (/usr/src/app/backend/node_modules/bindings/bindings.js:112:48)
[CERT-docker-back]     at Object.<anonymous> (/usr/src/app/backend/node_modules/ibm_db/lib/odbc.js:57:31)
[CERT-docker-back]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[CERT-docker-back]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[CERT-docker-back]     at Module.load (internal/modules/cjs/loader.js:928:32)
[CERT-docker-back] npm ERR! code ELIFECYCLE
[CERT-docker-back] npm ERR! errno 1
[CERT-docker-back] npm ERR! ibm-cert-manager@1.0.0 CERT-docker-back: `cd backend && node src/index.js`
npm ERR! Exit status 1
[CERT-docker-back] npm ERR! 
[CERT-docker-back] npm ERR! Failed at the ibm-cert-manager@1.0.0 CERT-docker-back script.
[CERT-docker-back] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[CERT-docker-back] npm WARN Local package.json exists, but node_modules missing, did you mean to install?
[CERT-docker-back] 
[CERT-docker-back] npm ERR! A complete log of this run can be found in:
[CERT-docker-back] npm ERR!     /root/.npm/_logs/2021-03-25T16_55_03_400Z-debug.log
[CERT-docker-back] npm run CERT-docker-back exited with code 1

**Comment by bimalkjha** [comment]
@songires `invalid ELF header` about a binary file means this file is not compatible for current platform. Probably, the image contains odbc_bindings.node file which was compiled on different operating system and now you are trying to install on other operating system.
Please cd to the `ibm_db` directory and run `npm install` command. Reinstalling should fix the issue, else share the complete output of docker installation of ibm_db and complete output of `npm install` command executed under ibm_db directory. Thanks.

**Comment by sbohner14335** [comment]
@songires @bimalkjha ^ Did the above ultimately resolve the issue?

**Comment by bimalkjha** [comment]
@sbohner14335 Yes.

**Comment by sbohner14335** [comment]
Ok, we did this within our Dockerfile and are now getting this error:

Here's our Dockerfile for reference
```
FROM registry.cirrus.ibm.com/public/nodejs-16:latest
USER root
RUN dnf update -y && dnf upgrade -y
WORKDIR /app
COPY . /app
ARG BUILD
RUN ls && cd node_modules/ibm_db && npm install
RUN npm install && npm run $BUILD
EXPOSE 8081
CMD npm run start
```

```
STEP 7: RUN ls && cd node_modules/ibm_db && npm install
Dockerfile
README.md
backend
frontend
node_modules
package.json
webpack.config.js

> ibm_db@2.8.1 install
> node installer/driverInstall.js

platform = linux, arch = x64, node.js version = v16.13.1
make version =GNU Make 4.2.1
Rebuild Process: Found clidriver at -> /app/node_modules/ibm_db/installer/clidriver

Downloading of clidriver skipped - build is in progress...

make: Entering directory '/app/node_modules/ibm_db/build'
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_connection.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_statement.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_result.o
  SOLINK_MODULE(target) Release/obj.target/odbc_bindings.node
make: Leaving directory '/app/node_modules/ibm_db/build'

Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"
gyp info it worked if it ends with ok
gyp info using node-gyp@8.3.0
gyp info using node@16.13.1 | linux | x64
gyp info find Python using Python version 3.6.8 found at "/usr/bin/python3"
gyp http GET https://nodejs.org/download/release/v16.13.1/node-v16.13.1-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v16.13.1/node-v16.13.1-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v16.13.1/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v16.13.1/SHASUMS256.txt
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/app/node_modules/ibm_db/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/opt/app-root/src/.cache/node-gyp/16.13.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/opt/app-root/src/.cache/node-gyp/16.13.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/opt/app-root/src/.cache/node-gyp/16.13.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/app/node_modules/ibm_db',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
../src/odbc.cpp: In static member function 'static void ODBC::UV_AfterCreateConnection(uv_work_t*, int)':
../src/odbc.cpp:216:27: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
     data->cb->Call(1, info);
                           ^
In file included from ../src/odbc.h:23,
                 from ../src/odbc.cpp:29:
../node_modules/nan/nan.h:1744:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/odbc.cpp:228:27: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
     data->cb->Call(2, info);
                           ^
In file included from ../src/odbc.h:23,
                 from ../src/odbc.cpp:29:
../node_modules/nan/nan.h:1744:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/odbc.cpp: In static member function 'static v8::Local<v8::Value> ODBC::CallbackSQLError(SQLSMALLINT, SQLHANDLE, char*, Nan::Callback*)':
../src/odbc.cpp:1413:19: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   cb->Call(1, info);
                   ^
In file included from ../src/odbc.h:23,
                 from ../src/odbc.cpp:29:
../node_modules/nan/nan.h:1744:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
In file included from ../src/odbc.cpp:24:
../src/odbc.cpp: At global scope:
/opt/app-root/src/.cache/node-gyp/16.13.1/include/node/node.h:821:43: warning: cast between incompatible function types from 'void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)' {aka 'void (*)(v8::Local<v8::Object>)'} to 'node::addon_register_func' {aka 'void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)'} [-Wcast-function-type]
       (node::addon_register_func) (regfunc),                          \
                                           ^
/opt/app-root/src/.cache/node-gyp/16.13.1/include/node/node.h:855:3: note: in expansion of macro 'NODE_MODULE_X'
   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
   ^~~~~~~~~~~~~
../src/odbc.cpp:1577:1: note: in expansion of macro 'NODE_MODULE'
 NODE_MODULE(odbc_bindings, init)
 ^~~~~~~~~~~
../src/odbc.cpp: In static member function 'static v8::Local<v8::Value> ODBC::GetColumnValue(SQLHSTMT, Column, uint16_t*, int)':
../src/odbc.cpp:592:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
         if((int) column.type == SQL_DBCLOB)
         ^~
../src/odbc.cpp:598:5: note: here
     case SQL_BLOB :
     ^~~~
../src/odbc.cpp:599:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
         if((int) column.type == SQL_BLOB)
         ^~
../src/odbc.cpp:605:5: note: here
     default :
     ^~~~~~~
../src/odbc.cpp: In static member function 'static v8::Local<v8::Value> ODBC::GetOutputParameter(Parameter)':
../src/odbc.cpp:734:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
         if((int) prm.type == SQL_NUMERIC)
         ^~
../src/odbc.cpp:736:5: note: here
     case SQL_BIGINT :
     ^~~~
../src/odbc.cpp:780:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
         if((int) prm.type == SQL_DECIMAL)
         ^~
../src/odbc.cpp:782:5: note: here
     case SQL_FLOAT :
     ^~~~
../src/odbc.cpp:825:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
         if((int) prm.type == SQL_DBCLOB)
         ^~
../src/odbc.cpp:829:5: note: here
     case SQL_BLOB :
     ^~~~
../src/odbc.cpp:830:9: warning: this statement may fall through [-Wimplicit-fallthrough=]
         if((int) prm.type == SQL_BLOB)
         ^~
../src/odbc.cpp:834:5: note: here
     default :
     ^~~~~~~
../src/odbc_connection.cpp: In static member function 'static void ODBCConnection::UV_AfterOpen(uv_work_t*, int)':
../src/odbc_connection.cpp:310:35: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->cb->Call(err ? 1 : 0, argv);
                                   ^
In file included from ../src/odbc.h:23,
                 from ../src/odbc_connection.cpp:25:
../node_modules/nan/nan.h:1744:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/odbc_connection.cpp: In static member function 'static void ODBCConnection::UV_AfterClose(uv_work_t*, int)':
../src/odbc_connection.cpp:534:35: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->cb->Call(err ? 1 : 0, argv);
                                   ^
In file included from ../src/odbc.h:23,
                 from ../src/odbc_connection.cpp:25:
../node_modules/nan/nan.h:1744:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/odbc_connection.cpp: In static member function 'static void ODBCConnection::UV_AfterCreateStatement(uv_work_t*, int)':
../src/odbc_connection.cpp:909:26: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->cb->Call( 2, info);
                          ^
In file included from ../src/odbc.h:23,
                 from ../src/odbc_connection.cpp:25:
../node_modules/nan/nan.h:1744:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/odbc_connection.cpp: In static member function 'static void ODBCConnection::UV_Query(uv_work_t*)':
../src/odbc_connection.cpp:1094:51: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
                                 (SQLPOINTER)data->arraySize, 0);
                                                   ^~~~~~~~~
../src/odbc_connection.cpp: In static member function 'static void ODBCConnection::UV_AfterQuery(uv_work_t*, int)':
../src/odbc_connection.cpp:1148:27: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
     data->cb->Call(2, info);
                           ^
In file included from ../src/odbc.h:23,
                 from ../src/odbc_connection.cpp:25:
../node_modules/nan/nan.h:1744:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/odbc_connection.cpp:1178:27: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
     data->cb->Call(3, info);
                           ^
In file included from ../src/odbc.h:23,
                 from ../src/odbc_connection.cpp:25:
../node_modules/nan/nan.h:1744:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/odbc_connection.cpp: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE ODBCConnection::QuerySync(Nan::NAN_METHOD_ARGS_TYPE)':
../src/odbc_connection.cpp:1341:46: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
                                 (SQLPOINTER) arraySize, 0);
                                              ^~~~~~~~~
../src/odbc_connection.cpp: In static member function 'static void ODBCConnection::UV_AfterBeginTransaction(uv_work_t*, int)':
../src/odbc_connection.cpp:1714:36: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->cb->Call( err ? 1 : 0, argv);
                                    ^
In file included from ../src/odbc.h:23,
                 from ../src/odbc_connection.cpp:25:
../node_modules/nan/nan.h:1744:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/odbc_connection.cpp: In static member function 'static void ODBCConnection::UV_AfterEndTransaction(uv_work_t*, int)':
../src/odbc_connection.cpp:1896:35: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->cb->Call(err ? 1 : 0, argv);
                                   ^
In file included from ../src/odbc.h:23,
                 from ../src/odbc_connection.cpp:25:
../node_modules/nan/nan.h:1744:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/odbc_connection.cpp: In static member function 'static void ODBCConnection::UV_AfterGetInfo(uv_work_t*, int)':
../src/odbc_connection.cpp:2100:26: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
   data->cb->Call( 2, info);
                          ^
In file included from ../src/odbc.h:23,
                 from ../src/odbc_connection.cpp:25:
../node_modules/nan/nan.h:1744:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/odbc_statement.cpp: In static member function 'static void ODBCStatement::UV_AfterExecute(uv_work_t*, int)':
../src/odbc_statement.cpp:246:27: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
     data->cb->Call(3, info);
                           ^
In file included from ../src/odbc.h:23,
                 from ../src/odbc_statement.cpp:24:
../node_modules/nan/nan.h:1744:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/odbc_statement.cpp: In static member function 'static void ODBCStatement::UV_AfterExecuteNonQuery(uv_work_t*, int)':
../src/odbc_statement.cpp:422:63: warning: 'v8::Local<v8::Value> Nan::Callback::Call(v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
     data->cb->Call(Nan::GetCurrentContext()->Global(), 2, info);
                                                               ^
In file included from ../src/odbc.h:23,
                 from ../src/odbc_statement.cpp:24:
../node_modules/nan/nan.h:1722:3: note: declared here
   Call(v8::Local<v8::Object> target
   ^~~~
../src/odbc_statement.cpp: In static member function 'static void ODBCStatement::UV_AfterExecuteDirect(uv_work_t*, int)':
../src/odbc_statement.cpp:573:27: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
     data->cb->Call(2, info);
                           ^
In file included from ../src/odbc.h:23,
                 from ../src/odbc_statement.cpp:24:
../node_modules/nan/nan.h:1744:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/odbc_statement.cpp: In static member function 'static void ODBCStatement::UV_AfterPrepare(uv_work_t*, int)':
../src/odbc_statement.cpp:778:28: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
     data->cb->Call( 2, info);
                            ^
In file included from ../src/odbc.h:23,
                 from ../src/odbc_statement.cpp:24:
../node_modules/nan/nan.h:1744:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/odbc_statement.cpp: In static member function 'static void ODBCStatement::UV_AfterBind(uv_work_t*, int)':
../src/odbc_statement.cpp:949:28: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
     data->cb->Call( 2, info);
                            ^
In file included from ../src/odbc.h:23,
                 from ../src/odbc_statement.cpp:24:
../node_modules/nan/nan.h:1744:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/odbc_statement.cpp: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE ODBCStatement::SetAttrSync(Nan::NAN_METHOD_ARGS_TYPE)':
../src/odbc_statement.cpp:980:84: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
       valuePtr = (SQLPOINTER)(Nan::To<v8::Int32>(info[1]).ToLocalChecked()->Value());
                                                                                    ^
../src/odbc_statement.cpp: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE ODBCStatement::SetAttr(Nan::NAN_METHOD_ARGS_TYPE)':
../src/odbc_statement.cpp:1047:90: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
       data->valuePtr = (SQLPOINTER)(Nan::To<v8::Int32>(info[1]).ToLocalChecked()->Value());
                                                                                          ^
../src/odbc_statement.cpp: In static member function 'static void ODBCStatement::UV_AfterSetAttr(uv_work_t*, int)':
../src/odbc_statement.cpp:1121:28: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
     data->cb->Call( 2, info);
                            ^
In file included from ../src/odbc.h:23,
                 from ../src/odbc_statement.cpp:24:
../node_modules/nan/nan.h:1744:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/odbc_statement.cpp: In static member function 'static void ODBCStatement::UV_AfterClose(uv_work_t*, int)':
../src/odbc_statement.cpp:1244:24: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
  data->cb->Call(1, info);
                        ^
In file included from ../src/odbc.h:23,
                 from ../src/odbc_statement.cpp:24:
../node_modules/nan/nan.h:1744:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/odbc_statement.cpp: In static member function 'static Nan::NAN_METHOD_RETURN_TYPE ODBCStatement::Close(Nan::NAN_METHOD_ARGS_TYPE)':
../src/odbc_statement.cpp:1183:21: warning: 'closeOption' may be used uninitialized in this function [-Wmaybe-uninitialized]
   data->closeOption = closeOption;
   ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
../src/odbc_result.cpp: In static member function 'static void ODBCResult::UV_AfterFetch(uv_work_t*, int)':
../src/odbc_result.cpp:287:27: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
     data->cb->Call(2, info);
                           ^
In file included from ../src/odbc.h:23,
                 from ../src/odbc_result.cpp:24:
../node_modules/nan/nan.h:1744:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/odbc_result.cpp:312:27: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
     data->cb->Call(2, info);
                           ^
In file included from ../src/odbc.h:23,
                 from ../src/odbc_result.cpp:24:
../node_modules/nan/nan.h:1744:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
../src/odbc_result.cpp: In static member function 'static void ODBCResult::UV_AfterFetchAll(uv_work_t*, int)':
../src/odbc_result.cpp:598:27: warning: 'v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const' is deprecated [-Wdeprecated-declarations]
     data->cb->Call(3, info);
                           ^
In file included from ../src/odbc.h:23,
                 from ../src/odbc_result.cpp:24:
../node_modules/nan/nan.h:1744:3: note: declared here
   Call(int argc, v8::Local<v8::Value> argv[]) const {
   ^~~~
/usr/bin/ld: cannot find -ldb2
collect2: error: ld returned 1 exit status
make: *** [odbc_bindings.target.mk:148: Release/obj.target/odbc_bindings.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 4.15.0-158-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=/app/node_modules/ibm_db/installer/clidriver"
gyp ERR! cwd /app/node_modules/ibm_db
gyp ERR! node -v v16.13.1
gyp ERR! node-gyp -v v8.3.0
gyp ERR! not ok 

    at ChildProcess.exithandler (node:child_process:397:12)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"'
}
Getting image source signatures
Copying blob sha256:de9bc33d733791f5dcdc296c0b8f06dcefd136c34b8f263716dc590adea53850
Copying blob sha256:effc4ea612c8cb531b45192df865c42f91ac1fa5da56a4af992e019934c442b9
Copying blob sha256:3fd4070f0c92f7359beabe954b2d9db3880f22bc8816ecf99f3c39c17ff875d7
Copying blob sha256:3b3e40b753e90aa16191234fa3f0e581b846f4e550d0cb39dbd2a2e8ab76c2f9
Copying config sha256:a45ce9acbfd52d8fea8ab62dc7c5c47ee3ac4bbe90c1974f383eedb81027ee5c
Writing manifest to image destination
Storing signatures
npm notice 
npm notice New minor version of npm available! 8.1.2 -> 8.5.5
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.5.5>
npm notice Run `npm install -g npm@8.5.5` to update!
npm notice 
npm ERR! code 1
npm ERR! path /app/node_modules/ibm_db
npm ERR! command failed
npm ERR! command sh -c node installer/driverInstall.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/app-root/src/.npm/_logs/2022-03-21T19_11_06_437Z-debug.log
subprocess exited with status 1
subprocess exited with status 1
error building at STEP "RUN ls && cd node_modules/ibm_db && npm install": exit status 1
time="2022-03-21T19:11:09Z" level=error msg="exit status 1"
Dockerfile build failed - exit status 1exit status 1
```

**Comment by bimalkjha** [comment]
@sbohner14335 Seems the pre-existing clidriver (/app/node_modules/ibm_db/installer/clidriver) is causing issue. Please use below docker file:
```
FROM registry.cirrus.ibm.com/public/nodejs-16:latest
USER root
RUN dnf update -y && dnf upgrade -y
WORKDIR /app
COPY . /app
rm -rf /app/node_modules/ibm_db/installer/clidriver
ARG BUILD
RUN ls && cd node_modules/ibm_db && npm install
RUN npm install && npm run $BUILD
EXPOSE 8081
CMD npm run start
```
If possible, push your app without /app/node_modules and use `RUN ls && npm install ibm_db` after `ARG BUILD` command. Thanks.

**Comment by mosestenai** [comment]
If you are running inside a docker container as I am, all you need is a .dockerignore with 'node_modules' specified in it.

Some libraries need to be compiled on the host machine and therefore your modules can be stale.
This worked for me on the odbc error--   "/app/node_modules/ibm_db/build/Release/odbc_bindings.node: invalid ELF header"
