### ISSUE TITLE
Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"

### ISSUE THREAD

**Issue by C4stleB** [ibmdb/node-ibm_db#775]
`npm install ibm_db`  fails with below.
I'm behind corporate proxy, so I already have done with `npm config set proxy` , `npm config set https-proxy`.

how can I solve this?

````
> ibm_db@2.7.4 install /usr/app/src/node_modules/ibm_db
> node installer/driverInstall.js

platform =  linux , arch =  x64 , node.js version =  v12.22.1
make version = GNU Make 4.2.1
Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz...

100.00% | 24805204 bytes downloaded out of 24805204 bytes.

****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in undefined   Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
****************************************

Downloading and extraction of DB2 ODBC CLI Driver completed successfully ...


Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: There was a fatal problem while downloading/extracting the tarball
gyp ERR! stack     at afterTarball (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:212:21)
gyp ERR! System Linux 3.10.0-1160.25.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IS_DOWNLOADED=true" "--IBM_DB_HOME=/usr/app/src/node_modules/ibm_db/installer/clidriver"
gyp ERR! cwd /usr/app/src/node_modules/ibm_db
gyp ERR! node -v v12.22.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=true --IBM_DB_HOME="$IBM_DB_HOME"'
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN dspbasic-api-jssampleapp@1.0.0 No description

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ibm_db@2.7.4 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ibm_db@2.7.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-17T16_07_48_448Z-debug.log
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
````

**Comment by bimalkjha** [comment]
@C4stleB I see this error in the pasted output: `gyp ERR! stack Error: There was a fatal problem while downloading/extracting the tarball`
I think this issue should be temporary. Anyway, you can try below steps:
Download https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/linuxx64_odbc_cli.tar.gz and untar it. You'll get clidriver directory. Now, cd to clidriver and run `pwd` command. Copy the full path. Then,
```
export IBM_DB_HOME=pull_path_of_clidriver
npm install ibm_db
```
I hope above steps will solve the issue. If it fails, please share complete output of `npm install ibm_db` again. Thanks.

**Comment by C4stleB** [comment]
@bimalkjha 
thank you for your reply.
it was not due to downloading odbc cli, but node header.
i found that node-gyp tries to download a tarball of node header, but i fails as of proxy setting.
because i could not find a way to add proxy setting to node-gyp, i just decided to download it by myself and copy it as below.

```
COPY ./tarball/node-v12.22.1-headers.tar.gz /tmp/node-v12.22.1-headers.tar.gz
RUN npm config set tarball /tmp/node-v12.22.1-headers.tar.gz
```

anyway, it worked for me.
