### ISSUE TITLE
installing ibm_db on Windows

### ISSUE THREAD

**Issue by hizir-bc** [ibmdb/node-ibm_db#785]
Hello,
 we are trying to use this package on Windows 10 and facing the following issue while running the test. 

---------------------------------------------------------------------------------------------------------------------------

**You can see the version information**

node: v14.17.4
npm: 6.14.14

---------------------------------------------------------------------------------------------------------------------------
**output from our test run**
```
npm run test skytest.test.ts

FAIL src/test/samples/db2/skytest.test.ts
  ● Test suite failed to run

    The specified module could not be found.
    \\?\C:\Users\sky\sky-sample\node_modules\ibm_db\build\Release\odbc_bindings.node

      at Runtime._loadModule (node_modules/jest-runtime/build/index.js:893:29)
      at bindings (node_modules/ibm_db/node_modules/bindings/bindings.js:112:48)
      at Object.<anonymous> (node_modules/ibm_db/lib/odbc.js:57:31)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        6.079 s
Ran all test suites matching /skytest.test.ts/i.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sky-sample@1.0.0 test: `jest "skytest.test.ts"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sky-sample@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sky\AppData\Roaming\npm-cache\_logs\2021-08-06T17_59_02_472Z-debug.log
```
---------------------------------------------------------------------------------------------------------------------------

**Output from npm install inside the node_modules/ibm_db directory**

```
cd node_modules\ibm_db
npm install
> ibm_db@2.7.4 install C:\Users\sky\sky-sample\node_modules\ibm_db
> node installer/driverInstall.js

platform =  win32 , arch =  x64 , node.js version =  v14.17.4
Rebuild Process: Found clidriver at -> C:\Users\sky\sky-sample\node_modules\ibm_db\installer\clidriver

Downloading of clidriver skipped - build is in progress...


C:\Users\sky\sky-sample\node_modules\ibm_db>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=true --IBM_DB_HOME=$IBM_DB_HOME )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=true --IBM_DB_HOME=$IBM_DB_HOME ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  odbc.cpp
  odbc_connection.cpp
  odbc_statement.cpp
  odbc_result.cpp
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_statement.cpp(246,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_statement.cpp(422,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_statement.cpp(573,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_statement.cpp(778,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_statement.cpp(949,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_statement.cpp(980,85): warning C4312: 'type cast': conversion from 'int32_t' to 'SQLPOINTER' of greater size [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_statement.cpp(1047,91): warning C4312: 'type cast': conversion from 'int32_t' to 'SQLPOINTER' of greater size [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_statement.cpp(1121,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_statement.cpp(1244,10): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_result.cpp(287,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_result.cpp(312,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_result.cpp(598,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc.cpp(216,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc.cpp(228,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc.cpp(705,73): warning C4311: 'type cast': pointer truncation from 'SQLHSTMT' to 'long' [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc.cpp(705,73): warning C4302: 'type cast': truncation from 'SQLHSTMT' to 'long' [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc.cpp(706,33): warning C4311: 'type cast': pointer truncation from 'SQLHSTMT' to 'long' [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc.cpp(706,33): warning C4302: 'type cast': truncation from 'SQLHSTMT' to 'long' [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc.cpp(1413,5): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_connection.cpp(310,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_connection.cpp(534,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_connection.cpp(909,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_connection.cpp(1094,60): warning C4312: 'type cast': conversion from 'int32_t' to 'SQLPOINTER' of greater size [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_connection.cpp(1148,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_connection.cpp(1178,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_connection.cpp(1341,55): warning C4312: 'type cast': conversion from 'int32_t' to 'SQLPOINTER' of greater size [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_connection.cpp(1714,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_connection.cpp(1896,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_connection.cpp(2100,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  win_delay_load_hook.cc
  strptime.c
     Creating library C:\Users\sky\sky-sample\node_modules\ibm_db\build\Release\odbc_bindings.lib and object C:\Users\sky\sky-sample\node_modules\ibm_db\build\Release\odbc_bindings.exp
  odbc_bindings.vcxproj -> C:\Users\sky\sky-sample\node_modules\ibm_db\build\Release\\odbc_bindings.node


Kernel additional dependencies removed successfully!

Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  odbc.cpp
  odbc_connection.cpp
  odbc_statement.cpp
  odbc_result.cpp
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_connection.cpp(310,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_connection.cpp(534,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc.cpp(216,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_connection.cpp(909,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc.cpp(228,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_connection.cpp(1094,60): warning C4312: 'type cast': conversion from 'int32_t' to 'SQLPOINTER' of greater size [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc.cpp(705,73): warning C4311: 'type cast': pointer truncation from 'SQLHSTMT' to 'long' [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc.cpp(705,73): warning C4302: 'type cast': truncation from 'SQLHSTMT' to 'long' [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc.cpp(706,33): warning C4311: 'type cast': pointer truncation from 'SQLHSTMT' to 'long' [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_connection.cpp(1148,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc.cpp(706,33): warning C4302: 'type cast': truncation from 'SQLHSTMT' to 'long' [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_connection.cpp(1178,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_connection.cpp(1341,55): warning C4312: 'type cast': conversion from 'int32_t' to 'SQLPOINTER' of greater size [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_connection.cpp(1714,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc.cpp(1413,5): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_connection.cpp(1896,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_connection.cpp(2100,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_result.cpp(287,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_result.cpp(312,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_result.cpp(598,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_statement.cpp(246,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_statement.cpp(422,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_statement.cpp(573,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_statement.cpp(778,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_statement.cpp(949,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_statement.cpp(980,85): warning C4312: 'type cast': conversion from 'int32_t' to 'SQLPOINTER' of greater size [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_statement.cpp(1047,91): warning C4312: 'type cast': conversion from 'int32_t' to 'SQLPOINTER' of greater size [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_statement.cpp(1121,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\sky\sky-sample\node_modules\ibm_db\src\odbc_statement.cpp(1244,10): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\sky\sky-sample\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  win_delay_load_hook.cc
  strptime.c
     Creating library C:\Users\sky\sky-sample\node_modules\ibm_db\build\Release\odbc_bindings.lib and object C:\Users\sky\sky-sample\node_modules\ibm_db\build\Release\odbc_bindings.exp
  odbc_bindings.vcxproj -> C:\Users\sky\sky-sample\node_modules\ibm_db\build\Release\\odbc_bindings.node


node-ibm_db installed successfully!

audited 62 packages in 13.313s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by bimalkjha** [comment]
@hizir-bc Update database connection info in `ibm_db\test\config.testConnectionStrings.json` file and run `node test\test-basic-test.js`. Share the complete output of test file execution. Thanks.

**Comment by hizir-bc** [comment]
@bimaljha thanks for your reply, please see the details below,
-----
**It appears, the connection is successful based on this test. Also I was able to access my existing table by editing this test code. You can find the output below.** I had to replace the für word with fur, it was somehow causing a problem.

```
Trying to open a connection ... 
 ... Got the connection.
insertedRows =  1
[ [ 1, 4, 5 ] ]
[]
Selected data with special character  =  [ [ 4, 'fur', null ] ]
[ [ 3, 7, 8 ] ]
Inserted row count = 1
Column Names =  [ 'C1', 'C2', 'C3' ]
Column Meta Data =  [
  {
    index: 1,
    SQL_DESC_CONCISE_TYPE: 'C1',
    SQL_DESC_TYPE_NAME: 'INTEGER',
    SQL_DESC_DISPLAY_SIZE: 11,
    SQL_DESC_PRECISION: 0,
    SQL_DESC_SCALE: 0,
    SQL_DESC_LENGTH: 11
  },
  {
    index: 2,
    SQL_DESC_CONCISE_TYPE: 'C2',
    SQL_DESC_TYPE_NAME: 'VARCHAR',
    SQL_DESC_DISPLAY_SIZE: 10,
    SQL_DESC_PRECISION: 0,
    SQL_DESC_SCALE: 0,
    SQL_DESC_LENGTH: 10
  },
  {
    index: 3,
    SQL_DESC_CONCISE_TYPE: 'C3',
    SQL_DESC_TYPE_NAME: 'BLOB',
    SQL_DESC_DISPLAY_SIZE: 200,
    SQL_DESC_PRECISION: 0,
    SQL_DESC_SCALE: 0,
    SQL_DESC_LENGTH: 100
  }
]
Fetched Data = 
[
  { C1: 4, C2: 'fur', C3: null },
  { C1: 34245, C2: 'bimal', C3: null }
]
conn.querySync('select * from mytab1 where c1 = ?;', valueArray)
[ [ 34245, 'bimal', null ] ]
Result of UPDATE Query =  [ [], [ [ 1 ] ] ]
SQLCA =  { state: '0', sqlcode: 0 }
conn.prepare('delete from mytab1 where c1 = 89')
Deleted row count = 0
done
```

-----
I have a test file db2test.test.ts, when I want to execute **_npm run test db2test.test.ts_** command, I see the following error:

```
C:\Users\sky\sky-sample> npm run test db2test.test.ts

> skyy-sample@1.0.0 test C:\Users\sky\sky-sample
> jest "db2test.test.ts"

 FAIL  src/test/samples/db2/db2test.test.ts
  ● Test suite failed to run

    The specified module could not be found.
    \\?\C:\Users\sky\sky-sample\node_modules\ibm_db\build\Release\odbc_bindings.node

      at Runtime._loadModule (node_modules/jest-runtime/build/index.js:893:29)
      at bindings (node_modules/ibm_db/node_modules/bindings/bindings.js:112:48)
      at Object.<anonymous> (node_modules/ibm_db/lib/odbc.js:57:31)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        6.604 s
Ran all test suites matching /db2test.test.ts/i.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! skyy-sample@1.0.0 test: `jest "db2test.test.ts"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the skyy-sample@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sky\AppData\Roaming\npm-cache\_logs\2021-08-09T19_47_19_853Z-debug.log
PS C:\Users\sky\sky-sample>
```

**Comment by bimalkjha** [comment]
@hizir-bc Since, `node test\test-basic-test.js` working fine, so installation of `ibm_db` is good and it is working well using node.js scripts too.
The problem looks the way you want to use ibm_db. The root cause of the problem is `jest`. You can convert `test-basic-test.js` to a typescript file and run it to validate.
Loading of odbc_bindings.node may fail if dependent library is not in PATH and LIB system environment variables. Set below environment variables and then try:
```
set PATH=C:\Users\sky\sky-sample\node_modules\ibm_db\installer\clidriver\bin;C:\Users\sky\sky-sample\node_modules\ibm_db\installer\clidriver\lib;%PATH%
set LIB=C:\Users\sky\sky-sample\node_modules\ibm_db\installer\clidriver\bin;C:\Users\sky\sky-sample\node_modules\ibm_db\installer\clidriver\lib;%LIB%
```
Thanks.

**Comment by bimalkjha** [comment]
@hizir-bc Your test result points out that there is some issue with Jest framework which is causing the failure. If same test file is working from npx, it should work from Jest too. Better to post your question on stackoverflow and someone having expertise in Jest could help! Thanks.

**Comment by hizir-bc** [comment]
Hi Bimal,

Thanks for spending your time with this matter, I appreciate it! We were finally able to identify the issue, you can see the details below. We ended up with adding more environment variables. You can see it below for the future reference if you need.
Thanks for all!

```
set PATH=C:\Users\sky\sky-sample\node_modules\ibm_db\installer\clidriver\bin;C:\Users\sky\sky-sample\node_modules\ibm_db\installer\clidriver\bin\amd64.VC12.CRT;C:\Users\sky\sky-sample\node_modules\ibm_db\installer\clidriver\bin\icc64;C:\Users\sky\sky-sample\node_modules\ibm_db\installer\clidriver\lib;C:\Users\sky\sky-sample\node_modules\.bin;%PATH%

set LIB=C:\Users\sky\sky-sample\node_modules\ibm_db\installer\clidriver\bin;C:\Users\sky\sky-sample\node_modules\ibm_db\installer\clidriver\bin\icc64;C:\Users\sky\sky-sample\node_modules\ibm_db\installer\clidriver\lib;%LIB%
```

**Comment by bimalkjha** [comment]
Great! Thanks @hizir-bc for sharing the valuable info here. Closing the issue now.
