### ISSUE TITLE
ibm_db npm module is not installed properly on Mac 

### ISSUE THREAD

**Issue by sagarcasm** [ibmdb/node-ibm_db#888]
**Laptop config:**
```
Model Name:	MacBook Pro
Model Identifier:	MacBookPro15,1
Processor Name:	6-Core Intel Core i7
Processor Speed:	2.6 GHz
Memory:	16 GB
OS: Monterey 12.6
```
**Node version** : v14.19.3

**Installation log:**
```
sagar.s@ibm.test.com@Sagars-MacBook-Pro-2 backend % cd node_modules/ibm_db
sagar.s@ibm.test.com@Sagars-MacBook-Pro-2 ibm_db % npm install
npm notice Beginning October 4, 2021, all connections to the npm registry - including for package installation - must use TLS 1.2 or higher. You are currently using plaintext http to connect. Please visit the GitHub blog for more information: https://github.blog/2021-08-23-npm-registry-deprecating-tls-1-0-tls-1-1/

> ibm_db@3.0.0 install /Users/sagar.s@ibm.test.com/Projects/cedp-uxui/cedp-ui-landing-interface/backend/node_modules/ibm_db
> node installer/driverInstall.js

platform = darwin, arch = x64, node.js version = v14.19.3
make version =GNU Make 3.81

****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in /Users/sagar.s@ibm.test.com/Projects/cedp-uxui/cedp-ui-landing-interface/backend/node_modules/ibm_db/installer/clidriver. Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
****************************************

Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz ...

100.00% | 30407976 bytes downloaded out of 30407976 bytes.

Downloading and extraction of DB2 ODBC CLI Driver completed successfully.

  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_connection.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_statement.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_result.o
  SOLINK_MODULE(target) Release/odbc_bindings.node

ibm_db installed successfully.
npm notice created a lockfile as package-lock.json. You should commit this file.
added 61 packages from 51 contributors in 119.954s

3 packages are looking for funding
  run `npm fund` for details
```
Running the ibm-db connect gives me the below error every time I do a fresh `npm install` it is just frustrating at this point to setup the and rename the `libstdc++.6.dylib` file in the `installer/lib/` directory.

```
node(92226,0x106648600) malloc: *** error for object 0x7ffb443e8440: pointer being freed was not allocated
node(92226,0x106648600) malloc: *** set a breakpoint in malloc_error_break to debug
[nodemon] app crashed - waiting for file changes before starting...
```
Even if I get a fix by renaming the file - our `jest` doesn't recognise the `ibm_db` import and gives the below error
```
 FAIL  app/__tests__/server.test.js
  ● Test suite failed to run

    Could not locate the bindings file. Tried:
     → /Users/sagar.s@ibm.test.com@ibm.com/Projects/cedp-uxui/cedp-ui-landing-interface/backend/node_modules/ibm_db/lib/build/odbc_bindings.node
     → /Users/sagar.s@ibm.test.com@ibm.com/Projects/cedp-uxui/cedp-ui-landing-interface/backend/node_modules/ibm_db/lib/build/Debug/odbc_bindings.node
     → /Users/sagar.s@ibm.test.com@ibm.com/Projects/cedp-uxui/cedp-ui-landing-interface/backend/node_modules/ibm_db/lib/build/Release/odbc_bindings.node
     → /Users/sagar.s@ibm.test.com@ibm.com/Projects/cedp-uxui/cedp-ui-landing-interface/backend/node_modules/ibm_db/lib/out/Debug/odbc_bindings.node
     → /Users/sagar.s@ibm.test.com/Projects/cedp-uxui/cedp-ui-landing-interface/backend/node_modules/ibm_db/lib/Debug/odbc_bindings.node
     → /Users/sagar.s@ibm.test.com@ibm.com/Projects/cedp-uxui/cedp-ui-landing-interface/backend/node_modules/ibm_db/lib/out/Release/odbc_bindings.node
     → /Users/sagar.s@ibm.test.com/Projects/cedp-uxui/cedp-ui-landing-interface/backend/node_modules/ibm_db/lib/Release/odbc_bindings.node
     → /Users/sagar.s@ibm.test.com/Projects/cedp-uxui/cedp-ui-landing-interface/backend/node_modules/ibm_db/lib/build/default/odbc_bindings.node
     → /Users/sagar.s@ibm.test.com/Projects/cedp-uxui/cedp-ui-landing-interface/backend/node_modules/ibm_db/lib/compiled/14.19.3/darwin/x64/odbc_bindings.node
     → /Users/sagar.s@ibm.test.com/Projects/cedp-uxui/cedp-ui-landing-interface/backend/node_modules/ibm_db/lib/addon-build/release/install-root/odbc_bindings.node
     → /Users/sagar.s@ibm.test.com/Projects/cedp-uxui/cedp-ui-landing-interface/backend/node_modules/ibm_db/lib/addon-build/debug/install-root/odbc_bindings.node
     → /Users/sagar.s@ibm.test.com/Projects/cedp-uxui/cedp-ui-landing-interface/backend/node_modules/ibm_db/lib/addon-build/default/install-root/odbc_bindings.node
     → /Users/sagar.s@ibm.test.com/Projects/cedp-uxui/cedp-ui-landing-interface/backend/node_modules/ibm_db/lib/lib/binding/node-v83-darwin-x64/odbc_bindings.node

```

Please find the error after running the node `test-basic-test.js` file

```
sagar.s@ibm.test.com@Sagars-MacBook-Pro-2 test % node test-basic-test.js 
/Users/sagar.s@ibm.test.com/Projects/cedp-uxui/cedp-ui-landing-interface/backend/node_modules/ibm_db/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: The module '/Users/sagar.s@ibm.test.com/Projects/cedp-uxui/cedp-ui-landing-interface/backend/node_modules/ibm_db/build/Release/odbc_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 83. This version of Node.js requires
NODE_MODULE_VERSION 93. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/Users/sagar.s@ibm.test.com/Projects/cedp-uxui/cedp-ui-landing-interface/backend/node_modules/ibm_db/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/sagar.s@ibm.test.com/Projects/cedp-uxui/cedp-ui-landing-interface/backend/node_modules/ibm_db/lib/odbc.js:57:31)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'ERR_DLOPEN_FAILED'
}
```

Can you please help me as my entire team with macs is just frustrated at this point 

Concluding Issues:
1. `malloc: *** error for object 0x7ffb443e8440` error after a simple install - already have a temporary solution need a defintite one
2. Jest cannot locate the bindings file

**Comment by bimalkjha** [comment]
@sagarcasm 1. To avoid this malloc issue which is system related, copy the ibm_db/installer/clidriver directory outside node_modules somewhere in the system and set system environment variable `IBM_DB_HOME=<full path of clidriver>`. If IBM_DB_HOME is set, `npm install ibm_db` will not download clidriver and no need to delete the libstdc++.6.dylib file manually every time.

2. Jest able to locate the bindings file as bindings file is present in the path. But, Jest is unable to load the bindings file as bindings file was generated using node version 14.x but Jest is trying to use it using node version 16.x.
NODE_MODULE_VERSION 83 is for Node.js 14.x
NODE_MODULE_VERSION 93 is for Node.js 16.x

when you run `node test-basic-test.js`, the node.js version is 16.x but your ibm_db was installed using node.js version 14.x. Please check output of `node -v` just after `node node test-basic-test.js` fails. Keep the same node.js version of your system and Jest both to fix this issue.

If you are still facing issue, execute below commands from terminal and share complete output of all commands in a file:
```
cp -r /Users/sagar.s@ibm.test.com/Projects/cedp-uxui/cedp-ui-landing-interface/backend/node_modules/ibm_db/installer/clidriver  /Users/sagar.s@ibm.test.com/Projects/clidriver
export IBM_DB_HOME=/Users/sagar.s@ibm.test.com/Projects/clidriver
rm /Users/sagar.s@ibm.test.com/Projects/clidriver/lib/libstdc++.6.dylib
otool -L /Users/sagar.s@ibm.test.com/Projects/clidriver/lib/libdb2.dylib
ls /usr/local/lib/gcc
gcc -v
uname -a
cd /Users/sagar.s@ibm.test.com/Projects/cedp-uxui/cedp-ui-landing-interface/backend/
npm uninstall ibm_db
npm install ibm_db
node -v
node test/test-basic-test.js
ls /Users/sagar.s@ibm.test.com/Projects/cedp-uxui/cedp-ui-landing-interface/backend/node_modules/ibm_db/build/Release/odbc_bindings.node
```
Thanks.

**Comment by sagarcasm** [comment]
Manually copying the driver to another directory is still not permanent solution,  we use a forked git strategy and explaining this setup for `ibm_db` npm module for the developers with Mac is not what we are looking for -  this needs to be fixed.

**Comment by bimalkjha** [comment]
@sagarcasm Update file https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz without `libstdc++.6.dylib`. Please test and confirm. Thanks.
