### ISSUE TITLE
Segmentation fault when running `node run-tests.js` in my alpine docker container.

### ISSUE THREAD

**Issue by janvda** [ibmdb/node-ibm_db#895]
- Operating System Name:

1.  Alpine docker container:
```
Linux 8ceec160c0bf 5.10.93-0-virt #1-Alpine SMP Thu, 27 Jan 2022 09:34:38 +0000 x86_64 Linux
```

2.  docker host machine is macbook pro

- node.js, ... Version:

```
bash-5.0$ node --version
v16.13.1
bash-5.0$ python --version
Python 2.7.18
bash-5.0$ gcc --version
gcc (Alpine 9.3.0) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

- For non-Windows, output of below commands:
  uname
  uname -m

```
bash-5.0$ uname
Linux
bash-5.0$ uname -m
x86_64
bash-5.0$ 
```

- Value of below environment variables if set:
  IBM_DB_HOME:
  PATH:
  LIB/LD_LIBRARY_PATH/DYLD_LIBRARY_PATH:

only PATH is set.

```
NODE_PATH=/usr/src/node-red/node_modules:/data/node_modules
PATH=/usr/src/node-red/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NODE_VERSION=16.13.1
```

- Test script to reproduce the problem.

```
bash-5.0$ node run-tests.js
Segmentation fault (core dumped)
bash-5.0$
```

- For installation related issue, complete output of `npm install ibm_db` command.
- For connection related issue, update database connection info in `ibm_db/test/config.testConnectionStrings.json` file and share complete output of below commands:
  * cd .../ibm_db
  * npm install
  * node test/test-basic-test.js

```
bash-5.0$  node test/test-basic-test.js
Segmentation fault (core dumped)
bash-5.0$ 
```

**Comment by janvda** [comment]
FYI 

I am using docker image:  `nodered/node-red:2.2.3-16`
I have installed packages
```
RUN apk add alpine-sdk libc6-compat linux-pam libxml2 python2 sudo loksh
```

I have installed ibm_db in folder `/data/node_modules` by following commands:

```
cd /data
npm install ibm_db
```

**Comment by janvda** [comment]
I have same problem with alpine image: `node:14-alpine3.14`.

I could install it.
Then I had to install following packages to fix errors but this didn't fix.  I am still getting segmentation fault.

```
apk add libc6-compat linux-pam libxml2
```

The error logs:

```
/data/node_modules/ibm_db/test # node test-connection-object.js 
/data/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: Error loading shared library libcrypt.so.1: No such file or directory (needed by /data/node_modules/ibm_db/build/Release/../../installer/clidriver/lib/libdb2.so.1)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at bindings (/data/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/data/node_modules/ibm_db/lib/odbc.js:57:31)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_DLOPEN_FAILED'
}
/data/node_modules/ibm_db/test # apk add libc6-compat
(1/1) Installing libc6-compat (1.2.2-r3)
OK: 261 MiB in 63 packages
/data/node_modules/ibm_db/test # node test-connection-object.js 
/data/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: Error loading shared library libpam.so.0: No such file or directory (needed by /data/node_modules/ibm_db/build/Release/../../installer/clidriver/lib/libdb2.so.1)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at bindings (/data/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/data/node_modules/ibm_db/lib/odbc.js:57:31)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_DLOPEN_FAILED'
}
/data/node_modules/ibm_db/test # apk add linux-pam
(1/1) Installing linux-pam (1.5.1-r1)
Executing busybox-1.33.1-r7.trigger
OK: 262 MiB in 64 packages
/data/node_modules/ibm_db/test # node test-connection-object.js 
/data/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: Error loading shared library libxml2.so.2: No such file or directory (needed by /data/node_modules/ibm_db/build/Release/../../installer/clidriver/lib/libdb2.so.1)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at bindings (/data/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/data/node_modules/ibm_db/lib/odbc.js:57:31)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  code: 'ERR_DLOPEN_FAILED'
}
/data/node_modules/ibm_db/test # apk add libxml2
(1/1) Installing libxml2 (2.9.14-r2)
OK: 263 MiB in 65 packages
/data/node_modules/ibm_db/test # node test-connection-object.js 
Segmentation fault (core dumped)
/data/node_modules/ibm_db/test # 
```

**Comment by janvda** [comment]
I didn't get a segmentation fault when using the default image :  `node`

The command to start the container:

```
docker run node sh -c 'while sleep 3600; do :; done'
```

Note that this image contained everything.  So I didn't need to install any additional packages.


This is the output:

```
root@f5dfaca57cf6:/data# npm install ibm_db 

added 60 packages, and audited 61 packages in 1m

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
root@f5dfaca57cf6:/data# ls
node_modules  package-lock.json  package.json
root@f5dfaca57cf6:/data# cd node_modules/
root@f5dfaca57cf6:/data/node_modules# ls
axios            buffer-alloc             core-util-is      fstream      listenercount     process-nextick-args  tar-fs          wrappy
balanced-match   buffer-alloc-unsafe      duplexer2         glob         lodash            pump                  tar-stream      xtend
big-integer      buffer-fill              end-of-stream     graceful-fs  minimatch         q                     targz
binary           buffer-indexof-polyfill  file-uri-to-path  ibm_db       minimist          readable-stream       to-buffer
bindings         buffers                  follow-redirects  inflight     mkdirp            rimraf                traverse
bl               chainsaw                 fs-constants      inherits     nan               safe-buffer           universalify
bluebird         chownr                   fs-extra          isarray      once              setimmediate          unzipper
brace-expansion  concat-map               fs.realpath       jsonfile     path-is-absolute  string_decoder        util-deprecate
root@f5dfaca57cf6:/data/node_modules# cd ibm_db/test/
root@f5dfaca57cf6:/data/node_modules/ibm_db/test# node test-connection-object.js 
node:assert:124
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: [Error: [IBM][CLI Driver] SQL1336N  The remote host "waldevdbclnxtst06.dev.rocketsoftware.com" was not found.  SQLSTATE=08001
] {
  error: '[ibm_db] SQL_ERROR',
  sqlcode: -1336,
  state: '08001'
} == null
    at /data/node_modules/ibm_db/test/test-connection-object.js:8:10
    at /data/node_modules/ibm_db/lib/odbc.js:371:18 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: [Error: [IBM][CLI Driver] SQL1336N  The remote host "waldevdbclnxtst06.dev.rocketsoftware.com" was not found.  SQLSTATE=08001
  ] {
    error: '[ibm_db] SQL_ERROR',
    sqlcode: -1336,
    state: '08001'
  },
  expected: null,
  operator: '=='
}

Node.js v19.1.0
root@f5dfaca57cf6:/data/node_modules/ibm_db/test# 
```

**Comment by bimalkjha** [comment]
@janvda ibm_db do not work on Alpine Linux. See the issue #217 for details. Thanks.

**Comment by janvda** [comment]
I have lost a lot of time with this issue.
In the end I got it working by using images based on debian instead of alpine.  (e.g. `node:19.1.0-bullseye-slim` or `node:16-buster-slim`).

If it is not supported on alpine based docker images then it would be good to mention this in the prerequisites section of the readme as the alpine images are very popular due to their reduced size.

Note also that all nodered docker images at docker hub (https://hub.docker.com/r/nodered/node-red) are based on alpine.  So you don't have immediately an alternative unless you decide to build nodered yourselves based on debian image (which I had to do).

I also believe that there must be a way to install this properly on alpine.
FYI also for the debian based builds I needed to add the following to my dockerfile to get it working:

```
# fix missing libxml2 and libc.musl-x86_64.so.1 (see https://github.com/alexander-akhmetov/python-telegram/issues/3)  and
RUN apt-get update && apt-get install -y musl-dev libxml2
RUN ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1
```

**Comment by bimalkjha** [comment]
@janvda The segmentation fault is because `clidriver/lib/libdb2.so.1` is not compatible with `libc.musl-x86_64.so.1`. If you run `ldd libdb2.so.1`, you'll get the missing symbols.
As mentioned the details in this [comment](https://github.com/ibmdb/node-ibm_db/issues/894#issuecomment-1351987365), Alpine Linux is not a supported platform for node ibm_db as we have add this info in the latest documentation of ibm_db. Hence, closing this issue. Thanks.

**Comment by bimalkjha** [comment]
@janvda If you want it should work on Alpine Linux too in future, please open an idea here https://ideas.ibm.com/ to compile Db2 clidriver using musl gcc for Alpine Linux. Thanks.
