### ISSUE TITLE
Can't install on Windows 7

### ISSUE THREAD

**Issue by qntm** [ibmdb/node-ibm_db#9]
Following the instructions at https://www.npmjs.org/package/ibm_db, I have the IBM DB2 v9.7 Data Server Driver installed at `C:\Program Files\ibm\IBM DATA SERVER DRIVER` and I have set the environment variable:

```
set IBM_DB_HOME=C:\Program Files\ibm\IBM DATA SERVER DRIVER
```

However the result when I run `npm install ibm_db` is:

```
C:\Users\admin\Documents\2014-07-21 - Cloud Integration\pvanrun>npm install ibm_db
npm WARN package.json SQLDBNode@0.0.1 No repository field.
/


> ibm_db@0.0.1 preinstall C:\Users\admin\Documents\2014-07-21 - Cloud Integration\pvanrun\node_modules\ibm_db
> node-gyp configure build


C:\Users\admin\Documents\2014-07-21 - Cloud Integration\pvanrun\node_modules\ibm_db>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  odbc.cpp
  odbc_connection.cpp
  odbc_statement.cpp
  odbc_result.cpp
  dynodbc.cpp
c:\users\admin\documents\2014-07-21 - cloud integration\pvanrun\node_modules\ibm_db\src\odbc.h(29): fatal error C1083: Cannot open include file: 'sqlcli1.h': No such file or directory (..\src\odbc_connection.cpp) [C:\Users\admin\Documents\2014-07-21 - Cloud Integration\pvanrun\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\users\admin\documents\2014-07-21 - cloud integration\pvanrun\node_modules\ibm_db\src\odbc.h(29): fatal error C1083: Cannot open include file: 'sqlcli1.h': No such file or directory (..\src\odbc_statement.cpp) [C:\Users\admin\Documents\2014-07-21 - Cloud Integration\pvanrun\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\users\admin\documents\2014-07-21 - cloud integration\pvanrun\node_modules\ibm_db\src\odbc.h(29): fatal error C1083: Cannot open include file: 'sqlcli1.h': No such file or directory (..\src\odbc_result.cpp) [C:\Users\admin\Documents\2014-07-21 - Cloud Integration\pvanrun\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\users\admin\documents\2014-07-21 - cloud integration\pvanrun\node_modules\ibm_db\src\odbc.h(29): fatal error C1083: Cannot open include file: 'sqlcli1.h': No such file or directory (..\src\odbc.cpp) [C:\Users\admin\Documents\2014-07-21 - Cloud Integration\pvanrun\node_modules\ibm_db\build\odbc_bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build"
gyp ERR! cwd C:\Users\admin\Documents\2014-07-21 - Cloud Integration\pvanrun\node_modules\ibm_db
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
npm ERR! ibm_db@0.0.1 preinstall: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@0.0.1 preinstall script.
npm ERR! This is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ibm_db"
npm ERR! cwd C:\Users\admin\Documents\2014-07-21 - Cloud Integration\pvanrun
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\admin\Documents\2014-07-21 - Cloud Integration\pvanrun\npm-debug.log
npm ERR! not ok code 0
```

Things I have tried which failed to solve this problem: running the command from a DB2 command line; running from a Visual Studio command line; moving the drivers to a path with no spaces (`C:\IBM_DATA_SERVER_DRIVER`), adding the `include` directory to my `INCLUDE` environment variable.

**Comment by mariobriggs** [comment]
win32 not yet supported though
