### ISSUE TITLE
npm install failed on OS X and node v5.7.0

### ISSUE THREAD

**Issue by leondroidgeeks** [ibmdb/node-ibm_db#95]
Can't install the module ibm_db using npm on OS X: npm install ibm_db
I am using node v5.7.0 and npm v3.6.0, but it also happens using node version 0.10.36 and 0.12.7. I am running OS X El Capitan 10.11.3.

How can i solve this problem?

```
ibm_db@0.0.19 install /Users/Leon/Desktop/Neuer Ordner/node_modules/ibm_db
node installer/driverInstall.js

Downloading DB2 ODBC CLI Driver from http://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/macos64_odbc_cli.tar.gz...
Download and extraction of DB2 ODBC CLI Driver completed successfully ...

{ [Error: Command failed: node-gyp configure build --IBM_DB_HOME=$IBM_DB_HOME --IS_DOWNLOADED=true
make: *** No rule to make target `Ordner/node_modules/ibm_db/installer/clidriver'.  Stop.
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/Cellar/node/5.7.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--IBM_DB_HOME=/Users/Leon/Desktop/Neuer" "Ordner/node_modules/ibm_db/installer/clidriver" "--IS_DOWNLOADED=true"
gyp ERR! cwd /Users/Leon/Desktop/Neuer Ordner/node_modules/ibm_db
gyp ERR! node -v v5.7.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
]
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build --IBM_DB_HOME=$IBM_DB_HOME --IS_DOWNLOADED=true' }
npm WARN enoent ENOENT: no such file or directory, open '/Users/Leon/Desktop/Neuer Ordner/package.json'
npm WARN Neuer Ordner No description
npm WARN Neuer Ordner No repository field.
npm WARN Neuer Ordner No README data
npm WARN Neuer Ordner No license field.
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.7.0/bin/node" "/usr/local/bin/npm" "install" "ibm_db"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code ELIFECYCLE

npm ERR! ibm_db@0.0.19 install: `node installer/driverInstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ibm_db@0.0.19 install script 'node installer/driverInstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ibm_db package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node installer/driverInstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ibm_db
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ibm_db
npm ERR! There is likely additional logging output above.
```

**Comment by IronGremlin** [comment]
I think your issue might just be that your directory has a space in it.

That make error is a node-gyp failure being thrown because node-gyp can't find a particular file, and the error seems to state that "No rule to make target `Ordner/node_modules/ibm_db/installer/clidriver'. " 

Whereas earlier in the error output, the full directory seems to be:

"/Users/Leon/Desktop/Neuer Ordner/node_modules/ibm_db/installer/clidriver"

**Comment by leondroidgeeks** [comment]
That was the solution! Thank you very much!
