### ISSUE TITLE
unhandledrejection

### ISSUE THREAD

**Issue by huineng** [ibmdb/node-ibm_db#996]
ibm_db 3.2.4. node 20.12.2

i was doing some development as usual using some
try { await conn.query(sql,bindings) } catch (err) { throw err} (or Promise.reject)

the problem was that i by mistake provided for bindings [['string']] instead of ['string']

So i got my rejecting and this had a message like

```javascript
stack: Error: Wrong param format!
   at /node_modules/ibm_db/lib/odbc.js:677:19
   at SimpleQueue.next (/node_modules/ibm_db/lib/simple-queue.js:34:5)
   at SimpleQueue.maybeNext (/node_modules/ibm_db/lib/simple-queue.js:22:10)
   at SimpleQueue.push (/node_modules/ibm_db/lib/simple-queue.js:15:8)
   at Database.query (/node_modules/ibm_db/lib/odbc.js:520:14)
```

i guess this is from this line https://github.com/ibmdb/node-ibm_db/blob/a2f0018a74f076832c569f38af7ba2b6b7e73553/src/odbc.cpp#L988

fine

But then i got also a unhandledrejection with reason

```javascript
reason: Error: [IBM][CLI Driver] CLI0123E  SQL data type out of range. SQLSTATE=HY004
```

so it looks to me the code doesn't stop at the first error

thanks

**Comment by bimalkjha** [comment]
@huineng I tried to repro the issue on my Linux system using latest code of ibm_db and latest version of nodejs. But, I am unable to reproduce it. So, added a test case too. 
Could you please install latest code from git and run test file [test-asyc-await.js](https://github.com/ibmdb/node-ibm_db/blob/master/test/test-asyc-await.js) to verify it?
If issue is still reproducible for you, please share simple test program to reproduce it.

When I run the latest updated test-async-await.js file, getting output as below for Test3:
```
Test for issue #960 is done.
Got error, throwing it.
Error: Wrong param format!
    at /home/bjha/nodework/master/node-ibm_db/lib/odbc.js:677:19
    at SimpleQueue.next (/home/bjha/nodework/master/node-ibm_db/lib/simple-queue.js:34:5)
    at SimpleQueue.maybeNext (/home/bjha/nodework/master/node-ibm_db/lib/simple-queue.js:22:10)
    at SimpleQueue.push (/home/bjha/nodework/master/node-ibm_db/lib/simple-queue.js:15:8)
    at Database.query (/home/bjha/nodework/master/node-ibm_db/lib/odbc.js:520:14)
    at test3 (/home/bjha/nodework/master/node-ibm_db/test/test-asyc-await.js:80:20)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async main (/home/bjha/nodework/master/node-ibm_db/test/test-asyc-await.js:12:5)
Test3 done.
```
Thanks.

**Comment by huineng** [comment]
thanks Bimal for you rapid answer :)

i still have the unhandled rejection and doing a debug i get the same as you

```
Error: Wrong param format!
    at /workspaces/dsw-dashboard/node_modules/ibm_db/lib/odbc.js:677:19
    at SimpleQueue.next (/workspaces/dsw-dashboard/node_modules/ibm_db/lib/simple-queue.js:34:5)
    at SimpleQueue.maybeNext (/workspaces/dsw-dashboard/node_modules/ibm_db/lib/simple-queue.js:22:10)
    at SimpleQueue.push (/workspaces/dsw-dashboard/node_modules/ibm_db/lib/simple-queue.js:15:8)
    at Database.query (/workspaces/dsw-dashboard/node_modules/ibm_db/lib/odbc.js:520:14)
    at Db2.runQuery (/workspaces/dsw-dashboard/server/server.js:2256:37)
```
    
but my unhandled rejection is trowing a different message
    
```
[ibm_db] SQL_ERROR","sqlcode":-99999,"message":"[IBM][CLI Driver] CLI0123E  SQL data type out of range. SQLSTATE=HY004","state":"HY004","resultset":[]}
```

where is that message coming from ?    
   
You are running a file, i run a webserver with node that has a specific .on('unhandledRejection') handler
maybe that might explain ?

Thanks

**Comment by bimalkjha** [comment]
@huineng Are you able to reproduce your error using a simple test program? If not, please try making small test program. Then you can collect db2traces and we can look into trace file that which API is throwing CLI0123E error.
Also, you can install ibm_db in debug mode and run your test program, which will print API call sequence on screen and we can see from where error is comming.

If you can repro using small test program, try below commands to collect logs:
```
cd ..../ibm_db/installer
source ./setenv.sh
cd ..
npm install --debug
cd test
./trace test-async-await.js
```
Capture all output of test program to a file and zip the output file along with other generated 1.* file. You can attach zip file here.
If issue is reproducible only using your application, still you can build ibm_db using --debug option and run your test program. In debug mode, you can see lots of output of screen that you can analyze to find the root cause. Thanks.

**Comment by bimalkjha** [comment]
@huineng Any update? Can we close the issue? Thanks.

**Comment by huineng** [comment]
Hi Bimal, so i ran your test

but i first added this line at the top of the file

```
process
  .on('unhandledRejection', async (reason, p) => {
    console.debug('unhandled', reason, p)
  })

main();
async function main() {
```

and this was the result


```
Got error, throwing it.
Error: Wrong param format!
    at /workspaces/dsw-dashboard/node_modules/ibm_db/lib/odbc.js:677:19
    at SimpleQueue.next (/workspaces/dsw-dashboard/node_modules/ibm_db/lib/simple-queue.js:34:5)
    at SimpleQueue.maybeNext (/workspaces/dsw-dashboard/node_modules/ibm_db/lib/simple-queue.js:22:10)
    at SimpleQueue.push (/workspaces/dsw-dashboard/node_modules/ibm_db/lib/simple-queue.js:15:8)
    at Database.query (/workspaces/dsw-dashboard/node_modules/ibm_db/lib/odbc.js:520:14)
    at test3 (/workspaces/dsw-dashboard/node_modules/ibm_db/test/test-asyc-await.js:73:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/workspaces/dsw-dashboard/node_modules/ibm_db/test/test-asyc-await.js:22:5)
unhandled [Error: [IBM][CLI Driver] CLI0123E  SQL data type out of range. SQLSTATE=HY004] {
  error: '[ibm_db] SQL_ERROR',
  sqlcode: -99999,
  state: 'HY004',
  resultset: []
} Promise {
  promiseDispatch: [Function (anonymous)],
  inspect: [Function: inspect],
  exception: [Error: [IBM][CLI Driver] CLI0123E  SQL data type out of range. SQLSTATE=HY004] {
    error: '[ibm_db] SQL_ERROR',
    sqlcode: -99999,
    state: 'HY004',
    resultset: []
  },
  valueOf: [Function (anonymous)]
}
```

hope this helps
